### ISSUE TITLE
Install and configure `willow_sword`

### ISSUE THREAD

**Issue by kirkkwang** [scientist-softserv/palni-palci#1013]
# Story

Install and configure the `willow_sword` gem into Hyku

# Acceptance Criteria

- [ ] `willow_sword` is now installed and configured in Hyku

# Notes

This should be a no op change as we're just including a dependency.  Test functionality will be handled in a different ticket.

**Comment by kirkkwang** [comment]
https://github.com/scientist-softserv/palni-palci/issues/1013

**Comment by ShanaLMoore** [comment]
this was deployed to hyku staging and [demo](https://demo.hyku-demo.notch8.cloud/).
