### ISSUE TITLE
admin cannot deposit works into a collection

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#1046]
## Summary
https://assaydepot.slack.com/archives/C0313NKC08L/p1721066260232569

A user is reporting an issue depositing works into collections they should have access to (as an admin). I tried running the Create Collection Accesses data repair job from their dashboard, but is there a way I can check on the progress of that job?

This is on [wabash.hykucommons.org](http://wabash.hykucommons.org/)

## Acceptance Criteria
- [ ] Admins on [wabash.hykucommons.org](http://wabash.hykucommons.org/) can deposit works into collections

**Comment by aprilrieger** [comment]
https://assaydepot.slack.com/archives/C0313NKC08L/p1721403025423579?thread_ts=1721066260.232569&cid=C0313NKC08L

I also clicked the button to `Create Collections Accesses` and when I navigate to the aux worker pod and review the logs I see it completed in the log `2024-07-19T14:47:03.069998172Z 2024-07-19T14:47:03.069Z pid=1 tid=kw3sd class=RolesService::CreateCollectionAccessesJob jid=4303b62c1be8f8693e60b18d elapsed=0.755 INFO: done`

I am unable to replicate the issue on wabash as an admin.

Asking the client in thread:
`Can you give me more information to troubleshoot? Which user and which collection and what work on wabash tenant?`

**Comment by aprilrieger** [comment]
Client responded with more information:
```
So for this one, the user ([miller@wabash.edu](mailto:miller@wabash.edu)) has already deposited works and is trying to add them to this collection (https://wabash.hykucommons.org/dashboard/collections/d4efac9d-24d2-472e-85cd-1c7da1319ccd?locale=en) from the works dashboard. When he does, he gets this error message```

**Comment by aprilrieger** [comment]
https://assaydepot.slack.com/archives/C0313NKC08L/p1721411545380369?thread_ts=1721066260.232569&cid=C0313NKC08L

I don’t see any logs in the pods or in sentry around this issue and I cannot replicate it with my user (same as you I can add to the collection no problem). I suggest we set something up to have the user try while we search logs at the same time to capture the issue.

Asked client:
Are any other Admins having issues uploading to the collection? Or is it only this user?

**Comment by aprilrieger** [comment]
Client gave us a video from the client: https://wabash.app.box.com/s/0fy4gjp5rx4takg28iiy4ry7fss1c3pf/file/1595658354346

and sent this response: 
Is this the way the user previously added works to collections? and now cannot?
Can they go to the work and add the work to the collection via this workflow? https://share.zight.com/QwuoZvYD

**Comment by aprilrieger** [comment]
I was able to recreate the issue on our super admin user for pals. Video: https://share.zight.com/DOuEZWL5

url: `https://wabash.hykucommons.org/dashboard/works?utf8=%E2%9C%93&add_works_to_collection=d4efac9d-24d2-472e-85cd-1c7da1319ccd&add_works_to_collection_label%5B%5D=The+Bachelor+Archives&locale=en&q=The+Bachelor%2C+December+4%2C+2008`

I CAN add the work through a different workflow: https://share.zight.com/QwuoZvYD

Asked client to ask user of they can add the work to the collection this way to help isolate the issue more. Waiting to hear back.

**Comment by bkiahstroud** [comment]
Wonder if this is the same issue as: 

- https://github.com/samvera/hyrax/issues/6006 

@aprilrieger does the admin have permission for all collections on the first page of results, but not the second (or third, or fourth, etc)?

**Comment by aprilrieger** [comment]
User gave client more screen recordings to show us their workflow. The user CAN add an individual work to a collection from the collection show page. BUT still CANNOT from the dashboard my/works or my/collections pages.

folder of videos: https://wabash.app.box.com/s/0fy4gjp5rx4takg28iiy4ry7fss1c3pf

**Comment by bkiahstroud** [comment]
Other possible fixes: 

- https://github.com/samvera/hyku/pull/2040 
- https://github.com/osulp/Scholars-Archive/blob/main/app/controllers/hyrax/my/works_controller.rb#L34-L39

**Comment by aprilrieger** [comment]
@ndroark Thus was deployed in todays prod deployment, please have user check that it is fixed on their end, and let us know/close ticket. Thank you!

**Comment by aprilrieger** [comment]
Client stated this work solved the user's reported issue. Closing ticket as done.
