### ISSUE TITLE
pitt.hykucommons.org tenant produces an error when any logged in user attempts to access the Works dashboard, the Collections dashboard, or certain Collection pages

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#1050]
## Summary
https://assaydepot.slack.com/archives/C0313NKC08L/p1724693163100939

the [pitt.hykucommons.org](http://pitt.hykucommons.org/) tenant produces an error when any logged in user attempts to access the Works dashboard, the Collections dashboard (or the All tab of the Collections dashboard if that user hasn't created any collections), or certain Collection pages. The error reads, "I'm sorry, I don't understand that search."

The error may be related to an import performed today that added a number of collections, some of which have the > character in the title. One such example that produces an error for logged in users is https://pittir.hykucommons.org/collections/43598e51-8dad-4591-888e-5bc011f1726a?q=bioengineering

This is a total stopper for work in the Pitt repo, and should be top priority now

## Acceptance Criteria
- [x] Cause of problem is documented
- [ ] Follow up ticket that includes the below acceptance criteria and to fix the issue is created
  - [ ] the [pitt.hykucommons.org](http://pitt.hykucommons.org/) tenant can access the Works dashboard
  - [ ] the [pitt.hykucommons.org](http://pitt.hykucommons.org/) tenant can access the collections dashboard
  - [ ] the [pitt.hykucommons.org](http://pitt.hykucommons.org/) tenant can access collection pages

**Comment by bkiahstroud** [comment]
## Results:

A `RSolr::Error::Http - 414 Request-URI Too Long` error is causing the user to be redirected to the tenant's landing page with the flash message `Sorry, I don't understand your search.`

<details><summary>Trace</summary>

```log
D, [2024-08-27T17:50:53.830589 #1] DEBUG -- : [aef3333e58ccd7c1a9c6e917f6c7c539]    (14.3ms)  SELECT DISTINCT "source_id" FROM "permission_template_accesses" INNER JOIN "p
ermission_templates" ON "permission_templates"."id" = "permission_template_accesses"."permission_template_id" WHERE "permission_template_accesses"."access" IN ($1, $2) AND
 ("permission_template_accesses"."agent_type" = $3 AND "permission_template_accesses"."agent_id" = $4 OR "permission_template_accesses"."agent_type" = $5 AND "permission_t
emplate_accesses"."agent_id" IN ($6, $7, $8))  [["access", "manage"], ["access", "deposit"], ["agent_type", "user"], ["agent_id", "support@notch8.com"], ["agent_type", "gr
oup"], ["agent_id", "public"], ["agent_id", "registered"], ["agent_id", "admin"]]
D, [2024-08-27T17:50:53.892566 #1] DEBUG -- : [aef3333e58ccd7c1a9c6e917f6c7c539] Solr parameters: {"facet.field"=>["visibility_ssi", "suppressed_bsi", "resource_type_sim",
 "has_model_ssim"], "facet.query"=>[], "facet.pivot"=>["has_model_ssim,collection_type_gid_ssim"], "fq"=>["{!terms f=id}82ab5232-40de-455a-b412-293701686a94,580821a1-a9e1-
4e9c-9ba4-6df9df59f8e5,05d6838b-a3d6-4c94-8862-b71eab23f23a,a21e1e2c-2a43-4263-b103-be6064c4e7fd,69aca7c7-ca97-4dfb-8d62-e0350099f608,73bfe74b-645b-4346-94e1-6680b8043224,
d6560769-b02b-4b5d-b746-53a85f1237b7,567a20ed-e1e2-4e21-a380-43a4f4f0e16e,9ae37fdf-e824-4879-9c4a-4f73f2f66292,7bb8faf0-dbcb-4d76-8604-58cd71165d83,6451ce75-a1f7-498f-9283
...many more UUIDs listed...
I, [2024-08-27T17:50:53.997283 #1]  INFO -- : [aef3333e58ccd7c1a9c6e917f6c7c539]   Rendered hyrax/dashboard/collections/_collection_title.html.erb (183.1ms)
I, [2024-08-27T17:50:54.006506 #1]  INFO -- : [aef3333e58ccd7c1a9c6e917f6c7c539]   Rendered /usr/local/bundle/bundler/gems/hyrax-285982850cd9/app/views/hyrax/dashboard/col
lections/show.html.erb within layouts/hyrax/dashboard (193.2ms)
E, [2024-08-27T17:50:54.006840 #1] ERROR -- : [aef3333e58ccd7c1a9c6e917f6c7c539] RSolr::Error::Http - 414 Request-URI Too Long
I, [2024-08-27T17:50:54.007240 #1]  INFO -- : [aef3333e58ccd7c1a9c6e917f6c7c539] Redirected to https://pittir.hykucommons.org/?locale=en
I, [2024-08-27T17:50:54.007442 #1]  INFO -- : [aef3333e58ccd7c1a9c6e917f6c7c539] Completed 302 Found in 471ms (ActiveRecord: 46.5ms)
```

</details>

**Comment by bkiahstroud** [comment]
Follow up ticket created: 

- #1051
