### ISSUE TITLE
Embed PDF viewer

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/palni-palci#125]
# Summary
Implement pdf.js viewer: https://mozilla.github.io/pdf.js/

An embedded PDF viewer is an essential improvement for the implementation and use of Hyku by both our current and potential user base. They would like to have the option to use IIIF Print or the embedded PDF for PDF items through feature flippers. 

# Acceptance Criteria
- [x] https://mozilla.github.io/pdf.js/ is an embedded PDF viewer
- [x] Indocument search is set up
- [x] Near instantaneous file loading
- [x] Configuration option to display full PDF in vertical format
- [x] Full page display at 100% scale
- [x] Single page display with “next” and “previous” buttons for readers to move between pages
- [x] Ability for readers to jump to indicated pages
- [x] Select and cut options for text
- [x] Feature flipper for embedded PDF is available for PDF items
- [x] Feature flipper for IIIF Print is available for PDF items
- [x] Instructions that enforce only one feature flipper to be enabled are displayed with the above feature flippers

# Screenshots or Video
Example of non-cached pdf loading in JSTOR:

![Image](https://user-images.githubusercontent.com/29311858/200966679-49b7ae44-3e55-4bca-a87c-17a4b0489704.png)

Example of vertical format:

![Image](https://user-images.githubusercontent.com/29311858/200966692-26007532-2ec2-4188-aab5-90ffbadf2308.png)

# Testing Instructions
- Create a work with a PDF attached to it
- Default Theme
  - [ ] Indocument search is set up
  - [ ] Near instantaneous file loading
  - [ ] Configuration option to display full PDF in vertical format
  - [ ] Full page display at 100% scale
  - [ ] Single page display with “next” and “previous” buttons for readers to move between pages
  - [ ] Ability for readers to jump to indicated pages
  - [ ] Select and cut options for text
  - [ ] Feature flipper for embedded PDF is available for PDF items
  - [ ] Feature flipper for IIIF Print is available for PDF items
  - [ ] Instructions that enforce only one feature flipper to be enabled are displayed with the above feature flippers
- Cultural Theme
  - [ ] Indocument search is set up
  - [ ] Near instantaneous file loading
  - [ ] Configuration option to display full PDF in vertical format
  - [ ] Full page display at 100% scale
  - [ ] Single page display with “next” and “previous” buttons for readers to move between pages
  - [ ] Ability for readers to jump to indicated pages
  - [ ] Select and cut options for text
  - [ ] Feature flipper for embedded PDF is available for PDF items
  - [ ] Feature flipper for IIIF Print is available for PDF items
  - [ ] Instructions that enforce only one feature flipper to be enabled are displayed with the above feature flippers
- Scholarly Theme
  - [ ] Indocument search is set up
  - [ ] Near instantaneous file loading
  - [ ] Configuration option to display full PDF in vertical format
  - [ ] Full page display at 100% scale
  - [ ] Single page display with “next” and “previous” buttons for readers to move between pages
  - [ ] Ability for readers to jump to indicated pages
  - [ ] Select and cut options for text
  - [ ] Feature flipper for embedded PDF is available for PDF items
  - [ ] Feature flipper for IIIF Print is available for PDF items
  - [ ] Instructions that enforce only one feature flipper to be enabled are displayed with the above feature flippers
- ReShare Theme
  - [ ] Indocument search is set up
  - [ ] Near instantaneous file loading
  - [ ] Configuration option to display full PDF in vertical format
  - [ ] Full page display at 100% scale
  - [ ] Single page display with “next” and “previous” buttons for readers to move between pages
  - [ ] Ability for readers to jump to indicated pages
  - [ ] Select and cut options for text
  - [ ] Feature flipper for embedded PDF is available for PDF items
  - [ ] Feature flipper for IIIF Print is available for PDF items
  - [ ] Instructions that enforce only one feature flipper to be enabled are displayed with the above feature flippers

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by DiemBTran** [comment]
Linked items:

Relates to:

- Epic: Backlog Tickets

**Comment by DiemBTran** [comment]
Amanda - Oct 2020:

---

also make it able to turn off and on

**Comment by ndroark** [comment]
Here is a Hyrax repo with pdf.js installed https://ldr.lafayette.edu/concern/publications/9019s417m

**Comment by kirkkwang** [comment]
useful reference: https://github.com/LafayetteCollegeLibraries/spot/pull/14

**Comment by jillpe** [comment]
SoftServ QA: Pass!

[PDF Link](https://dev.commons-archive.org/concern/generic_works/47a56d40-58f7-4de1-94bd-769f5f2c67ea?locale=en)

<details><summary>Default Theme ✅ </summary>


![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/5892b01b-f9a2-4d04-8f8e-0b3ec0a19b6c)


</details

<details><summary>Scholarly ✅ </summary>
![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/077c27e5-5268-4c44-9b10-8bbba8e7197c)

</details

<details><summary>Culture ❌ </summary>
Viewer is contained to left side of screen

![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/6565edf0-2278-4775-95e3-f796bafa5703)


</details

<details><summary>ReShare ❌ </summary>
The metadata is overlapping the viewer

![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/5a20eb73-72a8-4b32-9a7e-d22c867ddedd)


</details

**Comment by kirkkwang** [comment]
ReShare will not be using PDF.js so no need to test with that theme.


Cultural theme viewer fixed (download button will be fixed in a separate ticket)
![Image](https://github.com/scientist-softserv/palni-palci/assets/19597776/6da82309-bf39-4aa1-b850-59022acffa11)
