### ISSUE TITLE
Add appearance option to update favicon

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/palni-palci#149]
# Summary
Pals would like to give their tenants the option for a favicon icon. This work was done for BL: the option is in Setting -> Appearance.

Related BL ticket: https://gitlab.com/notch8/britishlibrary/-/issues/90

# Acceptance Criteria

- [ ] Favicon icon option for each tenant is in place

# Screenshots or Video

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by DiemBTran** [comment]
Linked items:

- Epic: Backlog Tickets

**Comment by labradford** [comment]
`

[2022-11-30T20:37:24.559339 #1] INFO -- : [b1593af86e553ce31e441418ca9d14c0] Sending event e14b5692b63b4b068cd64aab854b5c2c to Sentry
--
Wed, Nov 30 2022 12:37:24 pm | F, [2022-11-30T20:37:24.681273 #1] FATAL -- : [b1593af86e553ce31e441418ca9d14c0]
Wed, Nov 30 2022 12:37:24 pm | F, [2022-11-30T20:37:24.681541 #1] FATAL -- : [b1593af86e553ce31e441418ca9d14c0] NoMethodError (undefined method `favicon_will_change!' for #<Site:0x00007f7ada37b930>
Wed, Nov 30 2022 12:37:24 pm | Did you mean? favicon_cache):
Wed, Nov 30 2022 12:37:24 pm | F, [2022-11-30T20:37:24.684820 #1] FATAL -- : [b1593af86e553ce31e441418ca9d14c0]
Wed, Nov 30 2022 12:37:24 pm | F, [2022-11-30T20:37:24.685159 #1] FATAL -- : [b1593af86e553ce31e441418ca9d14c0] app/forms/hyrax/forms/admin/appearance.rb:355:in `update!'
Wed, Nov 30 2022 12:37:24 pm | [b1593af86e553ce31e441418ca9d14c0] app/controllers/hyrax/admin/appearances_controller.rb:28:in `update'

`

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screen recording.

tested on:
- https://qa-13.commons-archive.org/admin/appearance?locale=en#favicon
- **note:** favicons are heavily cached, so clicking `Remove favicon` may *seem* to not work at first glance. If you view the same tenant again on a different browser, the favicon will actually be removed.

<details><summary>Favicons can be selected, saved, and replaced. The changes are reflected across all pages of the tenant.</summary>

https://user-images.githubusercontent.com/29311858/207934332-3d0b232a-71cb-498d-b262-25fbaafcd8d7.mp4</details>

**Comment by labradford** [comment]
contribute back: https://github.com/samvera/hyku/pull/1868
