### ISSUE TITLE
Style a 500 error pg

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/palni-palci#173]
# Summary
Style a static 500.html page and include the everything in the acceptance criteria below.

# Acceptance Criteria

Client approval of video/screenshot mockup: https://assaydepot.slack.com/archives/C0313NKC08L/p1669755830521409

- [x] Adds a styled static html 500 error page
- [x] Has the Hyku commons logo
- [x] Adds the error message -- "500" && "An unexpected error occurred." 
- [x] Adds a call to action with email us link (email: help@hykuforconsortia.org) -- "Please [email us](mailto:help@hykuforconsortia.org) if you continue to experience this error."

# Screenshots or Video

Small video demo to see simple animation: https://share.getcloudapp.com/nOu1plmg

Screenshot:
![Image](https://user-images.githubusercontent.com/63515648/205210104-285f4efa-11f7-4236-953a-594519328082.png)

# Testing Instructions

Navigate to the website you are testing on and add /500.html and make sure the 500 page on demo and when it's time production, to look like the screenshot added above.

Url when testing demo: https://commons-archive.org/500.html

Url when testing production: https://hykucommons.org/500.html

Make sure that we satisfy each of the acceptance criteria above.

**Comment by DiemBTran** [comment]
Linked items:

Relates to:

- Epic: Backlog Tickets
