### ISSUE TITLE
Batch editing Works throws error

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/palni-palci#185]
# Summary

In Dashboard Works index views, selecting more than one checkbox next to works and clicking the "Edit Selected" button throws a 500 error. 

Error in Sentry: https://sentry.notch8.com/sentry/pals/issues/52030/ 

Current Hyrax version: 2.9.0 

# Screenshots 

Selecting Works to batch edit

![Image](https://user-images.githubusercontent.com/29311858/200966828-72f414b0-9d25-46f4-9292-ca0758710605.png)

Resulting error page

![Image](https://user-images.githubusercontent.com/29311858/200966858-2b80bd46-62f2-444c-a393-63fec829fca7.png)

Expected behavior (Nurax)

![Image](https://user-images.githubusercontent.com/29311858/200966888-c66346f1-e2b6-49f3-b9b1-ec1c13d593dc.png)

# Implementation Suggestions 

Investigate whether or not this bug comes from this project or from Hyrax v2.9.0. Is the fix as simple as upgrading Hyrax? Do this before working on a custom fix

**Comment by DiemBTran** [comment]
Linked items:

Relates to:

- Epic: Backlog Tickets

**Comment by DiemBTran** [comment]
Jill Oct 2022:

---

Problem actively occurring in Adventist. Please let Adventist team know when a solution is discovered.

**Comment by bkiahstroud** [comment]
Team Sprint meeting discussion: 

- Needs investigation (0.5 days) 
  - Does Hyku override that action? If so, what's different?
  - Is this a known bug in Hyrax 3.x?

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screen recording.

tested on:
- https://qa-12.commons-archive.org/concern/images/45fcb64b-a4d1-4cb2-8939-07fc84be6e72?locale=en
- https://qa-12.commons-archive.org/concern/images/b0218615-fe9e-415b-9d62-8331e591ea88?locale=en
- https://qa-12.commons-archive.org/concern/images/0ad4b1e9-1a37-4a91-b3ef-16b5c1370601?locale=en

<details><summary> Users can batch edit works

</summary>


https://user-images.githubusercontent.com/29311858/204939765-6ebce58f-0491-4782-b7f0-8106b723c23e.mp4

</details>

**Comment by ndroark** [comment]
I get an error trying to edit any combination of the works on this page, including just editing a single work through the checkbox system https://nic2.commons-archive.org/dashboard/my/works?locale=en

Perhaps rela

**Comment by labradford** [comment]
@ndroark can you try this again? I'm not running into the same issue and I think it might have been due to the server issues we were having yesterday.

**Comment by ndroark** [comment]
@labradford Still seeing the errors in nic2.commons-archive and [othowinger](https://othowingerdemo.hykucommons.org/dashboard/my/works?locale=en).

**Comment by labradford** [comment]
Ok, I can now reproduce the issue and the error lies in the `app/views/records/edit/_default.html.erb`

**Comment by labradford** [comment]
```

Completed 500 Internal Server Error in 650ms (ActiveRecord: 40.4ms)
--
Mon, Dec 5 2022 9:30:08 am | D, [2022-12-05T17:30:08.516560 #1] DEBUG -- : [c72a0cc0342254eab1899f5e9b80fd01] Account Load (0.1ms) SELECT "public"."accounts".* FROM "public"."accounts" WHERE "public"."accounts"."tenant" = $1 LIMIT $2 [["tenant", "public"], ["LIMIT", 1]]
Mon, Dec 5 2022 9:30:08 am | I, [2022-12-05T17:30:08.619018 #1] INFO -- : [c72a0cc0342254eab1899f5e9b80fd01] Sending event c9277d7d87d040c1aa0b9650227ba6e6 to Sentry
Mon, Dec 5 2022 9:30:08 am | F, [2022-12-05T17:30:08.786299 #1] FATAL -- : [c72a0cc0342254eab1899f5e9b80fd01]
Mon, Dec 5 2022 9:30:08 am | F, [2022-12-05T17:30:08.786373 #1] FATAL -- : [c72a0cc0342254eab1899f5e9b80fd01] ActionView::Template::Error (undefined local variable or method `curation_concern' for #<#<Class:0x00007f6bb36cf5b8>:0x00007f6ba55201f8>
Mon, Dec 5 2022 9:30:08 am | Did you mean? curation_concern_page_title):
Mon, Dec 5 2022 9:30:08 am | F, [2022-12-05T17:30:08.786496 #1] FATAL -- : [c72a0cc0342254eab1899f5e9b80fd01] 1: <%# Copied from Hyrax to support dynamic labels and hints for custom worktypes %>
Mon, Dec 5 2022 9:30:08 am | [c72a0cc0342254eab1899f5e9b80fd01] 2:
Mon, Dec 5 2022 9:30:08 am | [c72a0cc0342254eab1899f5e9b80fd01] 3: <%# Avoid NoMethod error when rendering partial in Collection form %>
Mon, Dec 5 2022 9:30:08 am | [c72a0cc0342254eab1899f5e9b80fd01] 4: <% record = @collection \|\| curation_concern %>
Mon, Dec 5 2022 9:30:08 am | [c72a0cc0342254eab1899f5e9b80fd01] 5: <% if f.object.multiple? key %>
Mon, Dec 5 2022 9:30:08 am | [c72a0cc0342254eab1899f5e9b80fd01] 6: <%= f.input key,
Mon, Dec 5 2022 9:30:08 am | [c72a0cc0342254eab1899f5e9b80fd01] 7: as: :multi_value,
Mon, Dec 5 2022 9:30:08 am | F, [2022-12-05T17:30:08.786520 #1] FATAL -- : [c72a0cc0342254eab1899f5e9b80fd01]
Mon, Dec 5 2022 9:30:08 am | F, [2022-12-05T17:30:08.786554 #1] FATAL -- : [c72a0cc0342254eab1899f5e9b80fd01] app/views/records/edit_fields/_default.html.erb:4:in `_app_views_records_edit_fields__default_html_erb__151063061611375272_621920'
Mon, Dec 5 2022 9:30:08 am | [c72a0cc0342254eab1899f5e9b80fd01] app/middleware/no_cache_middleware.rb:13:in `call'
Mon, Dec 5 2022 9:30:08 am | 10.0.4.185, 10.0.6.252 - - [05/Dec/2022:17:30:08 +0000] "GET /500?batch_document_ids%5B%5D=a081fca8-9a7e-42e1-9752-f41ce56170dd HTTP/1.0" 500 1477 0.933

```

**Comment by labradford** [comment]
Not able to reproduce on nic2.commons-archive.org

**Comment by ndroark** [comment]
Maybe it's something specific to my superadmin account? This is after all cache-clearing 

https://user-images.githubusercontent.com/117871943/205731175-1e399adc-b22b-4f95-88c8-c8f1760485bf.webm

**Comment by ndroark** [comment]
I set up another account with edit permissions and didn't encounter the error, so there is something about the ndroark@anderson.edu superadmin that is causing it.

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot and recording.

tested on:
- https://nic2.commons-archive.org/concern/generic_works/8f6154a9-d761-4688-8a88-f00341688c0c?locale=en
- https://nic2.commons-archive.org/concern/generic_works/481ff5c0-2ddf-4598-a7ce-547e8c70f189?locale=en
- https://nic2.commons-archive.org/concern/generic_works/fc0748f1-4b7c-47ad-9120-c87fddba9c28?locale=en

<details><summary> Works can be edited by batch without error

</summary>

https://user-images.githubusercontent.com/29311858/206029495-ff68dd81-5d87-4951-9cb9-1f6fd104da8f.mp4



</details>

**Comment by labradford** [comment]
This was a palni/palci specific error and does not need to be contributed back to Hyku or Hyrax
