### ISSUE TITLE
[3] Thumbnails inconsistently showing on various tenants

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/palni-palci#199]
# Summary
I'm experiencing an issue on multiple tenants where work and collection thumbnails are randomly broken. Which ones are broken change with each refresh of the page. For example:

![Image](https://user-images.githubusercontent.com/29311858/200943404-e601655f-303f-4a44-8fa2-5c3ea9c85c9f.png)

After Refresh: 

![Image](https://user-images.githubusercontent.com/29311858/200943431-7fa15795-b5d0-43f8-a69a-bc08e7845704.png)

# Acceptance Criteria
- [ ] Thumbnails should be showing consistently and should stay on refresh

# Testing
Go to https://au-archives.hykucommons.org/ and check that all the thumbnails are showing.  Refresh a couple times and make sure they still work.  Check another tenant on production.  

# Notes: 
From April: 
After navigating to the production tenant: https://au-archives.hykucommons.org/ I refresh my page several times and notice that thumbnails are inconsistently not being generated and they do change on refresh, I cannot find a pattern. I then inspect the page and see that those images are receiving a 500 code.

I navigated to Sentry and saw error: https://sentry.notch8.com/sentry/pals/issues/138642/ The value for :adapter was not found in the blacklight.yml config.

I was able to see this accross a couple of tenant: https://sentry.notch8.com/sentry/pals/issues/138645/

I am wondering if it is a SOLR_URL issue. In blacklight.yml the SOLR_URL or a solr url with the blacklight core attached?

**Comment by DiemBTran** [comment]
Lea Ann - March 2022:

---

Let's retest again since we have done server upgrades.
