### ISSUE TITLE
Fix triple thumbnail render error

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/palni-palci#266]
# Summary
it does this weird thing where the thumbnail is the front page of the document but three times... it doesn't always happen to every PDF that goes in, but has happened to two recently - is there a way i can amend this to stop it happening?!

This was happening in:

Bl - https://gitlab.com/notch8/britishlibrary/-/issues/218

Cal State - https://github.com/csuscholarworks/scholarworks/issues/52

https://github.com/csuscholarworks/scholarworks/pull/61/commits

Samples of the triple thumbnail error in pals:
- https://pvcc.hykucommons.org/concern/generic_works/b42e99bf-ff3e-42c1-a294-236408c52dbd?locale=en
- https://pvcc.hykucommons.org/concern/parent/bcd19300-c0e8-452e-8bb3-4d42732322f5/generic_works/9dba3348-f71b-40d6-81b6-0118f0cef456
- https://juniata.hykucommons.org/concern/generic_works/1431154a-a45e-4a32-adb7-119af457bce6?locale=en

# Acceptance Criteria

- [ ] There is only 1 thumbnail on the front page of the document

# Screenshots or Video

# Testing Instructions

# Notes
- This is believed to happen because of a mismatch in image magic versions and their underlying dependencies. Resolved in scholar works. Possibly solved in newer versions of hyrax. Checks scholar works variables for image magic's newest version of hyku. 

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by DiemBTran** [comment]
Linked items:

Relates to:

- Epic: Backlog Tickets

**Comment by labradford** [comment]
@ndroark I have completed re-generating the thumbnails for all the tenants that Rob marked as incomplete. Can you verify that I didn't miss any?

**Comment by ndroark** [comment]
I've tried clearing cookies and cache and am still seeing the issue on sma-ir-library.hykucommons.org

**Comment by labradford** [comment]
running more of the jobs today. I ran several yesterday morning but many errored due to the server issues we were experiencing.

**Comment by labradford** [comment]
All of the jobs have completed and I do not see any triple-thumbnails for sma-ir-library tenant.
