### ISSUE TITLE
Using "back" browser function on IR theme expands resource types endlessly

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/palni-palci#277]
## Summary
From user: "Whenever I go from the main page of Dickinson's repository to a particular work and then use the back button in my browser (or more specifically, right click-->Back) to return to the main page, the icons near the top for book, conference proceeding, journal, etc, seem to multiply. And then if you navigate from the home page to another publication and use the back button/command in the browser to return to the homepage again, even MORE duplicate icons appear. I'm attaching a screenshot of this. I've replicated the error a few times. Refreshing the home page clears the error and returns it to the normal appearance. This also doesn't happen if you use the hyperlinks near the top to navigate. (For reference, I'm using Chrome.)"

Have confirmed on Firefox as well.

## Accepted Criteria
- [ ] As a user I can navigate from the main page of a repository to a work, then use the back button in my browser to navigate back to the main page without duplicate icons appearing

# Testing Instructions
1. Switch theme to Institutional Repository
2. Add works with various resource types until the home page's the icons have < and > arrows. 

![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/ba80cbe7-2a8a-4784-8fa5-64d56cae381f)

3. click on a work under recent uploads. Click the back button.
4. The row of icons should look the same and not duplicate.

## Notes
 
See demo in PR: - https://github.com/scientist-softserv/palni-palci/pull/851

**Comment by DiemBTran** [comment]
Nic - July 2022

---

From user: "Whenever I go from the main page of Dickinson's repository to a particular work and then use the back button in my browser (or more specifically, right click-->Back) to return to the main page, the icons near the top for book, conference proceeding, journal, etc, seem to multiply.  And then if you navigate from the home page to another publication and use the back button/command in the browser to return to the homepage again, even MORE duplicate icons appear.  I'm attaching a screenshot of this.  I've replicated the error a few times.  Refreshing the home page clears the error and returns it to the normal appearance.  This also doesn't happen if you use the hyperlinks near the top to navigate. (For reference, I'm using Chrome.)"

Have confirmed on Firefox as well. 



![Image](https://user-images.githubusercontent.com/29311858/200936624-0062f2df-e6e7-41c0-815c-3a22edc79c6a.png)

**Comment by ShanaLMoore** [comment]
# QA RESULTS:
