### ISSUE TITLE
Work new/edit form sharing tab not working

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/palni-palci#283]
## Summary

The work form Sharing tab doesn't work when depositing into an Admin Set that uses a mediated deposit workflow. The tab is hidden for non-managers (mostly admins), but not for managers. The tab should be hidden for all users regardless of permission level since it doesn't work. 

## Acceptance Criteria 

- [ ] The Sharing tab on the work form is hidden when the work's admin set uses a mediated deposit workflow 

## Testing Instructions 

1. Login as an admin 
2. Navigate to Dashboard > Collections > Add New Collection 
3. Select Admin Set as the collection type 
4. Fill out the required fields and click Save 
5. Edit the admin set. On the Workflow tab, ensure either `One-step mediated deposit workflow` or `Custom mediated deposit workflow for Hyku Commons` is selected. Save if necessary 
6. Navigate to Dashboard > Works > Add New Work 
7. Fill out required fields. On the relationships tab, select the admin set that was created in Step 4 
8. Validate the Sharing tab is not rendered 
9. Validate that the Sharing tab does render when selecting an admin set that uses the `Default workflow` 

<details><summary>Archived, old description</summary>

# Summary

There are several bugs on the Work new/edit form's `Sharing` tab. These bugs were found while QAing the SPP (diem.staging-palni-palci.notch8.cloud) Hyku Upgrade site. Bugs and broken behavior that need to be fixed will be listed as `Acceptance Criteria` below.

tested on:
- batch work: https://diem.staging-palni-palci.notch8.cloud/concern/generic_works/b617d48f-c78a-481f-905d-15a595ee6ced/edit?locale=en#share
- regular work: https://diem.staging-palni-palci.notch8.cloud/concern/images/9e2fd4a2-5902-4dae-be3a-a664280282f7/edit?locale=en#share

# Acceptance Criteria

### 1. I can see a list of all the groups / users I am currently sharing my works with, along with their respective access levels 
---
**expected behavior:**
- [ ] I can see a list of all the groups / users I am currently sharing my works with, along with their respective access levels 

**actual behavior:**
- Groups and users can be added, but they are not actually saved after the `Save` button is clicked

# Testing Instructions
As an admin user:
- [x] Login as an admin/superadmin onto an SPP tenant
- [x] Navigate to `Dashboard` > `Works` and edit a `private` work that the admin/superadmin owns
- [x] Navigate to the `Sharing` tab of the edit form
- [x] verify that the user or group you added is actually saved after clicking `Save`
- [ ] verify that you can `Remove` a group or user successfully
- [ ] **note:** When adding a user, add the non-admin user you want to test these abilities on. Be sure that this non-admin user has no roles attached to them by navigating to `Dashboard` > `Manage Users`.
- [ ] **note:** When adding a group, make sure that the group has no roles attached and that you add a non-admin user with no roles. At `Dashboard` > `Manage Users`, you should see that the user is in no other groups than `Registered Users` and the **one** group you just added them to to test this ability.

As that non-admin user:
- [ ] Navigate to that `private` work and attempt the managers/depositors/viewer role you were given.

</details>

**Comment by DiemBTran** [comment]
Related MRs:

- [i576 Sharing tab errors](https://gitlab.com/notch8/palni-palci/-/merge_requests/628)
!628
- [i577 Work around bug in Hyrax that doesn't allow admins to update a Work's Sharing](https://gitlab.com/notch8/palni-palci/-/merge_requests/631)
!631

**Comment by DiemBTran** [comment]
Kiah Nov 2022:

---

Failing on N8 staging with the following error: 

```sh
ActionController::ParameterMissing (param is missing or the value is empty: permissions_attributes):

app/controllers/concerns/hyrax/works_controller_behavior_decorator.rb:33:in `attributes_for_actor'
app/controllers/concerns/hyrax/works_controller_behavior.rb:244:in `actor_environment'
app/controllers/concerns/hyrax/works_controller_behavior.rb:70:in `create'
app/controllers/concerns/hyrax/works_controller_behavior.rb:499:in `inject_show_theme_views' 
```

Pushing back to ready for development.

**Comment by DiemBTran** [comment]
**Needs further review:** See attached screen recording

tested on:
- https://qa-9.commons-archive.org/concern/generic_works/d74db0a5-d26d-4eb2-bca9-cb03aae75d0d?locale=en

Acceptance criteria:
- [x]  Login as an admin/superadmin onto an SPP tenant
- [x]  Navigate to Dashboard > Works and edit a private work that the admin/superadmin owns
- [x]  Navigate to the Sharing tab of the edit form
- [x]  verify that the user or group you added is actually saved after clicking Save
- [ ]  verify that you can Remove a group or user successfully
     - [ ] bug: removing a group or user leads to a `We're sorry, but something went wrong.`
     - [x] correct: removing a group or user removes them from the `Work new/edit form sharing tab` list
     - [ ] bug: although they are removed from the list, they still retain the given permissions
https://user-images.githubusercontent.com/29311858/201738620-d80d42ba-cb4e-450c-92ba-2bcaf6c8182e.mp4

**Comment by bkiahstroud** [comment]
Needs further testing, but this may be related to files specifically; I tested this on a work that didn't have any files attached to it and did not see the bug. Also, the error is happening in the `CreateWithFilesActor#update` method.

**Comment by bkiahstroud** [comment]
Related PR: https://github.com/scientist-softserv/palni-palci/pull/316

**Comment by DiemBTran** [comment]
**Needs further review:**

tested on: https://qa-9.commons-archive.org/dashboard/my/works?locale=en

I’m still seeing the same broken behavior on:

1. old work, old admin set ([link to work](https://qa-9.commons-archive.org/concern/images/eb5dc003-dd6d-4842-9624-bd4107cd2db3?locale=en))
2. new work, old admin set ([link to work](https://qa-9.commons-archive.org/concern/images/725ff7f6-9acd-4ebd-8db7-296763dca056?locale=en))
3. new work, new admin set ([work 1](https://qa-9.commons-archive.org/concern/images/507bf9a5-d06d-49b1-8334-aa5cb58ecd94?locale=en), [2](https://qa-9.commons-archive.org/concern/generic_works/bfec502b-d236-4853-b156-9415c8c57437?locale=en))


<details><summary>This screenshot shows all 4 works I tested with. You can see the time stamps in the works’ titles (YYYYMMDDHHMM), so you can see that I gave works up to 30 minutes to refresh itself

</summary>

![Works 2022-11-30 at 1 25 42 PM](https://user-images.githubusercontent.com/29311858/204922097-98482873-0abe-4f00-992d-0ff0f01b67c3.jpg)
</details>

<details><summary> This screen recording shows a test with a new work, new admin set

</summary>

https://user-images.githubusercontent.com/29311858/204922314-3ee75544-bda4-4863-9b45-b624a392ce4f.mp4

</details>

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screen recording.

tested on:
- https://qa-13.commons-archive.org/concern/images/new?locale=en#relationships
- https://qa-13.commons-archive.org/concern/images/a3eb7d1b-421e-4083-9157-a07d511f8fdc?locale=en

<details><summary>If a work is added to an admin set with non-mediated deposit, the sharing tab appears. If it is added to an admin set with mediated deposit (e.g. the Default Admin set out of the box), the sharing tab disappears.</summary>

https://user-images.githubusercontent.com/29311858/206328510-4250a2ea-0e79-4f9d-aa3f-321c0cdeaa73.mp4
</details>
