### ISSUE TITLE
Disabling Featured Works in Neutral Theme disables Share your Work Button

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/palni-palci#285]

**Comment by DiemBTran** [comment]
Related MRs:

---

- [move share work button outside of featured works partial](https://gitlab.com/notch8/palni-palci/-/merge_requests/627)
!627

**Comment by DiemBTran** [comment]
Lea Ann - Oct 2022:

---

Fixing on the Hyku upgrade branch

**Comment by DiemBTran** [comment]
Diem - Oct 2022:

----

**This passes Notch8 QA:** See attached screen recording.

tested on:
- https://diem.staging-palni-palci.notch8.cloud/?locale=en

Neutral theme: Disabling Featured Works no longer disables Share your Work Button


https://user-images.githubusercontent.com/29311858/200949522-7af961c1-7e65-48f9-99bf-e89118c8b32c.mp4

**Comment by labradford** [comment]
contributed back: https://github.com/samvera/hyku/pull/1866
