### ISSUE TITLE
Create mockups of 500 error page

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/palni-palci#287]
# Summary
They want to style a 500 error page, so we need to make mockups to present to them.

# Acceptance Criteria

- [ ] Mockups have been created for 500 error page

# Notes
Ideas:
- https://uicookies.com/500-error-page-templates/
- https://iamrohit.in/500-error-page-html-templates/

**Comment by DiemBTran** [comment]
Jill Peterson - Oct 2022:

---

Ideas:
https://docs.google.com/document/d/1FKoJpzVwv78NHNwkmufsvuMDXhQiUgdxj_ZWvP_a300/edit

**Comment by labradford** [comment]
closing as client approved design in slack https://assaydepot.slack.com/archives/C0313NKC08L/p1669755830521409
