### ISSUE TITLE
Collection-level searching not working

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/palni-palci#288]
When viewing a collection page, the central search bar does not return results for the content or metadata of works or sub-collections, only the titles. Optimally, this search would function just as the main search bar for each tenant does, searching the text of PDFs, and all metadata fields, but only within the collection.

**Comment by DiemBTran** [comment]
tested on:
- tested on work and sub-collection metadata
- https://dev.commons-archive.org/collections/05933519-23d0-4876-a0e8-31680e54263e?utf8=%E2%9C%93&cq=miller&sort=&locale=en
- https://dev.commons-archive.org/collections/03390bb4-5e00-4000-b97f-514a40701712?utf8=%E2%9C%93&cq=&sort=&locale=en

Metadata fields that come up in search:
- [x] Description
- [x] Creator
- [x] Keyword
- [x] Date created

Metadata fields that do not come up in search:
- [ ] Subject
- [ ] Language
- [ ] Keyword
- [ ] Date created
- [ ] Resource type
- [ ] text content of PDFs

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screen recording.


tested on:
- https://dev.commons-archive.org/collections/03390bb4-5e00-4000-b97f-514a40701712?utf8=%E2%9C%93&cq=&sort=&locale=en
- 
Metadata fields that come up in search:
- [x] Description
- [x] Creator
- [x] Keyword
- [x] Date created
- [x] Subject
- [x] Language
- [x] Keyword
- [x] Resource type
- [x] text content of PDFs

<details><summary> Works' metadata, OCR in works, and Collections' metadata are now searchable from the dashboard collection show page and public collection show page</summary>


https://user-images.githubusercontent.com/29311858/207952225-a66d0ba9-51a3-43fb-a3c3-857df98088d2.mp4
</details>

**Comment by labradford** [comment]
contribute back PR https://github.com/samvera/hyku/pull/1876
