### ISSUE TITLE
Homepage: Fix spacing for directory images

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/palni-palci#289]
# Summary 
From Nic's [Upgrade Observations](https://docs.google.com/document/d/1Orb292eB2JQbEipBnGtWdU6Qkp9-dT6JtrspIIW44MY/edit#) document:

`The grid for directory images should have blank space between vertical rows at least matching the space between horizontal ones. Possibly this space should be a tiny bit bigger in general?`

# Acceptance Criteria

- [ ] Communicate with client for spacing design specs
- [ ] Implement said spacing design specs

# Screenshots

## Nic's screenshot from commons-archive.org on 2022-11-08:
There was less spacing before

![Image](https://user-images.githubusercontent.com/29311858/201191470-9c0ebc78-0674-412b-9f00-9410449841bc.png)

## Diem's screenshot from commons-archive.org on 2022-11-10:
There is more spacing now. Is this adequate?

![Image](https://user-images.githubusercontent.com/29311858/201191652-2f3f0086-a32e-4437-98c2-ef06b993c7de.png)

# Notes

**Comment by ndroark** [comment]
Now that spacing is added, I notice that when you hover over a thumbnail, a dash appears in the space between it and the following thumbnail. 
![dash](https://user-images.githubusercontent.com/117871943/201384185-606a6395-fcd8-45dc-8e1f-ee916722d216.png)
