### ISSUE TITLE
Homepage: Fix directory image heights

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/palni-palci#290]
# Summary 
From Nic's [Upgrade Observations](https://docs.google.com/document/d/1Orb292eB2JQbEipBnGtWdU6Qkp9-dT6JtrspIIW44MY/edit#) document:

`I turned nic2.commons-archive.org to public and uploaded the AMBS logo from hykucommons.org, and produced this: Presumably this is a result of the short-and-wide logo scaling up to minimum height? Maybe this just means we institute some ground rules for directory images?`

# Acceptance Criteria

- [ ] Communicate with client for best practice for short-and-wide logos:
     - [ ] do we implement ground rules for directory images?
     - [ ] Amanda H's suggestion: fixed width?
     - [ ] or another approach?
- [ ] Implement said approach

# Screenshots
## Diem's screenshot from commons-archive.org on 2022-11-10:
`Dickinson` and `AMBS` logo are short-and-wide, so they stretch out and take up a lot of space.

![Image](https://user-images.githubusercontent.com/29311858/201191652-2f3f0086-a32e-4437-98c2-ef06b993c7de.png)

# Notes

**Comment by labradford** [comment]
Add help text on image size. Should be no wider than 2x height

**Comment by ndroark** [comment]
Typo in message, says "that the height" instead of "than the height"

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

tested on:
- https://qa-12.commons-archive.org/admin/appearance?locale=en#directory_image
- https://commons-archive.org/?locale=en

testing:
- [x] Hint text says `The directory image should use an image (JPG, GIF or PNG). The width of the image should be no wider than 2x the height.`
- [x] Directory image and its alt text are saved

![Show Appearance Hyku Commons 2022-11-28 at 11 08 09 AM](https://user-images.githubusercontent.com/29311858/204361914-f70ab40a-9c30-4833-baaf-8537eb279fe7.jpg)
![Hyku Commons 2022-11-28 at 11 14 56 AM](https://user-images.githubusercontent.com/29311858/204361932-e2c174a2-ac1f-453e-85eb-31a96b9514df.jpg)
