### ISSUE TITLE
Homepage: Alphabetize partner repositories

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/palni-palci#291]
# Summary 
From Nic's [Upgrade Observations](https://docs.google.com/document/d/1Orb292eB2JQbEipBnGtWdU6Qkp9-dT6JtrspIIW44MY/edit#) document:

`[The directory images] also doesn’t follow alphabetization`

# Acceptance Criteria

- [ ] Alphabetize partner repositories

# Screenshots

### `nic3.commons-archive.org` has the AMBS logo. It sits on top, even before `bloomsburg` and `butler`

![Image](https://user-images.githubusercontent.com/29311858/201194452-bc0730eb-34d4-4591-a97e-579a74b60140.png)

### `nic3.commons-archive.org` is now in its correct spot. But now `nic2.commons-archive.org` has been added and is in the wrong spot

![Image](https://user-images.githubusercontent.com/29311858/201194887-58fa32c8-b8dd-49b0-853f-1fd5bf917fd9.png)

# Notes

**Comment by labradford** [comment]
the reason the nic tenants are sorting out of order is because the cname (url) is different than the name:
nic2 name = "2-10test", so it appears first

**Comment by labradford** [comment]
the "nic2" tenant has more than one cname, and it is sorting on the first one "2-10-test"
