### ISSUE TITLE
Work upload: Keyword field bugs

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/palni-palci#295]
# Summary 
From Nic's [Upgrade Observations](https://docs.google.com/document/d/1Orb292eB2JQbEipBnGtWdU6Qkp9-dT6JtrspIIW44MY/edit#) document:

`Keywords in existent works are deleted when the work edit page is opened. This also occurs without warning when an embargo is updated from the embargo management page and will create a work with no keyword.`

# Acceptance Criteria

- [ ] Existing `Keyword`s no longer disappear when accessing a `work edit form`
- [ ] Embargo edit form no longer creates works without keywords

# Screenshots

## 1. `Keywords` in existent works are deleted when the work edit page is opened.

https://user-images.githubusercontent.com/29311858/201234850-fea58e59-25f4-4328-95c6-f737ebee4518.mp4

## 2. This also occurs without warning when an embargo is updated from the embargo management page and will create a work with no keyword.

I was not able to replicate this. 

2022-11-11 Slack conversation with clients: https://assaydepot.slack.com/archives/C0313NKC08L/p1668177489828219?thread_ts=1668127438.488019&cid=C0313NKC08L

Nic: `So I've done a bit of testing to try to get a recording, and I can see why this can't be replicated now. The keyword being overwritten with a blank field only occurs on works created or last edited prior to the upgrade, so only works set to embargo prior to the upgrade will have the keyword deleted when updated through the Manage Embargoes tab. I'm not aware of any works set to embargo (or lease) prior to the upgrade that haven't been edited since, so I don't think we can replicate.`
Amanda H: `But there are embargoed works in production, right?`

# Notes

**Comment by labradford** [comment]
Need to research why keyword is removed when item is opened in edit mode

**Comment by labradford** [comment]
https://github.com/samvera/hyrax/issues/1505

**Comment by labradford** [comment]
https://github.com/samvera/hyrax/pull/3748

**Comment by labradford** [comment]
run `rake tenantize:task[hyrax:migrate:migrate_keyword_predicate]` after deploying to update the keyword field.

**Comment by ndroark** [comment]
As far as I can tell this is still occurring. Testing method: I edit a work that was uploaded prior to the upgrade, the keyword field appears blank and any keywords entered prior are missing/deleted.

**Comment by labradford** [comment]
which tenant are you looking at?

**Comment by ndroark** [comment]
I looked at two works in this tenant https://nic2.commons-archive.org/concern/generic_works/bcba8ea4-3819-4abb-a4bf-c98f47e82e31?locale=en

**Comment by labradford** [comment]
@ndroark can you test this again? I must have missed your tenant when I did the migration
