### ISSUE TITLE
Review Submissions tab under Tasks on the dashboard throws an error

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#334]
# Summary
In some tenants, the Review Submissions tab under Tasks on the dashboard throws an error. It is currently affecting some of their tenants' workflow.

Example https://marian.hykucommons.org/admin/workflows?locale=en

# Accepted Criteria
- [  ] Selecting "Review Submissions" from the Admin Dashboard will not cause an error. There must be a very large amount of items in this list for the error to occur.

**Comment by labradford** [comment]
https://sentry.io/organizations/scientist-inc/issues/3778440827/?project=6707374&query=is%3Aunresolved&referrer=issue-stream

**Comment by labradford** [comment]
In Hyrax: `app/services/hyrax/workflow/actionable_objects.rb`

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screen recording.

tested on:
- https://qa-13.commons-archive.org/admin/workflows?locale=en
- CSV used to import 200 works for testing: [200_works_no_source.csv](https://github.com/scientist-softserv/palni-palci/files/10179154/200_works_no_source.csv)

QA Notes:

1. I was able to steal a 200 work export from https://dev.commons-archive.org/exporters/93?locale=en, modify the CSV a bit, and import it into a new tenant at https://qa-13.commons-archive.org/importers/1. :white_check_mark:
2. 162/200 works were imported into an admin set that requires approval :white_check_mark:
3. The [Review Submissions](https://qa-13.commons-archive.org/admin/workflows?locale=en) tab did not break :white_check_mark:
4. However, something is wrong with the [Review Submissions](https://qa-13.commons-archive.org/admin/workflows?locale=en) page’s pagination-- it says Showing 1 to 10 of 10 🚧 and only shows 10 entries to review, not all 162 works
(0:05 in 2nd video below). This will be addressed in another ticket 

<details><summary>This video demonstrates that 100+ works were imported into an admin set that requires approval. The Review Submissions tab no longer breaks when a large number of works require approval</summary>

https://user-images.githubusercontent.com/29311858/206273075-4e4058c3-8e55-4ff9-8a2c-4806b154fc2a.mp4
</details>

<details><summary>This video demonstrates that the pagination on this page is broken, though, and only displays 10 works at a time. This will be addressed in another ticket</summary>


https://user-images.githubusercontent.com/29311858/206273301-5b4bf927-6e4b-4774-bef1-d8abae120969.mp4


</details>

**Comment by labradford** [comment]
To be addressed in Hyrax https://github.com/samvera/hyrax/issues/5926
