### ISSUE TITLE
Keywords are retained in the edit form, but are not displaying

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#335]
# Summary
In some works, the keywords are retained in the edit form, but are not displaying. 

Example https://ambs.hykucommons.org/concern/generic_works/26ed75be-e841-4341-a21e-40c680f5795e?locale=en

# Accepted Criteria:
- keyword appears on work show page

**Comment by labradford** [comment]
I re-saved the work and the issue resolved. 

I believe this was an anomaly with the data
https://ambs.hykucommons.org/concern/generic_works/26ed75be-e841-4341-a21e-40c680f5795e?locale=en
