### ISSUE TITLE
Approval ribbon whited out in au-archives.hykcommons.org

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#337]
# Summary 
Approval ribbon whited out in [au-archives.hykcommons.org](http://au-archives.hykucommons.org/). Can’t locate any color setting that affects this

![Image](https://user-images.githubusercontent.com/84697174/205747631-41633554-5746-4b46-8f6e-c46baaa62106.png)

# Accepted Criteria
- [ ]

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screen recording.

tested on:
- https://qa-13.commons-archive.org/concern/generic_works/f6196590-9749-4f59-87f1-d03debdcd9c1?locale=en

According to https://github.com/scientist-softserv/palni-palci/pull/341, the approval ribbon would white-out when a tenant selects the cultural repository theme. This has been fixed.

<details><summary> Cultural Repo Theme no longer hides approval ribbon</summary>

https://user-images.githubusercontent.com/29311858/206058122-f351ad2c-d1ff-4cb5-820c-7a68258bc4e8.mp4</details>
