### ISSUE TITLE
Enable Google Analytics

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/palni-palci#339]
# Summary

Pals is ready to tinker with Google Analytics.

NEW UA# `UA-251992018-1`

Tested on prod: https://qa.hykucommons.org/. Adding the code `UA-207005751-1` did not immediately enable Google Analytics. Instead, it broke the `Dashboard`,  `Dashboard` > `Collections Report`, and `Dashboard` > `Works Report`. We may need to check if the credentials made it into the code, first. 

# Screenshots or Videos

https://user-images.githubusercontent.com/29311858/205777355-cdfbbf7e-f3c5-4de0-9783-43470e2d477b.mp4

# Testing Instructions

- [ ] As a superadmin, navigate to a tenant's `Dashboard` > `Settings` > `Account` page
- [ ] Enter a Google Analytics code (e.g. `UA-251992018-1`) and save
- [ ] Navigate to  `Dashboard`,  `Dashboard` > `Collections Report`, and `Dashboard` > `Works Report` to verify that those pages are not breaking

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screen recording.

tested on:
- https://dev.commons-archive.org/dashboard?locale=en
- https://dev.commons-archive.org/admin/analytics/collection_reports?locale=en
- https://dev.commons-archive.org/admin/analytics/work_reports?locale=en
- https://dev.commons-archive.org/admin/analytics/work_reports/8128c621-23c0-4c6e-9fe3-89d8970e536c?locale=en (not shown in video)
- https://dev.commons-archive.org/works/45ccd215-b514-490b-a253-3374768b5999/stats?locale=en
- NEW UA# UA-251992018-1
- **note:** With the way Google Analytics is currently set up, a Google Analytics code must be added into each tenant for things to function correctly. If a tenant is not given a Google Analytics code, the dashboard will break because there is some Google Analytics functionality on the dashboard page. Things will work differently in the future, so this is a good starting point to begin that discussion so we can estimate the work for those changes 🫡

<details><summary>When a Google Analytics code is added, admin users can access the dashboard, Collections Report, Works Report, Work Report (not shown in video), and Work Show Page Analytics</summary>

https://user-images.githubusercontent.com/29311858/208166354-818b7f8c-c347-4b52-98f0-d4a6b4493da6.mp4</details>

**Comment by aprilrieger** [comment]
We pulled this out for troubleshooting purposes and we need to make a PR and get the code back in and retest on demo/prod.

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots and recording.

tested on:
- dashboard: https://dev.commons-archive.org/dashboard?locale=en
- collections report: https://dev.commons-archive.org/admin/analytics/collection_reports?locale=en
     - collection report: https://dev.commons-archive.org/admin/analytics/collection_reports/03390bb4-5e00-4000-b97f-514a40701712?locale=en
- works report: https://dev.commons-archive.org/admin/analytics/work_reports?locale=en
     - work report: https://dev.commons-archive.org/admin/analytics/work_reports/8d886268-1829-458e-bcfd-741e6531338c?locale=en
- work analytics page: https://dev.commons-archive.org/works/8d886268-1829-458e-bcfd-741e6531338c/stats?locale=en

<details><summary>The screen recording should give you a tour of most of the possible user paths. Feel free to click on anything that is a blue hyperlink (like a collection title on the collections report), or a button (like the Export button on the collections/works report)</summary>


![Image](https://user-images.githubusercontent.com/29311858/211647404-341801ee-b9c7-4d96-a1cb-a29edc0ad19d.jpg)
![Image](https://user-images.githubusercontent.com/29311858/211647442-f5962a04-39a9-476a-88d0-aae7ca3bb422.jpg)
https://user-images.githubusercontent.com/29311858/211647472-43d9a596-d539-4a98-9548-93ba6923b470.mp4
</details>

**Comment by ndroark** [comment]
The analytics button on individual files returns a 500 error. Example: https://au-archives.hykucommons.org/concern/parent/69ccff93-426a-4c2a-9dd8-985c4d933330/file_sets/73fd764e-021b-46df-a2f3-833d4de10fd2
