### ISSUE TITLE
Mirian domain name needs to be switched to new site

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#350]
[https://mushare.notch8.cloud/catalog?utf8=✓&search_field=all_fields&q=](https://mushare.notch8.cloud/catalog?utf8=%E2%9C%93&search_field=all_fields&q=) < old mushare
[https://mushare.marian.edu/catalog?utf8=✓&search_field=all_fields&q=](https://mushare.marian.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=) < new mushare
```yaml
[“f9d0fd11-6072-4f32-be09-c7ce8c3a1e91”, “103022f8-009e-49f6-b05b-b16808f4f516", “3c610db7-84f1-4816-84d7-f2874ecc13d6”, “02693b53-1560-4bbf-ac4f-86707f2ecebb”, “97b50aee-cb1c-41e1-a6da-03adfc4230ce”]
```

**Comment by labradford** [comment]
5 records need to be transported over

**Comment by crisr15** [comment]
5 records need to be copied from old system to new.  
Do that by going to the old system in the console, find the new 5 records.  
Create them in console in the new system. Want to make sure to bring the existing IDs.  
Possible create records with titles/IDs then update metadata.

**Comment by aprilrieger** [comment]
Go to r2-pals cluster, under production-palni-palci namespace, execute the shell in one of the web pods, and `rails c`
Useful commands during investigation:
```yaml
a=Account.where(cname:'marian.hykucommons.org')
Account.switch!('marian.hykucommons.org')
c=Collection.last
gw=GenericWork.last
```

Which "records" are we talking about?

**Comment by aprilrieger** [comment]
Got the 5 GenericWork ids:
[“f9d0fd11-6072-4f32-be09-c7ce8c3a1e91”, “103022f8-009e-49f6-b05b-b16808f4f516", “3c610db7-84f1-4816-84d7-f2874ecc13d6”, “02693b53-1560-4bbf-ac4f-86707f2ecebb”, “97b50aee-cb1c-41e1-a6da-03adfc4230ce”]

**Comment by aprilrieger** [comment]
`Account.switch!('mushare.notch8.cloud')`

**Comment by aprilrieger** [comment]
103022f8-009e-49f6-b05b-b16808f4f516: https://mushare.notch8.cloud/concern/generic_works/103022f8-009e-49f6-b05b-b16808f4f516
3c610db7-84f1-4816-84d7-f2874ecc13d6: https://mushare.notch8.cloud/concern/generic_works/3c610db7-84f1-4816-84d7-f2874ecc13d6
02693b53-1560-4bbf-ac4f-86707f2ecebb: https://mushare.notch8.cloud/concern/generic_works/02693b53-1560-4bbf-ac4f-86707f2ecebb
97b50aee-cb1c-41e1-a6da-03adfc4230ce: https://mushare.notch8.cloud/concern/generic_works/97b50aee-cb1c-41e1-a6da-03adfc4230ce
f9d0fd11-6072-4f32-be09-c7ce8c3a1e91: https://mushare.notch8.cloud/concern/generic_works/f9d0fd11-6072-4f32-be09-c7ce8c3a1e91?locale=en

**Comment by aprilrieger** [comment]
Here they are all moved over:

- https://mushare.marian.edu/concern/generic_works/3c610db7-84f1-4816-84d7-f2874ecc13d6?locale=en
- https://mushare.marian.edu/concern/generic_works/02693b53-1560-4bbf-ac4f-86707f2ecebb?locale=en
- https://mushare.marian.edu/concern/generic_works/97b50aee-cb1c-41e1-a6da-03adfc4230ce?locale=en
- https://mushare.marian.edu/concern/generic_works/103022f8-009e-49f6-b05b-b16808f4f516?locale=en
- https://mushare.marian.edu/concern/generic_works/f9d0fd11-6072-4f32-be09-c7ce8c3a1e91?locale=en

**Comment by ndroark** [comment]
Newly reported: Marian is experiencing an issue where their local users are getting a 404 error when navigating to the redirect (mushare.marian.edu), but not to the regular domain (marian.hykucommons.org). Outside users are not getting this error. They are checking with their IT to see if it's a local configuration issue, but I'm waiting to see how that works out before I close this.
