### ISSUE TITLE
GwR - Copy documentation into Hyku's GitHub Wiki

### ISSUE THREAD

**Issue by bkiahstroud** [scientist-softserv/palni-palci#355]
## Summary 

Documentation for the Groups with Roles feature exists in various places (the [palni-palci](https://github.com/scientist-softserv/palni-palci/blob/main/GROUPS_WITH_ROLES.md) code repo, Google Drive, etc). Documentation relevant to Hyku should be copied into [Hyku's GitHub Wiki](https://github.com/samvera/hyku/wiki). 

Creating new documentation is out of scope for this ticket. 

## Acceptance Criteria 

- [x] Locate and copy documentation relevant to the Groups with Roles feature into Hyku's GitHub Wiki 
  - [x] Ask PALNI/PALCI if they have any documentation they would like to contribute

**Comment by jillpe** [comment]
PALNI/PALCI documentation: https://docs.google.com/document/d/1dQta2JaT0rLPibl9XZNVt5VLskEWL9Ojym8EFKGdHYE/edit#heading=h.rrrlo1kmlxki
