### ISSUE TITLE
Hanover user getting unauthorized page when approving works

### ISSUE THREAD

**Issue by labradford** [scientist-softserv/palni-palci#357]
From Nic in Slack:
> User [duplaga@hanover.edu](mailto:duplaga@hanover.edu) is experiencing an issue where every time she approves a work she lands on a page with an error saying “Unauthorized. The page you have tried to access is private.” The work does approve, she just has to navigate away from that page.
> I can't replicate from my superadmin account.

**Comment by bkiahstroud** [comment]
I'm unable to reproduce this. Nothing seems to be wrong with the duplaga@hanover.edu user account as far as I can tell. Can the user please retry? If they run into the issue again, it could be related to a specific work.
