### ISSUE TITLE
Link consortia thumbnails on home page

### ISSUE THREAD

**Issue by aahurford** [scientist-softserv/palni-palci#376]
Can we hyperlink the consortia logos at the bottom of the hykucommons index/home page?  
https://palci.org/
https://palni.org/
https://www.louislibraries.org/
https://vivalib.org/

# Acceptance Criteria
- [ ] consortia logos are linked to the above locations
- [ ] There's a hyperlink [Hyku for Consortia](http://hykuforconsortia.org/) in the top text blurb 
- [ ] The email in the contact link in the footer does not have period at the end and it works properly

**Comment by DiemBTran** [comment]
QA notes:

tested on:
- https://commons-archive.org/

testing instructions:
- [x] Partnering consortia thumbnails hyperlink correctly: https://share.getcloudapp.com/xQuEv489
- [x] Hyku for Consortia hyperlinks properly: https://share.getcloudapp.com/NQupeRGo
- [ ] The email in the contact link in the footer does not have period at the end and it works properly
  - doesn't seem to work: https://share.getcloudapp.com/mXuG78O0
