### ISSUE TITLE
Hanover tenant works not showing in public view

### ISSUE THREAD

**Issue by labradford** [scientist-softserv/palni-palci#380]
> There are three works in the Hanover tenant that have been deposited and approved with public visibility, but still don't appear for public viewers. They the `Hanover, 1985`, `Hanover, 1984`, and `Monotype #8` works in the list below. They show up when you filter for works Pending Review even though they show the Deposited Status.

> Here is the list, and here is what one of the works looks like when you attempt to access is logged out. When logged in, the work appears normal, and all the required fields are filled out and editable.

https://assaydepot.slack.com/files/U03421Z2G02/F04JC3FRPNU/screenshot_47_.png
https://files.slack.com/files-pri/T045P84S5-F04H7RVMZK9/screenshot_46_.png

**Comment by labradford** [comment]
Ran the update workflow roles script on this tenant but did not seem to fix the issue

**Comment by labradford** [comment]
> This seems right, tests in Grace and Hanover have items uploading and importing correctly, but the previous Hanover items are kind of in limbo. I think it's only three items affected in Hanover, so probably not a big deal to ask the user to reupload as new works.

**Comment by bkiahstroud** [comment]
>the update workflow roles script

For the record, this is the script being referenced: 

```ruby
RolesService.grant_workflow_roles_for_all_admin_sets!
```
