### ISSUE TITLE
GwR - QA on hyku-demo.notch8.cloud

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/palni-palci#386]
# Summary

Groups with roles must be QA'd on hyku-demo.notch8.cloud. Any resulting bugs will be logged on this ticket.

# Testing instructions
- [x] Follow the Groups test plan templates
- [x] QA on demo-tenant.hyku-demo.notch8.cloud
- [x] log bugs on this ticket

**Comment by DiemBTran** [comment]
**Needs further review:**

tested on:
- https://demo-tenant.hyku-demo.notch8.cloud/

# Bug list
1. Work editor
     * Can Edit
          * From "Managed Works" tab in Dashboard > Works
            * [ ] Actions dropdown
                 * Edit button does not appear
            * [ ] Checkbox (under Select column) > "Edit Selected" button
                 * `You do not have permission to edit the documents: 1faed83c-56f0-4ed8-b473-0b372fc0c96d`
            * Attached video: Work editor cannot edit works from actions dropdown or with checkboxes :x:. However, they can edit from work show page ✅ 

https://user-images.githubusercontent.com/29311858/212787399-4db86eed-9952-424f-8c44-0e8a4630af33.mp4

2. Collection manager: can create new subcollections as subcollection
     * Can > Subcollections in Collection
          * [ ] Dashboard > Collection show > "Create new collection as subcollection" link
               * `You are not authorized to access this page.`
          * Attached video: Collection manager cannot create a new collection as a subcollection :x:. However, they can add an existing collection as a subcollection ✅ 

https://user-images.githubusercontent.com/29311858/212788671-94a9d422-05bc-4301-9488-aed12998b1b4.mp4

**Comment by bkiahstroud** [comment]
@DiemBTran how did you set up that user as a work editor and collection manager? There are several different ways: 

1. Add role directly to user 
2. Add user to Editors group 
3. Create new group, give it a role, add the user 
4. Other?

**Comment by DiemBTran** [comment]
> @DiemBTran how did you set up that user as a work editor and collection manager? There are several different ways:
> 
> 1. Add role directly to user
> 2. Add user to Editors group
> 3. Create new group, give it a role, add the user
> 4. Other?

Good question. Answer is `#3: Create new group, give it a role, add the user`

<details><summary>I made custom groups with 1 role/group. Then, I add 1 non-admin user to the group/role I am testing. I check Dashboard > Manage Users to make sure that the user has no other role than the 1 I am testing.</summary>

![Manage Groups Administration Hyku 2023-01-18 at 11 44 39 AM](https://user-images.githubusercontent.com/29311858/213279768-4c69532c-6070-4f5b-b90b-d61ceb13510f.jpg)
</details>

**Comment by bkiahstroud** [comment]
Hm, okay, thanks for clarifying. That's almost certainly a bug. Can you test those two failures using the other two methods I listed? 

> 1. Add role directly to user
> 2. Add user to Editors group

I want to make sure we don't have any other blind spots

**Comment by DiemBTran** [comment]
1. Work editor
     1. Add role directly to user
          1. Same bugged behavior
     2. Add user to Editors group
          1. Same bugged behavior
2. Collection manager
     1. Add role directly to user
          1. Same bugged behavior
     1. Add user to Managers group
          1. There is no default group with role: Collection Manager, so I was not able to test this route (as seen in attached screenshot)
<details>

![Manage Groups Administration Hyku 2023-01-18 at 2 54 25 PM](https://user-images.githubusercontent.com/29311858/213314964-0469d221-539c-47dc-9299-1578cce39d79.jpg)</details>

**Comment by DiemBTran** [comment]
Blocked by #393 and #394

**Comment by DiemBTran** [comment]
Can be closed now that https://github.com/scientist-softserv/palni-palci/issues/393 and https://github.com/scientist-softserv/palni-palci/issues/394 are separate tickets
