### ISSUE TITLE
[GwR] Cross-reference overwritten files

### ISSUE THREAD

**Issue by bkiahstroud** [scientist-softserv/palni-palci#395]
## Summary

Several files on [this PR](https://github.com/samvera/hyku/pull/1859) need to be compared with their counterparts in Hyrax v3.4.2 to ensure the changes they introduce are still valid. Mostly, this means comparing the files side by side, noting what differs between versions, and determining whether or not it necessitates a change to that override. 

## Acceptance Criteria 

- Cross-reference these files 
  - [x] `app/forms/hyrax/forms/admin/collection_type_form.rb`
  - [x] `app/forms/hyrax/forms/collection_form.rb`
  - [x] `app/models/concerns/hyrax/ability/solr_document_ability.rb`
  - [x] `app/models/hyrax/collection_type_participant.rb`
  - [x] `app/models/hyrax/permission_template_access.rb`
  - [x] `app/presenters/hyrax/admin/workflow_roles_presenter.rb`
  - [x] `app/services/hyrax/collection_types/create_service.rb`
  - [x] `app/services/hyrax/collections/permissions_service.rb`
- [ ] Create a ticket for each file whose override needs to be updated 

## Example 

See this commit: https://github.com/samvera/hyku/pull/1859/commits/caaa548d0d5c060e7f9b526c0202010ac92d823a

**Comment by aprilrieger** [comment]
- [ ] https://github.com/samvera/hyrax/blob/v3.4.2/app/forms/hyrax/forms/admin/collection_type_form.rb
- [ ] https://github.com/samvera/hyrax/blob/v3.4.2/app/forms/hyrax/forms/collection_form.rb
- [ ] https://github.com/samvera/hyrax/blob/v3.4.2/app/models/concerns/hyrax/ability/solr_document_ability.rb
- [ ] https://github.com/samvera/hyrax/blob/v3.4.2/app/models/hyrax/collection_type_participant.rb
- [ ] https://github.com/samvera/hyrax/blob/v3.4.2/app/models/hyrax/permission_template_access.rb
- [ ] https://github.com/samvera/hyrax/blob/v3.4.2/app/presenters/hyrax/admin/workflow_roles_presenter.rb
- [ ] https://github.com/samvera/hyrax/blob/v3.4.2/app/services/hyrax/collection_types/create_service.rb
- [ ] https://github.com/samvera/hyrax/blob/v3.4.2/app/services/hyrax/collections/permissions_service.rb

**Comment by aprilrieger** [comment]
PR Here: https://github.com/samvera/hyku/pull/1898
