### ISSUE TITLE
[GwR] Resolve misc feedback

### ISSUE THREAD

**Issue by bkiahstroud** [scientist-softserv/palni-palci#400]
Ref https://github.com/samvera/hyku/pull/1859 

## Acceptance Criteria 

Resolve the following requested changes: 

- [x] https://github.com/samvera/hyku/pull/1859#discussion_r1068994821
- [x] https://github.com/samvera/hyku/pull/1859#discussion_r1068994901 
- [x] https://github.com/samvera/hyku/pull/1859#discussion_r1087255069 
- [x] https://github.com/samvera/hyku/pull/1859#discussion_r1087256067 
- [x] https://github.com/samvera/hyku/pull/1859#discussion_r1087256562 
- [x] Comments that say "make sure override upgrade to Hyrax 3.4" need to be cross-referenced with Hyrax v3.4.2 

## Implementation details 

- Correct override comment format: `# OVERRIDE Hyrax v3.4.2 Reason for override` 
- How to generate translations: https://playbook-staging.notch8.com/en/samvera/hyrax/how_to/generate_translations

**Comment by aprilrieger** [comment]
https://github.com/samvera/hyku/pull/1902
