### ISSUE TITLE
Metadata Fields allowing multiple should be ordered.

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#401]
# Summary

When a user enters metadata and then saves a record, metadata on fields that allow for multiple responses do not save in order and can be reordered randomly.  This can cause confusion and order can be important.  So when items are entered as metadata they should stay in the order they were initially entered in.  

# Acceptance Criteria

- [ ] all fields that allow for multiple entries should be ordered fields.  

# Testing instructions

- [ ] Create a new work.  On fields that allow multiple entries add several entries.  Note the added order. Save the work.  View the work, save the work, view the work... repeat and make sure the fields are still in order on all saves and views. 

# Notes
- will need to pull a list of all the fields that allow multiple entries. 
- Rob noted the order_already gem 
- This has been implemented on Cal State and on Author/Creator fields in British Library

**Comment by crisr15** [comment]
https://rubygems.org/gems/order_already

**Comment by bkiahstroud** [comment]
I feel like we've solved this elsewhere before at least once, though I don't remember where specifically off the top of my head.

**Comment by bkiahstroud** [comment]
[Example from Adventist](https://github.com/scientist-softserv/adventist-dl/blob/be413e49cded6647655d6b6690a9f125bc75b708/app/models/thesis.rb#L28)

**Comment by crisr15** [comment]
Explore whether records can stay without a migration, so that they can be updated on save.

**Comment by bkiahstroud** [comment]
PR: https://github.com/scientist-softserv/palni-palci/pull/427

**Comment by crisr15** [comment]
Passes internal QA
Updated a work with multiple fields and everything stayed in order after saving.
