### ISSUE TITLE
Ability to enter rich text in some metadata fields, such as italics, bold, linebreaks, and hyperlinking

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#402]
# Summary

Users would like to be able to include additional formatting into certain metadata fields to make for easier reading and better consistency with sources.  Add the ability to support italics, bolds, linebreaks, and hyperlinking in selected metadata fields.  

# Acceptance Criteria

- [ ] Markdown displays properly on all fields. 
- [ ] there is a link to a page with markdown instructions (public user guide). 

# Testing instructions

1. Add both a work & a collection that have markdown in the title and metadata
   - [ ] italics
   - [ ] bolds
   - [ ] linebreaks
   - [ ] hyperlinking 
3. Visit the following pages to make sure markdown is appearing everywhere and there is nowhere that still shows the symbols without the correct formatting
    - [ ] Home page (test with all 4 themes)
    - [ ] Search results page
    - [ ] Work show page
    - [ ] Collection show page
    - [ ] Dashboard works/collections pages + tabs within those pages

# Notes
Lea Ann said allow HTML in metadata.  
Suggest using tinyMCE but if we use HTML limit for security.

**Comment by ndroark** [comment]
We would like this function on all fields that have free text (i.e., not a drop down menu).

**Comment by bkiahstroud** [comment]
Is HTML syntax okay? Or is another syntax like Markdown needed? 

```
# HTML
<em>Italics</em>
<strong>Bold</strong>

# Markdown
_Italics_
**Bold**
```

**Comment by ndroark** [comment]
HTML syntax is fine.

**Comment by bkiahstroud** [comment]
> HTML syntax is fine as long as we can get a list of supported prompts.

What do you envision this looking like? Help text for each text field? Examples? A link to an HTML syntax source? Etc.

**Comment by crisr15** [comment]
Question asked in channel about TinyMCE: https://assaydepot.slack.com/archives/C0313NKC08L/p1677547173790769

**Comment by crisr15** [comment]
Confirm hyperlink and linebreak.

**Comment by crisr15** [comment]
https://web-crunch.com/posts/how-to-add-markdown-support-to-ruby-on-rails

https://dev.to/stripe/rendering-markdown-with-markdoc-in-rails-3bp0

https://www.bacancytechnology.com/blog/add-markdown-to-rails-app

**Comment by DiemBTran** [comment]
**Needs further review:** Most items pass, but there are a couple of failures

# Testing instructions from this ticket

Create a new work using the fields above.  Add the following and make sure that they work in all the fields listed: 

- [x] italics
- [x] bolds
- [x] linebreaks
- [ ] hyperlinking
  - [ ] works
    - there's a weird string interpolation issue. The link should lead to https://www.google.com/, but it leads to https://qa-13.commons-archive.org/concern/generic_works/a%20href=%22https://www.google.com/%22%3E%3Cspan%20class=%22glyphicon%20glyphicon-new-window%22%3E%3C/span%3E%C2%A0https://www.google.com/%3C/a instead 
  - [x] collections

# Testing instructions from https://github.com/scientist-softserv/palni-palci/pull/437
1. Add both a work & a collection that have markdown in the title and metadata
2. Visit the following pages to make sure markdown is appearing everywhere and there is nowhere that still shows the symbols without the correct formatting
    - [ ] Home page (test with all 4 themes)
    - [x] Search results page
    - [x] Work show page
    - [ ] Collection show page
      - [x] public show page
      - [] dashboard show page
        - title's markdown is not correct
    - [x] Dashboard works/collections pages + tabs within those pages

# tested on
- work (has most of the markdown tests): https://qa-13.commons-archive.org/concern/generic_works/59dc2b80-b919-4b2f-bf8f-81edb0929abd?locale=en
- work (deposited, so I can search for this work in search results): https://qa-13.commons-archive.org/concern/generic_works/e759ab7c-16a1-4dd9-a6ec-c305f91b23e1?locale=en
- collection: https://qa-13.commons-archive.org/collections/02840d12-c62a-4c74-b58a-03a6780a945f?locale=en

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot and recording.

tested on:
- work show page: https://qa-13.commons-archive.org/concern/generic_works/59dc2b80-b919-4b2f-bf8f-81edb0929abd?locale=en
- collection dashboard show page: https://qa-13.commons-archive.org/dashboard/collections/02840d12-c62a-4c74-b58a-03a6780a945f?locale=en

# Testing instructions for rework:

- [x] Works
  - [x] Hyperlinks in description
  - [x] Hyperlinks in abstract
- [x] Collection
  - [x] Dashboard show page title

<details><summary>Hyperlinks for Works and Collections' dashboard show page titles are fixed </summary>

https://user-images.githubusercontent.com/29311858/230464767-c69e9847-6d9c-4b7a-a626-9903865c1ed1.mp4

![Diem's test to see if markdown works Hyku Commons 2023-04-06 at 11 29 41 AM](https://user-images.githubusercontent.com/29311858/230464792-6b64896c-ca52-4203-8bad-a2525f46ffe8.jpg)
</details>
