### ISSUE TITLE
Make Resource Type Required

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#404]
# Summary

Currently users do not have to enter a resource type.  Users should have to enter a Resource Type for all works added to the repository.  

# Acceptance Criteria

- [ ] All worktypes have Resource Type as a required field
- [ ] bulkrax is required.  Match other controlled field functionality. 

# Testing Instructions

1. Go to the create/edit page for each worktype and confirm that Resource Type is a required field in the UI. 
2. Try saving a record without Resource Type included and confirm you can not. 

# Notes

**Comment by bkiahstroud** [comment]
I assume this should extend to Bulkrax imports as well?

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot and recording. New works require you to add a `Resource Type` on the `new work form`. If you edit an existing work that does not have a `Resource Type`, the `edit work form` will require you to add a `Resource Type` for submission.

tested on:
- new work: https://qa-13.commons-archive.org/concern/generic_works/6dfff626-eccd-4dea-9fee-3871158c6e0a?locale=en
- existing work: https://qa-13.commons-archive.org/concern/generic_works/743c8705-5ded-4aca-a47b-6e7a952eeb63?locale=en

<details><summary>New works require you to add a Resource Type on the new work form</summary>

![Generic Work   Hyku Commons 2023-03-07 at 5 56 44 PM](https://user-images.githubusercontent.com/29311858/223600830-677c57cd-9c53-45cd-a15d-b4c13771603c.jpg)
</details>

<details><summary>If you edit an existing work that does not have a Resource Type, the edit work form will require you to add a Resource Type for submission.</summary>

https://user-images.githubusercontent.com/29311858/223601059-e5aff25e-ae27-41d3-93fe-6bac8b63181b.mp4
</details>
