### ISSUE TITLE
Test AllinsonFlex UI and record a demo

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#407]
# Summary

UTK has enabled the UI for AllinsonFlex.  Pals would like to understand how much of it is working and what would need to be resolved in order for it to meet user needs.  Test AllinsonFlex in a new tenant on UTK and record a demo for Pals.  Make a list of broken items that need to be resolved.  

# Acceptance Criteria

- [x] create a new tenant in UTK
     - https://allinsonflextest.utk-hyku-staging.notch8.cloud/
- [ ] ~~Create a new worktype~~
     - [ ] ~~this requires running a generator command locally~~
     - [ ] ~~those changes then need to be pushed/redeployed to staging for the new worktype to appear on a tenant~~
     - This is not necessary for testing
- [ ] make changes to that worktype using the UI.  
- [ ] Record a demo
- [ ] export the YAML file for a metadata profile

# Notes
Violet and Rob have the most information about AllinsonFlex for testing.  
Additionally, a deploy may update the environment variable, so if access is lost, talk with Violet team to restore.

**Comment by DiemBTran** [comment]
**QA Notes:**

Most of the UI editor functionality is broken. This is the bug list: https://docs.google.com/document/d/1yudlHsfPH7sH7T51KA6n5zAzLaBWdW8ACKyaD2_PIuI/edit#

**Comment by DiemBTran** [comment]
Now that I have tested this ticket to its fullest capacity and have created a bug list, this ticket can now be closed.
