### ISSUE TITLE
Analytics - User graph missing

### ISSUE THREAD

**Issue by labradford** [scientist-softserv/palni-palci#411]
# Summary
references https://github.com/scientist-softserv/palni-palci/issues/391

Initially the user activity graph in au-archives.hykucommons was displaying correctly, but after I added a user it disappeared. The graph is still displaying in other tenants.

# Acceptance Criteria

- [ ] The user activity graph displays correctly after users have been added

# Screenshots or Video
Dashboard user activity graph should still look like this after a user has been added: 
![Screenshot 2023-04-24 at 12 16 24 PM](https://user-images.githubusercontent.com/11359350/234094492-74994368-402f-43bd-8838-3f3e0db5bb25.png)

# Testing Instructions
Go to a tenant that has a working user activity on the dashboard.  (commons archive notch8 tenant was in good working state). 
Add a user. 
Confirm the graph still displays as show above.  

# Notes
There is a javascript error in the console on the users graph
![Image](https://user-images.githubusercontent.com/18175797/215598162-07e705b7-f982-4867-a403-b4c2ee169248.png)

**Comment by alishaevn** [comment]
contributed back to hyrax in https://github.com/samvera/hyrax/pull/6092
