### ISSUE TITLE
Fix failing PALs specs

### ISSUE THREAD

**Issue by bkiahstroud** [scientist-softserv/palni-palci#416]
## Summary

There are ~40-50 failings specs on the `main` branch in CI. This makes it very difficult to determine whether a given spec is failing due to changes on a branch or not. 

I think these have flown under the radar due to https://github.com/scientist-softserv/dev-ops/issues/525. 

## Acceptance Criteria 

- [ ] All specs pass in CI on the `main` branch 
  - [ ] Subtask: #442

**Comment by labradford** [comment]
Closing as specs are now passing per ticket #548
