### ISSUE TITLE
A single non DC field is included in the OAI feed

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#421]
# Summary

Using Jio or Adventist as a reference make one field for a non DC term appear in the OAI feed.  

# Acceptance Criteria

- [ ] A new OAI metadata prefix exists to support non DC terms.  (maybe name it hyku for advertising purposes???) add the metadata prefix to the testing instructions for this ticket
- [ ] Select a non DC field that looks difficult and add it to the testing criteria for this ticket.  
- [ ] When I go to see the OAI feed on a record, I can see the term from above that is not a DC term in the feed.  

# Testing instructions

1. select a tenant and use the documentation provided above and this playbook article to access the OAI feed.
2. Select a record from the tenant and look it up in the OAI feed using the metadata prefix oai_hyku
3. Confirm term is showing in the feed

# Notes

Jio and Adventist are utilizing adaptions to the OAI outgoing gem that allows for all metadata fields instead of just Dublin Core Metadata. Rob, Jeremy, or Braydon may have additional insight.

Standard format for oai url in hyku is: https://dc.utk-hyku-staging.notch8.cloud/catalog/oai?verb=ListRecords&metadataPrefix=oai_dc
Playbook article to look at OAI feeds: https://playbook-staging.notch8.com/en/samvera/oai-feeds

Part 1 of Epic #403

**Comment by bkiahstroud** [comment]
PR: https://github.com/scientist-softserv/palni-palci/pull/429

**Comment by bkiahstroud** [comment]
`based_near` ("Location") is probably the most complicated field to display in OAI. However, PALs does not use `based_near`. We need to check this field works when contributing back to Hyku

**Comment by bkiahstroud** [comment]
This is working, but we have a question for Rob in Slack [here](https://assaydepot.slack.com/archives/C03B6A93E31/p1677889840237369)

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot. I compared the terms in the `oai_dc feed` to the terms in the `oai_hyku` feed. The `oai_hyku` feed has non-dc feed terms.

tested on:
- `oai_hyku` feed: https://bloomsburg.commons-archive.org/catalog/oai?verb=ListRecords&metadataPrefix=oai_hyku
- `oai_dc` feed: https://bloomsburg.commons-archive.org/catalog/oai?verb=ListRecords&metadataPrefix=oai_dc

<details><summary>The oai_hyku feed has non-dc feed terms.</summary>

![OAI 2 0 Request Results 2023-03-22 at 6 37 42 PM](https://user-images.githubusercontent.com/29311858/227092828-9a37c679-855f-4aaf-b5ec-4c58eea48a27.jpg)</details>
