### ISSUE TITLE
All public metadata fields are available on records for tenants in hyku

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#422]
# Summary

Issue #421 must be done first. 

As a tenant manager, I want to be able to allow for harvesting of my tenant through OAI. Currently the OAI feed is not complete and is missing many metadata fields. Allow for all public metadata fields to be included in the OAI feed.

# Acceptance Criteria 

- [ ]  All public metadata fields are available on records for tenants in hyku
- [ ] Add the metadata prefix to the testing instructions. 

# Testing Instructions

1. select a tenant and use the documentation provided above and this playbook article to access the OAI feed.
2. Select a record from the tenant and look it up in the OAI feed.
3. Confirm all public metadata is available
4. confirm all public files are available by URL in the feed.

# Notes
Jio and Adventist are utilizing adaptions to the OAI outgoing gem that allows for all metadata fields instead of just Dublin Core Metadata. Rob, Jeremy, or Braydon may have additional insight.

Standard format for oai url in hyku is: https://dc.utk-hyku-staging.notch8.cloud/catalog/oai?verb=ListRecords&metadataPrefix=oai_dc
https://playbook-staging.notch8.com/en/samvera/oai-feeds

Part 2 of Epic #403

**Comment by labradford** [comment]
List of metadata fields is in Google drive in the client folder

**Comment by bkiahstroud** [comment]
PR: https://github.com/scientist-softserv/palni-palci/pull/429

**Comment by bkiahstroud** [comment]
Please check all the boxes next to properties that should be considered as "public": 

- [ ] abstract
- [ ] access_right
- [ ] accessibility_feature
- [ ] accessibility_hazard
- [ ] accessibility_summary
- [ ] additional_information
- [ ] advisor
- [ ] alternate_version_id
- [ ] alternative_title
- [ ] audience
- [ ] based_near
- [ ] bibliographic_citation
- [ ] bulkrax_identifier
- [ ] committee_member
- [ ] contributor
- [ ] create_date
- [ ] creator
- [ ] date_created
- [ ] date_modified
- [ ] date_uploaded
- [ ] degree_discipline
- [ ] degree_grantor
- [ ] degree_level
- [ ] degree_name
- [ ] department
- [ ] depositor
- [ ] description
- [ ] discipline
- [ ] education_level
- [ ] extent
- [ ] format
- [ ] has_model
- [ ] identifier
- [ ] import_url
- [ ] keyword
- [ ] label
- [ ] language
- [ ] learning_resource_type
- [ ] license
- [ ] modified_date
- [ ] newer_version_id
- [ ] oer_size
- [ ] owner
- [ ] previous_version_id
- [ ] proxy_depositor
- [ ] publisher
- [ ] related_item_id
- [ ] related_url
- [ ] relative_path
- [ ] resource_type
- [ ] rights_holder
- [ ] rights_notes
- [ ] rights_statement
- [ ] source
- [ ] subject
- [ ] table_of_contents
- [ ] title

**Comment by DiemBTran** [comment]
Diem's QA:
- tested on: https://dev.commons-archive.org/catalog/oai?verb=ListRecords&resumptionToken=oai_hyku.f(2021-10-14T13:52:35Z).u(2023-03-22T22:16:07Z).t(542):500

- [ ] abstract
- [ ] access_right
- [ ] accessibility_feature
- [ ] accessibility_hazard
- [ ] accessibility_summary
- [ ] additional_information
- [ ] advisor
- [ ] alternate_version_id
- [ ] alternative_title
- [ ] audience
- [ ] based_near
- [ ] bibliographic_citation
- [ ] bulkrax_identifier
- [ ] committee_member
- [ ] contributor
- [ ] create_date
- [ ] creator
- [ ] date_created
- [ ] date_modified
- [ ] date_uploaded
- [ ] degree_discipline
- [ ] degree_grantor
- [ ] degree_level
- [ ] degree_name
- [ ] department
- [ ] depositor
- [ ] description
- [ ] discipline
- [ ] education_level
- [ ] extent
- [ ] format
- [ ] has_model
- [ ] identifier
- [ ] import_url
- [ ] keyword
- [ ] label
- [ ] language
- [ ] learning_resource_type
- [ ] license
- [ ] modified_date
- [ ] newer_version_id
- [ ] oer_size
- [ ] owner
- [ ] previous_version_id
- [ ] proxy_depositor
- [ ] publisher
- [ ] related_item_id
- [ ] related_url
- [ ] relative_path
- [ ] resource_type
- [ ] rights_holder
- [ ] rights_notes
- [ ] rights_statement
- [ ] source
- [ ] subject
- [ ] table_of_contents
- [ ] title
