### ISSUE TITLE
OAI -  links to public files on works are available.

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#423]
# Summary

Cannot be done before  #421 

When looking at an OAI feed in hyku I can see links to any public files attached to works.  

# Acceptance Criteria
 
- [ ] links to public files on works are available.

# Testing Instructions
Get metadata prefix and notes from #421 or #422 

1. select a tenant and use the documentation provided above and this playbook article to access the OAI feed. - https://playbook-staging.notch8.com/en/samvera/oai-feeds
2. Create a work with two public file sets and look it up in the OAI feed 
3. Confirm that all of the public files are listed as `<file_url>`s in the feed 
4. Edit one of the file sets (work show page > file sets list > actions button dropdown > edit) 
5. Change its visibility to Private and save 
6. Look up the same record in the OAI feed and make sure the private file set is **not** listed 

Part of Epic #403

**Comment by labradford** [comment]
Jio has this feature

**Comment by bkiahstroud** [comment]
Need clarification regarding whether these links should point to external (e.g. `https://example.com/my_file.png`) or internal locations (e.g. `https://test.hykucommons.org/downloads/my_file.png`) (or both). If external, where should this value come from?

**Comment by crisr15** [comment]
Internal location.  This should be the hyku link directly to the file as show in your example above.

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot and recording.

tested on:
- work with 2 filesets: https://qa-9.commons-archive.org/concern/generic_works/0fabf9cf-5771-48a3-82ad-2b49ff7d9402?locale=en
- public fileset that I turn private: https://qa-9.commons-archive.org/concern/parent/0fabf9cf-5771-48a3-82ad-2b49ff7d9402/file_sets/492757cf-83e2-4fb9-90bc-2eb7510763a1
- public fileset that stays public: https://qa-9.commons-archive.org/concern/parent/0fabf9cf-5771-48a3-82ad-2b49ff7d9402/file_sets/5d893bcf-e229-438f-b8d8-0e08764bb8c3
- OAI feed to access the 1 work that has 2 filesets: https://qa-9.commons-archive.org/catalog/oai?verb=GetRecord&metadataPrefix=oai_hyku&identifier=0fabf9cf-5771-48a3-82ad-2b49ff7d9402

<details><summary>When both filesets are public, they can both be seen in the OAI feed. When 1 of those filesets is turned private, that 1 disappears from the public OAI feed</summary>

![33f8c86b-aed5-44e9-8c2d-2e29bccb43a9](https://user-images.githubusercontent.com/29311858/230491894-aa9a84a1-f98d-4ec6-939a-99a655b82b94.jpg)
![OAI 2 0 Request Results 2023-04-06 at 12 14 59 PM (2)](https://user-images.githubusercontent.com/29311858/230491949-f5dc6a78-dcc6-4655-96be-f93d72fd4092.jpg)
![1da2d2d3-570e-4c48-9f0a-cd428d4e01f7](https://user-images.githubusercontent.com/29311858/230492008-ce147454-b4f8-43c1-8de7-96ab11e93e0a.jpg)
![OAI 2 0 Request Results 2023-04-06 at 12 28 19 PM (2)](https://user-images.githubusercontent.com/29311858/230492063-0431c808-b575-45bf-adac-199b9a1c997b.jpg)

</details>
