### ISSUE TITLE
OAI - Documentation on how to access an OAI feed

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#424]
# Summary

#421 must be completed first

As a repository manager I want documentation that tells me how to access my OAI feed, what my metadata prefix should be, what identifier is used, and how to make basic OAI calls.  

# Acceptance Criteria
A document or playbook article with the following has been shared with Pals

- [x] base URL for OAI
- [x] Metadata prefix for OAI
- [x] identifier used in OAI to find records (hyku identifier?)
- [x] basic calls for seeing and accessing the feed.  

# Notes 
This playbook article may be helpful as a base.  https://playbook-staging.notch8.com/en/samvera/oai-feeds

Part of Epic #403

**Comment by crisr15** [comment]
Documentation at: https://docs.google.com/document/d/1lGyu9-YGT9-_Fvsl00Zz0_dvM3G0GkW-SD0GZK3QT8o/edit

**Comment by labradford** [comment]
Ready for client QA once the staging deploy has happened
