### ISSUE TITLE
Undefined method "split" for Hyrax::ControlledVocabularies::Location

### ISSUE THREAD

**Issue by bkiahstroud** [scientist-softserv/palni-palci#434]
## Story 

This ticket corresponds to this error in Sentry: https://scientist-inc.sentry.io/issues/4022055938/?project=6707374&query=is%3Aunresolved&referrer=issue-stream 

This error happened when @ndroark deposited a work without a file, meaning it might be related to https://github.com/scientist-softserv/palni-palci/issues/406

**Comment by ndroark** [comment]
The error seems to be tagged specifically to adding works to collections in the au-archives tenant

**Comment by Aaryanpal** [comment]
@bkiahstroud Let me in.. i would like to work on this

**Comment by bkiahstroud** [comment]
Closing (duplicate of https://github.com/scientist-softserv/palni-palci/issues/432)
