### ISSUE TITLE
Bug: Resource type requirement breaking bulkrax imports on collections and ETDs

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#436]
# Summary

On #404  we made Resource Type a required field on all models, instead of just worktypes.  And we did not catch that on ETD the field name for Resource Type is "Learning Resource Type" (Just Type as the label in the UI). And that it has a slightly different vocabulary.  

When I add a column for resource type to the importer, it works, and if the resource type and learning resource type are different controlled vocabulary terms, it maps both to Learning Resource Type (since Resource Type isn't a field in the ETD worktype).
edit. And if they are the same, it lists the term twice in Learning Resource Type.  

Sample import: https://delete-me-when-done.hykucommons.org/importers/1?locale=en

Slack message for additional context

Ref:

- https://github.com/scientist-softserv/palni-palci/issues/404

# Analysis

Bulkrax has an implicit assumption that the mapping fields are generally available; but we only map onto the Factory class (e.g. Work, FileSet, and Collection) the fields that exist.

Below is an excerpt from the `lib/configuration/bulkrax.rb`.  The ETD model has a `resource_type` field.  However the OER model has `learning_resource_type`.  When we’re importing rows, if the row were to be for an OER and had a value for `resource_type`, we’d skip adding that property.

```ruby
'learning_resource_type' => { from: ['learning_resource_type'], split: '\|' },
'resource_type' => { from: ['type'], split: '\|' },
```

Fundamentally, before we begin fully processing a row, we need to know what it’s underlying Factory class is; then we can perform data validations by looking at the intersection of:

-   `importerexporter.mapping.keys`
-   `Bulkrax.required_elements`

See [Bulkrax::ApplicationParser#required\_elements](https://github.com/samvera-labs/bulkrax/blob/e1d8a4e7f80074908991907b7aeaa38ba865258d/app/parsers/bulkrax/application_parser.rb#L279-L291); this is on the application parser, but missing is the consideration for the Factory class.

```ruby
def required_elements
  matched_elements = ((importerexporter.mapping.keys || []) & (Bulkrax.required_elements || []))
  unless matched_elements.count == Bulkrax.required_elements.count
    missing_elements = Bulkrax.required_elements - matched_elements
    error_alert = "Missing mapping for at least one required element, missing mappings are: #{missing_elements.join(', ')}"
    raise StandardError, error_alert
  end
  if Bulkrax.fill_in_blank_source_identifiers
    Bulkrax.required_elements
  else
    Bulkrax.required_elements + [source_identifier]
  end
end
```

# Workaround

The quick fix is to remove the required_fields that are not valid across all models.  

The general fix is to improve the validation logic to be more configurable and record aware.

# Acceptance Criteria

- [ ] I can import a Collection or Fileset through bulkrax without a Resource Type. 
- [ ] When I import an ETD or OER Learning Resource Type is required and Resource Type is not.  Resource type does not map to ETD and if it is used in the header it is ignored. _Edit: Disregard this acceptance criteria. Only OER should have Learning Resource Type, and both Type and Learning Resource Type should be required for OER. Resource Type should still be required for ETD. -ND_
- [ ] "Type_1" should be an acceptable alternative to "resource_type" in GenericWork, Image, Oer, and Etd works where "resource_type" is a required field.
- [ ] Roundtripping should not produce errors because "resource_type" is absent from the import, as long as type_1 is present
- [ ] Bulkrax and the UI's work creation form have the same required fields
 
# Testing Instructions
- [ ] Create a CSV importer and use this zip [oer_collection_fileset.zip](https://github.com/scientist-softserv/palni-palci/files/14517843/oer_collection_fileset.zip)
- [ ] Observe that the import succeeds

**Comment by ndroark** [comment]
ETD and OER both use Learning Resource Type and I believe they map identically. OER should behave the same way as ETD.

**Comment by alishaevn** [comment]
@ndroark can you upload the zip file you used on https://delete-me-when-done.hykucommons.org/importers/1?locale=en?

**Comment by ndroark** [comment]
I won't have access to the device where that actual file is located until Tuesday, but I believe I've back-constructed the same CSV and file set. The zip is too big to attach here, so I'll try it in slack

**Comment by alishaevn** [comment]
the zip file is [here](https://assaydepot.slack.com/archives/C0313NKC08L/p1680823812524769).

**Comment by ndroark** [comment]
Another issue with resource_type being a requirement is that works export with the fields labeled type_1, type_2, etc., which makes roundtrip updates produce errors, because "resource_type" is absent from the import.

**Comment by laritakr** [comment]
Based on the above comment, it appears that should also be added to the acceptance criteria.

**Comment by ndroark** [comment]
Agreed, "type_1" should be an acceptable alternative to "resource_type" in GenericWork, Image, Oer, and Etd works where "resource_type" is a required field.

**Comment by jillpe** [comment]
@ndroark could we get an updated version of the data that is being pushed through?

**Comment by ndroark** [comment]
Here is one each for GenericWork, Etd and Oer, all with a Collection included. 

[Copy of Hyku ETD Importer - ETD.csv](https://github.com/scientist-softserv/palni-palci/files/14464347/Copy.of.Hyku.ETD.Importer.-.ETD.csv)
[Copy of Hyku OER Importer - Sheet1.csv](https://github.com/scientist-softserv/palni-palci/files/14464346/Copy.of.Hyku.OER.Importer.-.Sheet1.csv)
[Copy of Hyku Generic Worktype Importer - Sheet1.csv](https://github.com/scientist-softserv/palni-palci/files/14464348/Copy.of.Hyku.Generic.Worktype.Importer.-.Sheet1.csv)

**Comment by jillpe** [comment]
SoftServ QA: ✅ 

[Importer](https://dev.commons-archive.org/importers/153?locale=en)



![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/48b07c34-6364-4901-ab42-c5b7f205ce0d)

**Comment by ndroark** [comment]
It looks like the work in this ticket or [990](https://github.com/scientist-softserv/palni-palci/issues/990) affected how some column names have to be labeled. Previously, columns could be titled with either spaces or underscores, now they require underscores in required fields (e.g. "date created" now has to be "date_created"). Can we restore that previous either/or functionality for column names?
