### ISSUE TITLE
Improve User Management - Add the ability to remove roles that have been directly added to users

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#445]
# Story

Currently when a role has been directly added to a user it can not be removed.  There is no option to edit permissions from the manage users page.  Add the ability for users with the manage user role to remove roles from users who have either manage user roles or below.  Add the ability for users with the admin role to remove roles from any user.  This only applies to roles directly added to users, and you should not be able to remove roles added to a user by a group.  

# Acceptance Criteria

- [x] After a role has been added directly to a user (user A), a user (user B) with permissions 'user manager' can remove the roles directly added to user A if  user A is not an admin 
- [x] After a role has been added directly to a user (user A), a user (user B) with permissions 'admin' can remove the roles directly added to user A.  
- [x] Roles added by groups can not be removed without removing the user from the group.  (dev note: is this saying that if a user is part of a group, you can't remove group roles it has?)

# Screenshots / Video
Current functionality does not have any way to remove a role from a user.  
![Screenshot 2023-04-24 at 12 42 46 PM](https://user-images.githubusercontent.com/11359350/234099983-5ea4a02e-fa75-4ff9-95bd-6694fea0b20a.png)

# Testing Instructions

- As a user who has a 'user manager' role, add a role directly to a user (User A) who is not an admin. 
- As a user who has ~a 'user manager'~ an 'admin' role, add an admin role directly to a user (User C).
- As a user with role 'user manager' remove that role from the user A.
- As a user with role 'user manager' try to remove admin role from user C. You should not be able to.  
- As a user with role 'admin' remove admin role from user C.  
- As a user with role 'admin' try to remove a role that was inherited from a group.  You should not be able to.  

# Notes

**Comment by crisr15** [comment]
Did not have room in the budget to complete during the Workflow Sprint.  This item has been moved back to no status to be reprioritized.

**Comment by laritakr** [comment]
QA in progress
