### ISSUE TITLE
Improve User Management - Ability for superadmins to activate users

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#446]
# Story

Add the ability for super admins to activate users. Currently, if a user's invite gets lost in spam, or delivery fails, a developer has to go and activate the user after a super admin requests it.  Instead, super admins should have a button they can press that will activate the user.  

# Acceptance Criteria

- [ ] As a super admin I have a button I can press that will active a user if they are unable to find their invitation email.  

# Screenshots / Video

# Testing Instructions and Sample Files
**Developer add instructions for where to find this button.**  
- Create a new user. Do not open the email sent to the new user.  
- Click the activate user button.  
- Confirm you can log in as user.  (password: password) 

# Notes
Because only the super admin can access this, should the button be on the super admin user view (at the hyku level instead of at the tenant level)? 
Lea Ann has a script she runs that activates the users currently.  
Do we need to set a password?

**Comment by crisr15** [comment]
Did not have room in the budget to complete during the Workflow Sprint.  This item has been moved back to no status to be reprioritized.

**Comment by ShanaLMoore** [comment]
# QA RESULTS: ✅ 

Invited 'test@example.com'. Clicked activate button. 

**

![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/b2d595df-d5f5-4f01-9bb0-b2c97a02496c)

**

signed in as test@example.com/password



![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/909bf57d-dbdf-4349-b881-9c9714aafa6f)
