### ISSUE TITLE
Remove Workflow Roles Section on Dashboard

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#447]
# Story

For many tenants the workflow roles is unnecessary and confusing when they are using users groups and roles.  In order to make it easier for users on tenants who do not need additional customizations, we want to be able to hide the Workflow Roles Section on the Dashboard.  Create a feature flipper that will hide the 'Workflow Roles" menu item on the Dashboard.  The routes can still be available if anyone wants them.

# Acceptance Criteria

- [ ] a Feature Flipper exists to hide the Workflow Roles menu item in the dashboard. 
- [ ] When activated, the Workflow Role tab no longer exists on the menu. 

# Screenshots / Video

![Image](https://user-images.githubusercontent.com/11359350/234141410-5ec63182-2bf7-488e-a988-1de55631a55a.png)

# Testing Instructions 
- Go to Dashboard -> Settings -> Features and turn on the feature flipper for hiding Workflow Roles
- Go to Dashboard and confirm you can not see Workflow Roles on the Dashboard.  

# Notes

**Comment by aprilrieger** [comment]
Deployed to demo and tested on the dev tenant: https://dev.commons-archive.org/


![Image](https://github.com/scientist-softserv/palni-palci/assets/63515648/4c26854d-8fc4-432a-8a54-1fcdaaef33ab)
![Image](https://github.com/scientist-softserv/palni-palci/assets/63515648/460915aa-0a6e-480b-829a-687d56d85207)
