### ISSUE TITLE
Improve Settings-> Appearance-> Color Labels and Help Text

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#449]
# Summary

As a user, it is hard to know what I am adjusting when I adjust the colors in the Appearance panel.  The names of the elements in the UI do not necessarily relate to where they are used and it can be confusing.  
Update the names associated with the colors in the admin panel and add any necessary help text that clarify where else the color may be getting used.  

![Image](https://user-images.githubusercontent.com/11359350/236310618-d09b633c-c42a-47cd-bcaa-be285c87c86e.png)

This ticket will require some research to see where the colors are being used and some thought work on how to name them so that users can more easily understand.  

# Acceptance Criteria

- [ ] The names for colors have been updated so that they make more sense with what you are updating in the application when you change that color.  
- [ ] Help text is available under the name for colors that we think need more description of where they are used.  

# Testing Instructions

- [ ] Go to Setting-> Appearance -> colors and confirm that the names have been update.  
- [ ] Update the colors and confirm that they update where the expect them to.

**Comment by alishaevn** [comment]
new ticket to run translations: 
- https://github.com/scientist-softserv/palni-palci/issues/455

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

tested on:
- https://qa-13.commons-archive.org/admin/appearance?locale=en#color

- [x] Go to Setting-> Appearance -> colors and confirm that the names have been update
- [x] Update the colors and confirm that they update where the expect them to
- **QA Note**:  While testing, I noticed that the color changes don't apply to the `Home Page` theme > `Institutional Repository`. This ticket's scope just addresses the labels and help text (and not how the theming is applied), so this probably indicates that there’s a theming problem in main Hyku.

<details><summary>labels and help text have been updated</summary>

![Show Appearance Hyku Commons 2023-05-17 at 9 50 45 AM](https://github.com/scientist-softserv/palni-palci/assets/29311858/5f3011c3-eba5-44ea-b5fd-b7aac90ef0c7)
![Hyku Commons 2023-05-17 at 9 50 56 AM](https://github.com/scientist-softserv/palni-palci/assets/29311858/3165d88a-c9b5-47ff-81d9-f6a96d20ec75)
</details>

**Comment by alishaevn** [comment]
contributed back to hyku in: https://github.com/samvera/hyku/pull/1957.
