### ISSUE TITLE
run translations

### ISSUE THREAD

**Issue by alishaevn** [scientist-softserv/palni-palci#455]
# Story
- related: #449 

We added new color hints in the issue above and will need to run translations when we have an available API key.

# Acceptance Criteria

- [x] translations exist in all of the existing locale files that correspond to the existing color form label hints
  - [x] de translations generated
    - [x] labels
    - [x] hint text
  - [x] es translations generated
    - [x] labels
    - [x] hint text
  - [x] fr translations generated
    - [x] labels
    - [x] hint text
  - [x] it translations generated
    - [x] labels
    - [x] hint text
  - [x] pt-BR translations generated
    - [x] labels
    - [x] hint text
  - [x] zh translations generated
    - [x] labels
    - [x] hint text

# Testing Instructions and Sample Files

- [ ] As an admin user, navigate to the `dashboard` > `appearance` > `colors` page
- [ ] From the top nav bar, change the language and verify that the following translations exist for each language:
  - [ ] de translations generated
    - [ ] labels
    - [ ] hint text
  - [ ] es translations generated
    - [ ] labels
    - [ ] hint text
  - [ ] fr translations generated
    - [ ] labels
    - [ ] hint text
  - [ ] it translations generated
    - [ ] labels
    - [ ] hint text
  - [ ] pt-BR translations generated
    - [ ] labels
    - [ ] hint text
  - [ ] zh translations generated
    - [ ] labels
    - [ ] hint text 

# Notes

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

tested on:
- https://qa-14.commons-archive.org/admin/appearance?locale=de#color
- https://qa-14.commons-archive.org/admin/appearance?locale=es#color
- https://qa-14.commons-archive.org/admin/appearance?locale=fr#color
- https://qa-14.commons-archive.org/admin/appearance?locale=it#color
- https://qa-14.commons-archive.org/admin/appearance?locale=pt-BR#color
- https://qa-14.commons-archive.org/admin/appearance?locale=zh#color

<details><summary>Translations have been created for all labels and hint texts in all languages</summary>

![Show Appearance Hyku 2023-06-07 at 2 51 39 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/7d912a04-fa71-4592-ade3-4c32462386ba)
![Show Appearance 俳句 2023-06-07 at 2 52 39 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/8a90208f-65d7-4cfc-9ea2-598d9b10fd9b)
</details>
