### ISSUE TITLE
CDL worktype

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#457]
# Story

SoftServ will create a CDL work type with a minimal set of standard metadata. Final schema to be defined prior to development

# Acceptance Criteria

- [x] CDL Worktype has same metadata fields and mapping as GenericWork
- [x] CDL Worktype metadata will include `contributing library`
- [x] CDL Worktype metadata will include `library catalog identifier `
- [x] CDL Worktype metadata will include `chronology note ` - This field is text area
- [ ] CDL Worktype shows audio, video, and PDF files in the UV
- [ ] the contributing library field will be a facet
- [ ] All 3 new fields will be added to the show page, but will be visible only to admins.

# Testing Instructions and Sample Files

- Login as Admin and go to the Works page in the dashboard Dashboard > Works (https://reshare.palni-palci-staging.notch8.cloud/dashboard/my/works?locale=en)
- Create a new work (Click Add New Work button)
- Select the CDL worktype (Modal will popup, select CDL)
  - You may need to enable the worktype first in `dashboard` > `available work types`
- Make sure the work includes the same metadata as GenericWork plus the three new fields listed above
- Make sure the CDL worktype will split PDFs for viewing in the UV
- Make sure audio and video files display in the UV for the CDL worktype

# Notes

Need worktype specification from ReShare. 

### Metadata Fields for CDL Work Type
SoftServ will create a CDL work type with a minimal set of standard metadata. Final schema to be defined prior to development, but will be a simple, broadly applicable schema including **title**, **author**, **publication date**. Additional required metadata includes, but may not be limited to:
**Contributing Library.** A text field for the pilot to be populated with a library-identifying code, such as an ISIL identifier.
**Local System Identifier.** This comes from the contributing library and typically matches the 001 field in a library catalog record.
**Multivolume Metadata.** This would include Volume, Issue, and potentially other fields.
NISO CDL Fields. These are to be determined, but the goal is for other systems to be able to identify the work as CDL.

**Comment by labradford** [comment]
Start with Same fields as GenericWork

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

tested on:
- CDL work with full metadata: https://qa-1.palni-palci-staging.notch8.cloud/concern/cdls/23ab3f51-2201-4102-bbf0-0916c0528ae4?locale=en
- generic work with full metadata for comparison: https://qa-1.palni-palci-staging.notch8.cloud/concern/generic_works/6f00a49b-5dda-4385-ba1d-d894a38deb89?locale=en
- new CDL work form: https://qa-1.palni-palci-staging.notch8.cloud/concern/cdls/new?locale=en
- CDL pdf: https://qa-1.palni-palci-staging.notch8.cloud/concern/cdls/155fa07f-b5a3-48c7-b71f-90fd29d991a7?locale=en
- CDL audio: https://qa-1.palni-palci-staging.notch8.cloud/concern/cdls/f8f0805c-57e0-4ae6-b489-75925f8b52d8?locale=en
- CDL pdf: https://qa-1.palni-palci-staging.notch8.cloud/concern/cdls/31460aca-f042-40e7-ba3c-86df558ba98e?locale=en

- [x] CDL Worktype has same metadata fields and mapping as GenericWork
- [x] CDL Worktype metadata will include contributing library
- [x] CDL Worktype metadata will include library catalog identifier 
- [x] CDL Worktype metadata will include chronology note  - This field is text area
- [x] CDL Worktype shows audio, video, and PDF files in the UV the contributing library field will be a facet
- [x] All 3 new fields will be added to the show page, but will be visible only to admins.

<details><summary>All acceptance criteria pass</summary>

![another CDL work type Cdl  23ab3f51-2201-4102-bbf0-0916c0528ae4  Hyku Commons 2023-05-24 at 3 37 36 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/5bc7fe32-d3d1-4ee2-80ae-9f0778ed14c5)
![Cdl another CDL work type ID 23ab3f51-2201-4102-bbf0-0916c0528ae4 Hyku Commons 2023-05-24 at 3 37 59 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/3c76c903-d633-4de6-8fd1-bd25e1b94bbc)
![Cdl another CDL work type ID 23ab3f51-2201-4102-bbf0-0916c0528ae4 Hyku Commons 2023-05-24 at 3 38 17 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/aa851221-5212-4900-9061-abfca16b2c67)
![generic work ID 6f00a49b-5dda-4385-ba1d-d894a38deb89 Hyku Commons 2023-05-24 at 3 42 25 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/35ff5384-97b1-42df-961e-f96da73ef25c)
![Cdl cdl audio ID f8f0805c-57e0-4ae6-b489-75925f8b52d8 Hyku Commons 2023-05-24 at 4 15 52 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/2ec0b8f8-de9f-45a6-9c2e-f9d7917c1d67)
![Cdl cdl video ID 31460aca-f042-40e7-ba3c-86df558ba98e Hyku Commons 2023-05-24 at 4 13 11 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/a75c7e6f-2bc8-4ed1-8356-1b872d6b394f)
![Cdl cdl pdf ID 155fa07f-b5a3-48c7-b71f-90fd29d991a7 Hyku Commons 2023-05-24 at 4 15 38 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/cc2e38a3-16ba-4598-bf0c-fecd67857f8e)
</details>

**Comment by crisr15** [comment]
Approved to close during meeting with ReShare on 8/29
