### ISSUE TITLE
Add account setting for disabling downloads

### ISSUE THREAD

**Issue by labradford** [scientist-softserv/palni-palci#468]
# Story
Part of #460 

There should be an account setting for disabling downloads within a tenant
# Acceptance Criteria

- [ ] There is a checkbox for allowing downloads on the Accounts page
- [ ] There is a checkbox for allowing downloads in the Admin dashboard of the tenant `admin/account/edit` or Dashboard > Settings > Account
# Screenshots / Video

# Testing Instructions and Sample Files

- [ ] To test on staging, log into https://palni-palci-staging.notch8.cloud/ as a super admin user
- [ ] Navigate to the proprietor Accounts Edit form: https://palni-palci-staging.notch8.cloud/proprietor/accounts/3/edit?locale=en
- [ ] Scroll down to the `Account Setting` section. Verify that there is an `Allow downloads` checkbox
- [ ] In a new window, navigate to your tenant's `Dashboard > Settings > Account` form: https://reshare.palni-palci-staging.notch8.cloud/admin/account/edit?locale=en
- [ ] Verify that there is an `Allow downloads` checkbox
<details><summary>Click to expand and see how to test this on the proprietor Accounts Edit form and the tenant Account form</summary>

https://github.com/scientist-softserv/palni-palci/assets/29311858/bc86abd0-5056-4f26-81d7-b501815a365c
</details>

# Notes

Setting can be added in app/models/concerns/account_settings.rb

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

tested on:
- proprietor account settings page: https://palni-palci-staging.notch8.cloud/proprietor/accounts/2/edit?locale=en
- tenant's account settings page: https://qa-1.palni-palci-staging.notch8.cloud/admin/account/edit.2?locale=en
- work show page:
- fileset show page: 

<details><summary>"Allow downloads" checkbox works as expected</summary>

![Edit Account Hyku Commons 2023-05-22 at 12 42 32 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/baac7804-0fcf-4fcf-98ab-81d91c961ba9)
![Edit Account Hyku Commons 2023-05-22 at 12 43 37 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/7b523aa4-9da9-45db-86a0-6ed697d83003)
![2023-05-22 Hyku upgrade #456 - pdf ID 07f197cb-a77e-4d53-ad21-c10ca6a3bc35 Hyku Commons 2023-05-22 at 12 41 12 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/a730d7f2-a8e5-404f-87b1-dc6b67b6c87a)
![File simpsons_trombone pdf ID 2a085c72-31e4-43f3-b861-7352f028d8fb Hyku Commons 2023-05-22 at 12 41 21 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/60c9bbd6-1482-43fe-8289-3ca3388dcf4c)
![2023-05-22 Hyku upgrade #456 - pdf ID 07f197cb-a77e-4d53-ad21-c10ca6a3bc35 Hyku Commons 2023-05-22 at 12 41 55 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/b27ab641-a1c0-4c22-b987-ddbd1a06d8f8)
![File simpsons_trombone pdf ID 2a085c72-31e4-43f3-b861-7352f028d8fb Hyku Commons 2023-05-22 at 12 42 07 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/503d6fe3-c55c-4176-b078-d4fd69dbca10)

</details>
