### ISSUE TITLE
Disable fileset downloads when Account setting to disable downloads is checked

### ISSUE THREAD

**Issue by labradford** [scientist-softserv/palni-palci#469]
# Story
Part of #460 

When the disable download box is checked, users cannot download files sets from the work show page or from the file set show page, or any other location for downloads (except the universal viewer)

# Acceptance Criteria

- [ ] When the account setting for disable downloads is checked, users cannot see links to download files from the work show page
- [ ] When the account setting for disable downloads is checked, users cannot see links to download files from the fileset page

# Screenshots / Video

<details>
<summary>work show page</summary>

![Screenshot 2023-05-15 at 12 07 33 PM](https://github.com/scientist-softserv/palni-palci/assets/18175797/f6c5a464-5317-424b-ba29-ee795361ce7e)

</details>

<details>
<summary>fileset show page</summary>

![Screenshot 2023-05-15 at 12 08 04 PM](https://github.com/scientist-softserv/palni-palci/assets/18175797/cfe831b8-c65e-4784-a429-20170a3232bb)

</details>

# Testing Instructions and Sample Files

- [ ] To test on staging, log into https://reshare.palni-palci-staging.notch8.cloud/ as admin user
- [ ] Open this work show page: https://reshare.palni-palci-staging.notch8.cloud/concern/cdls/7cee6c8f-0fd0-4f0c-88ed-8441fc4d16a7?locale=en
- [ ] Testing this from the proprietary Accounts page
  - [ ] In a new window, navigate to the proprietor Accounts Edit form: https://palni-palci-staging.notch8.cloud/proprietor/accounts/3/edit?locale=en
  - [ ] Testing downloads enabled
    - [ ] Scroll down to the `Account Setting` section. Find the `Allow downloads` checkbox
    - [ ] Check the box to enable downloads. Click the `Save changes` button at the bottom of the form
    - [ ] Navigate back to the work show page and refresh the page. Scroll down to the `Items` section. The first item should have an `Actions` dropdown menu. Verify that when downloads are enabled, there is a `Download` option in this dropdown menu.
  - [ ] Testing downloads disabled
    - [ ] Scroll down to the `Account Setting` section. Find the `Allow downloads` checkbox
    - [ ] Uncheck the box to disable downloads. Click the `Save changes` button at the bottom of the form
    - [ ] Navigate back to the work show page and refresh the page. Scroll down to the `Items` section. The first item should have an `Actions` dropdown menu. Verify that when downloads are disabled, there is **no** `Download` option in this dropdown menu.
- [ ] Testing this from the `Dashboard > Settings > Account` page
  - [ ] In a new window, navigate to the `Dashboard > Settings > Account` form: https://reshare.palni-palci-staging.notch8.cloud/admin/account/edit?locale=en
  - [ ] Testing downloads enabled
    - [ ] Find the `Allow downloads` checkbox
    - [ ] Follow the steps above to test when downloads are enabled
  - [ ] Testing downloads enabled
    - [ ] Find the `Allow downloads` checkbox
    - [ ] Follow the steps above to test when downloads are disabled

<details><summary>Click to expand and see how to test this ticket.</summary>

https://github.com/scientist-softserv/palni-palci/assets/29311858/970bc89e-682f-4954-903b-866e107b9110
</details>

# Notes
The entire Files section can probably be removed from the workshow page if disable downloads is checked

**Comment by sephirothkod** [comment]
https://github.com/scientist-softserv/palni-palci/pull/488

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

tested on:
- proprietor account settings page: https://palni-palci-staging.notch8.cloud/proprietor/accounts/2/edit?locale=en
- tenant's account settings page: https://qa-1.palni-palci-staging.notch8.cloud/admin/account/edit.2?locale=en
- work show page:
- fileset show page: 

<details><summary>"Allow downloads" checkbox works as expected</summary>

![Edit Account Hyku Commons 2023-05-22 at 12 42 32 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/baac7804-0fcf-4fcf-98ab-81d91c961ba9)
![Edit Account Hyku Commons 2023-05-22 at 12 43 37 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/7b523aa4-9da9-45db-86a0-6ed697d83003)
![2023-05-22 Hyku upgrade #456 - pdf ID 07f197cb-a77e-4d53-ad21-c10ca6a3bc35 Hyku Commons 2023-05-22 at 12 41 12 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/a730d7f2-a8e5-404f-87b1-dc6b67b6c87a)
![File simpsons_trombone pdf ID 2a085c72-31e4-43f3-b861-7352f028d8fb Hyku Commons 2023-05-22 at 12 41 21 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/60c9bbd6-1482-43fe-8289-3ca3388dcf4c)
![2023-05-22 Hyku upgrade #456 - pdf ID 07f197cb-a77e-4d53-ad21-c10ca6a3bc35 Hyku Commons 2023-05-22 at 12 41 55 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/b27ab641-a1c0-4c22-b987-ddbd1a06d8f8)
![File simpsons_trombone pdf ID 2a085c72-31e4-43f3-b861-7352f028d8fb Hyku Commons 2023-05-22 at 12 42 07 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/503d6fe3-c55c-4176-b078-d4fd69dbca10)

</details>

**Comment by crisr15** [comment]
Approved to close during meeting with ReShare on 8/29
