### ISSUE TITLE
Disable downloads from the UV when Account setting to disable downloads is checked

### ISSUE THREAD

**Issue by labradford** [scientist-softserv/palni-palci#470]
# Story
Part of #460 
When the disable download box is checked, users cannot download files sets from the universal viewer

# Acceptance Criteria

- [ ]  When the account setting for disable downloads is checked, users cannot see the download link in the universal viewer

# Screenshots / Video

<details>
<summary>Download button</summary>

![Screenshot 2023-05-15 at 12 08 04 PM](https://github.com/scientist-softserv/palni-palci/assets/18175797/d7a2cae1-899e-4fb4-99ba-cebe6a84288c)

</details>

# Testing Instructions and Sample Files

- [ ] To test on staging, log into https://reshare.palni-palci-staging.notch8.cloud/ as admin user
- [ ] Open this work show page: https://reshare.palni-palci-staging.notch8.cloud/concern/cdls/7cee6c8f-0fd0-4f0c-88ed-8441fc4d16a7?locale=en
- [ ] Testing this from the proprietary Accounts page
  - [ ] In a new window, navigate to the proprietor Accounts Edit form: https://palni-palci-staging.notch8.cloud/proprietor/accounts/3/edit?locale=en
  - [ ] Testing downloads enabled
    - [ ] Scroll down to the `Account Setting` section. Find the `Allow downloads` checkbox
    - [ ] Check the box to enable downloads. Click the `Save changes` button at the bottom of the form
    - [ ] Navigate back to the work show page. Look at the Universal Viewer (UV). There is a download button in the bottom-left corner (a hard drive with an arrow pointing down ⬇️ ). Verify that when downloads are enabled, you can click this icon and the `Download` button to download the selected work.
  - [ ] Testing downloads disabled
    - [ ] Scroll down to the `Account Setting` section. Find the `Allow downloads` checkbox
    - [ ] Uncheck the box to disable downloads. Click the `Save changes` button at the bottom of the form
    - [ ] Navigate back to the work show page. Look at the Universal Viewer (UV). Verify that when downloads are disabled, there is no Download icon.
- [ ] Testing this from the `Dashboard > Settings > Account` page
  - [ ] In a new window, navigate to the `Dashboard > Settings > Account` form: https://reshare.palni-palci-staging.notch8.cloud/admin/account/edit?locale=en
  - [ ] Testing downloads enabled
    - [ ] Find the `Allow downloads` checkbox
    - [ ] Follow the steps above to test when downloads are enabled
  - [ ] Testing downloads enabled
    - [ ] Find the `Allow downloads` checkbox
    - [ ] Follow the steps above to test when downloads are disabled

<details><summary>Click to expand and see how to test this ticket. Note, at the time of this recording, the disable feature is not working correctly. So in the video, you will still see the download icon in the UV even when downloads are disabled. When this feature is working again, that download icon in the UV will not appear.</summary>

https://github.com/scientist-softserv/palni-palci/assets/29311858/94722cf6-b079-4c34-a11e-f3e35f5aa526

![Image 2023-05-24 Hyku upgrade #456 audio ID 767ba359-5aad-4817-8bac-e0450654d101 Hyku Commons 2023-05-24 at 11 44 00 AM](https://github.com/scientist-softserv/palni-palci/assets/29311858/1c58d94b-c2bc-42eb-9cfc-57f2db553688)
![Image 2023-05-24 Hyku upgrade #456 audio ID 767ba359-5aad-4817-8bac-e0450654d101 Hyku Commons 2023-05-24 at 11 44 10 AM](https://github.com/scientist-softserv/palni-palci/assets/29311858/68e90ca8-22df-4925-9609-e65ce3dff39a)
</details>

# Notes

# Implementation
- create a second config.json that does not include the download link
- Change logic that generates the universal viewer URL to respect admin setting
- Copy both config.json files at deploy (in the package.json) and switch based on the admin setting

**Comment by sephirothkod** [comment]
- https://github.com/scientist-softserv/palni-palci/pull/484

**Comment by DiemBTran** [comment]
**Needs further review:**

tested on:
- tenant setting's page: https://qa-1.palni-palci-staging.notch8.cloud/admin/account/edit.2?locale=en
- image work show page: https://qa-1.palni-palci-staging.notch8.cloud/concern/images/6019e141-a256-47a6-9008-70ff01fd8867?locale=en
- audio work show page: https://qa-1.palni-palci-staging.notch8.cloud/concern/images/7b337a1d-545a-4a59-8f56-05824815b7e8?locale=en

<details><summary>(0:25) Disabling downloads in settings does not make the download button disappear in the UV</summary>

https://github.com/scientist-softserv/palni-palci/assets/29311858/212e6c0d-865f-40a3-9d09-2b44d8aa363a
</details>

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots. If you are disabling downloads for the first time on your tenant, it may take a few minutes for the UV's download button to disappear.

tested on:
- proprietor account settings page: https://palni-palci-staging.notch8.cloud/proprietor/accounts/2/edit?locale=en
- tenant setting's page: https://qa-1.palni-palci-staging.notch8.cloud/admin/account/edit.2?locale=en
- audio work: https://qa-1.palni-palci-staging.notch8.cloud/concern/images/767ba359-5aad-4817-8bac-e0450654d101?locale=en
- image work: https://qa-1.palni-palci-staging.notch8.cloud/concern/etds/f1d4c771-8c7b-4a38-866f-bf89e86fb69a?locale=en

<details><summary>Disabling downloads will hide the download button in the UV</summary>

![Image 2023-05-24 Hyku upgrade #456 audio ID 767ba359-5aad-4817-8bac-e0450654d101 Hyku Commons 2023-05-24 at 11 44 00 AM](https://github.com/scientist-softserv/palni-palci/assets/29311858/1c58d94b-c2bc-42eb-9cfc-57f2db553688)
![Image 2023-05-24 Hyku upgrade #456 audio ID 767ba359-5aad-4817-8bac-e0450654d101 Hyku Commons 2023-05-24 at 11 44 10 AM](https://github.com/scientist-softserv/palni-palci/assets/29311858/68e90ca8-22df-4925-9609-e65ce3dff39a)
![ETD 2023-05-24 Hyku upgrade #456 image ID f1d4c771-8c7b-4a38-866f-bf89e86fb69a Hyku Commons 2023-05-24 at 11 42 45 AM](https://github.com/scientist-softserv/palni-palci/assets/29311858/396f3592-5a8e-440d-8aa1-33f6999a1fd8)
![ETD 2023-05-24 Hyku upgrade #456 image ID f1d4c771-8c7b-4a38-866f-bf89e86fb69a Hyku Commons 2023-05-24 at 11 43 10 AM](https://github.com/scientist-softserv/palni-palci/assets/29311858/f635cd32-b3e5-4564-aede-d965f923119c)
</details>

**Comment by crisr15** [comment]
Approved to close during meeting with ReShare on 8/29
