### ISSUE TITLE
Add test staging environment for ReShare work

### ISSUE THREAD

**Issue by labradford** [scientist-softserv/palni-palci#475]
# Story
Add staging server for the ReShare work
# Acceptance Criteria

- [x] Staging site setup that is not commons-archive

# Testing Instructions and Sample Files

- new staging URL is accessible

# Notes

**Comment by aprilrieger** [comment]
https://palni-palci-staging.notch8.cloud/

**Comment by aprilrieger** [comment]
Main is deployed to staging 	[https://palni-palci-staging.notch8.cloud](https://palni-palci-staging.notch8.cloud)
