### ISSUE TITLE
Convert Contributing Library field to a controlled vocabulary field

### ISSUE THREAD

**Issue by labradford** [scientist-softserv/palni-palci#495]
# ReWork
Convert the form to use a drop down single select box

Contributing library identifier field will be a controlled vocabulary field.
- Client to provide Library and Identifier values

# Acceptance Criteria
- [ ] Contributing Library is a controlled vocabulary field
- [ ] Values match list provided by client

# Testing instructions

- [ ] To test on staging, log into https://reshare.palni-palci-staging.notch8.cloud/ as admin user
- [ ] Navigate to the `Dashboard > Works > New CDL work form`: https://reshare.palni-palci-staging.notch8.cloud/concern/cdls/new?locale=en
- [ ] Fill out the required fields
- [ ] Scroll down to the `Contributing Library` field. Select `Tufts University`
- [ ] Check the deposit agreement and click the `Save` button. This will navigate you to the work show page
- [ ] As an admin user, you should be able to see that selecting `Tufts University` for the `Contributing Library` will display `US-MMET` on the work show page
- [ ] Follow these instructions again, but make the `Contributing Library` field `UMass Chan Medical School` instead.
- [ ] This should display `US-MAWCMUM` on the work show page

<details><summary>Click to expand and see demo of how to test this ticket. Note, during the time of this video recording, the Contributing Library field is not appearing on the work show page for admin users. When this is fixed, you should be able to see that field appear on the work show page</summary>

https://github.com/scientist-softserv/palni-palci/assets/29311858/b250a88b-50ac-46ec-b862-6d6d8328b483

![Cdl cdl ID 507a5217-f0db-44cd-a1c0-68d30ceb9535 Hyku Commons 2023-06-11 at 1 17 11 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/c1c1041f-ff56-4bb2-86fd-dd0c58b2b178)
![Cdl another cdl ID 2b216d19-4a26-4f2d-bb78-4d50edc13d67 Hyku Commons 2023-06-11 at 1 17 19 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/91a6c7bd-4b0a-42cc-b96b-e9c27f73873f)
</details>

**Comment by labradford** [comment]
Use temp data. The controlled vocab should be a library name and a library ID

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

tested on:
- https://test.palni-palci-staging.notch8.cloud/concern/cdls/new?locale=en
- https://test.palni-palci-staging.notch8.cloud/concern/cdls/507a5217-f0db-44cd-a1c0-68d30ceb9535?locale=en
- https://test.palni-palci-staging.notch8.cloud/concern/cdls/2b216d19-4a26-4f2d-bb78-4d50edc13d67?locale=en


<details><summary>Contributing Library field is a controlled vocabulary field. The values display correctly on the work show page.
</summary>

![Cdl   Hyku Commons 2023-06-11 at 1 15 35 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/cf73c69f-e947-486e-bf4f-6a2368b09553)
![Cdl cdl ID 507a5217-f0db-44cd-a1c0-68d30ceb9535 Hyku Commons 2023-06-11 at 1 17 11 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/c1c1041f-ff56-4bb2-86fd-dd0c58b2b178)
![Cdl another cdl ID 2b216d19-4a26-4f2d-bb78-4d50edc13d67 Hyku Commons 2023-06-11 at 1 17 19 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/91a6c7bd-4b0a-42cc-b96b-e9c27f73873f)
</details>

**Comment by sebhammer** [comment]
I'm not seeing the same fields -- does the quinn@indexdata.com account have limited permissions with respect to the sample record?

**Comment by sebhammer** [comment]
Note "ISIL" is not part of the contributor names. It just designates the type of identifier used. Please remove "ISIL" from the contributing library names.

**Comment by crisr15** [comment]
Approved to close during meeting with ReShare on 8/29
