### ISSUE TITLE
Create dynamic configuration for SSO

### ISSUE THREAD

**Issue by labradford** [scientist-softserv/palni-palci#496]
# Story
Create a tab on the admin dashboard where you can enter SSO configuration options

Part of #472 
Part of #463 

# Acceptance criteria
- [ ] As an admin, I can visit a tab in the dashboard where I can enter SSO configuration options, either SAML or OIDC
- [ ] A dynamic form will load the appropriate fields for basic SAML or OIDC configurations

# Testing instructions

- [ ] To test on staging, log into https://reshare.palni-palci-staging.notch8.cloud/ as admin user
- [ ] Navigate to `Dashboard > Settings > Features`: https://reshare.palni-palci-staging.notch8.cloud/admin/features?locale=en
- [ ] Scroll down to `Show identity provider in admin dashboard`. Make sure this is enabled/turned on. This will enable the `Identity Provider` setting for you to test.
- [ ] Navigate to the `Dashboard > Settings > Identity Provider` to enter SSO Configuration.
- [ ] Choose the `Create New` button
  - [ ] Enter SSO configuration options
  - [ ] click the `Save` button
  - [ ] Verify options are saved
- [ ] To create new provider, click the delete button and create a new configuration
  - [ ] Enter SSO configuration options
  - [ ] click the `Save Changes` button
  - [ ] Verify options are saved

### The video tutorial is outdated so use the instructions above
<details><summary>Click to expand and view a video tutorial.</summary>

https://github.com/scientist-softserv/palni-palci/assets/29311858/5e9adb4d-eda6-40f5-923b-f2cd4494e7c3
</details>

# Notes
See code snippet generated by ChatGPT in #463 for a starting point.

This will require adding a new model and a new tab in the dashboard that is viewable by admin users only

We will be using this gem https://github.com/omniauth/omniauth-saml

Use documentation to decide basic SAML and OIDC fields

**Comment by labradford** [comment]
```
config.omniauth :saml,
    allowed_clock_drift: 60,
    assertion_consumer_service_url: "https://#{Settings.multitenancy.root_host}/users/auth/saml/callback",
    attribute_statements: {
      email: ['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress'],
      name: ['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name']
    },
    certificate: File.read(Rails.root.join('provision/logingov.crt')),
    idp_cert_fingerprint: '7D:FD:DC:60:66:21:41:35:81:C5:53:50:D2:BE:A1:E6:17:EF:D4:15',
    idp_sso_target_url: 'https://adfs.dot.gov/adfs/ls/',
    idp_slo_target_url: 'https://adfs.dot.gov/adfs/ls/',
    issuer: "https://#{Settings.multitenancy.root_host}",
    name: :saml,
    name_identifier_format: 'urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified',
    private_key: ENV['PRIVATE_KEY'],
    strategy_class: ::OmniAuth::Strategies::SAML


provider :saml,
    :assertion_consumer_service_url     => "consumer_service_url",
    :sp_entity_id                       => "rails-application",
    :idp_sso_service_url                => "idp_sso_service_url",
    :idp_sso_service_url_runtime_params => {:original_request_param => :mapped_idp_param},
    :idp_cert                           => "-----BEGIN CERTIFICATE-----\n...-----END CERTIFICATE-----",
    :idp_cert_multi                     => {
                                             :signing => ["-----BEGIN CERTIFICATE-----\n...-----END CERTIFICATE-----", "-----BEGIN CERTIFICATE-----\n...-----END CERTIFICATE-----", ...],
                                             :encryption => []
                                           }
    :idp_cert_fingerprint               => "E7:91:B2:E1:...",
    :idp_cert_fingerprint_validator     => lambda { |fingerprint| fingerprint },
    :name_identifier_format
```

**Comment by labradford** [comment]
Fields for the migration:
provider - string
assertion_consumer_service_url - string
idp_cert_fingerprint - string
sp_entity_id - string
name_identifier_format - string

**Comment by labradford** [comment]
https://github.com/heartcombo/devise/wiki/OmniAuth:-Overview

**Comment by DiemBTran** [comment]
**Needs further review:**

tested on:
- new auth provider form: https://qa-1.palni-palci-staging.notch8.cloud/auth_providers/new?locale=en
- edit current auth provider form: https://qa-1.palni-palci-staging.notch8.cloud/auth_providers/3/edit?locale=en

# testing instructions
1. I borrowed test data from screenshots in PR: [dynamic partial rendering for auth provider form](https://github.com/scientist-softserv/palni-palci/pull/509#top) #509
2. Testing instructions: `Verify options are saved`
  1. screen recording: https://share.getcloudapp.com/mXuGjQ4o
  1. It looks like the Save button doesn’t work when you first fill out the form
    1. SAML example doesn’t save at (0:00)
    1. OIDC example doesn’t save at (0:20)
3. But if you stay on the form, switch the provider field (e.g. if you initially chose OIDC and then switch it to SAML),  and refill out the form, the Save button finally works (0:37)

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screen recording.
tested on:
- feature flipper page: https://qa-1.palni-palci-staging.notch8.cloud/admin/features?locale=en
- auth provider page: https://qa-1.palni-palci-staging.notch8.cloud/auth_providers/4/edit?locale=en

<details><summary>Click to expand. Both SAML and OIDC options save in the auth provider page</summary>

https://github.com/scientist-softserv/palni-palci/assets/29311858/9935f6c4-ba68-4daa-a6fa-643b4266a7dd
</details>

**Comment by ndroark** [comment]
I was able to enter information in the SAML authentication provide, and then information saved. After trying to delete the saved information, I received a 500 error and now receive a 500 error when I try to navigate to the Auth Provider tab.

example: https://nic726.commons-archive.org/auth_providers/new?locale=en

**Comment by labradford** [comment]
https://scientist-inc.sentry.io/issues/4326846904/?project=6707374&query=is%3Aunresolved&referrer=issue-stream&stream_index=19

**Comment by labradford** [comment]
When deleting, we didn't reset the current_account.settings['auth_provider'] back to nil so it would redirect to the edit page and the auth_provider didn't exist.

**Comment by labradford** [comment]
@ndroark this is ready for re-testing

**Comment by ndroark** [comment]
I saved new information and then deleted it and got the 500 error again upon deletion. Same tenant: https://nic726.commons-archive.org/auth_providers/new?locale=en

**Comment by labradford** [comment]
dang it, let me try again
