### ISSUE TITLE
Use dynamic credentials to connect to omniauth

### ISSUE THREAD

**Issue by labradford** [scientist-softserv/palni-palci#497]
# Story
Use dynamic credentials to connect to Omniauth

Part of https://github.com/scientist-softserv/palni-palci/issues/472
Part of https://github.com/scientist-softserv/palni-palci/issues/463

# Acceptance Criteria

- [ ] Users can login to omniauth based on the credentials entered in the admin dashboard
- [ ] Users can login via SAML or OIDC

# Screenshots / Video

<details>
<summary></summary>

</details>

# Testing Instructions and Sample Files

- Login via omniauth using the configuration options set up by the tenant admin

# Notes
https://github.com/omniauth/omniauth-saml

Create Account level omniauth config objects
Provide omniauth config base on tenant selected
LOOK AT DOT config/initializers/devise.rb for an example
See code snippet generated by ChatGPT in https://github.com/scientist-softserv/palni-palci/issues/463 for a starting point

Load tenant in Application controller, change the omniauth config

related to #496

**Comment by labradford** [comment]
This will require a SAML and OIDC provider

**Comment by crisr15** [comment]
This is already merged and deployed.  Has been tested by developers but is part of the SSO epic that the client will eventually QA.  Closing this ticket.
