### ISSUE TITLE
Wireframes for Show Page theme

### ISSUE THREAD

**Issue by labradford** [scientist-softserv/palni-palci#506]
Create a wireframe for the ReShare show page theme

Part of #462 

# Acceptance Criteria

- [ ] ReShare show page theme only has UV and Metadata
- [ ] ReShare show page theme will have links back to ReShare for additional search
- [ ] There is no link to the Hyku search results page

**Comment by labradford** [comment]
Crystal sent wireframe to client via email. Waiting for feedback

**Comment by labradford** [comment]
Client has requested a wireframe that shows a book in the UV. They would like to see what the page flipping experience is. I would suggest making use the UV has 2page spread enabled.

**Comment by summer-cook** [comment]
Book instead of video: 

<img width="881" alt="image" src="https://github.com/scientist-softserv/palni-palci/assets/73361970/bd8d3654-2efa-474d-9e6e-b96d4ecd0448">

**Comment by sebhammer** [comment]
For my money this is a good compromise configuration of UV, without the museum-y noise.
