### ISSUE TITLE
Error viewing work show page after Hyku upgrade

### ISSUE THREAD

**Issue by labradford** [scientist-softserv/palni-palci#507]
Error prevents show page from displaying. Seeing this on staging in incognito tab:

https://scientist-inc.sentry.io/issues/4202823718/?project=6707374&query=is%3Aunresolved&referrer=issue-stream&stream_index=0
```
NoMethodError
private method `solr_document' called for #<Hyrax::IiifAv::IiifFileSetPresenter:0x00007f06633f2c88>
Did you mean?  solr_document=
```

# Acceptance Criteria
- [ ] work with a PDF attached renders with the UV on the Work Show page, no error pages

# Testing Instructions
- [ ] Make sure you are not signed in
- [ ] Visit a work with a PDF that has been split into individual pages for viewing in the UV
- [ ] Make sure the page renders without an error page

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

tested on:
- https://qa-1.palni-palci-staging.notch8.cloud/concern/images/2ebaa742-92d4-4565-8e15-0b14c22326cf?locale=en

<details><summary>In incognito mode, I can see a work show page with a split PDF with no error.</summary>

![Image Bulkrax Test ID 2ebaa742-92d4-4565-8e15-0b14c22326cf Hyku Commons 2023-05-31 at 9 04 12 AM](https://github.com/scientist-softserv/palni-palci/assets/29311858/162bcf3a-8e8f-4c18-abc1-d5b1ce2c82a3)
![Image Bulkrax Test ID 2ebaa  2023-05-31 at 9 04 27 AM](https://github.com/scientist-softserv/palni-palci/assets/29311858/dfc3a952-641f-427e-b3e4-b2ca998affbd)
</details>

**Comment by labradford** [comment]
Closing as this is part of the Hyku upgrade ticket and client QA will be done there
