### ISSUE TITLE
Add actual IDs & terms for contributing library vocab

### ISSUE THREAD

**Issue by summer-cook** [scientist-softserv/palni-palci#511]
# Story
Currently contributing library is using placeholder values for the controlled vocab, it needs to be filled in with the list provided by client. 
(currently blocked as we do not have the list)

# Related
- #495 
- https://github.com/scientist-softserv/palni-palci/pull/510

# Acceptance
- [ ] the Contributing Library controlled vocab will be populated by the list provided by the client.

**Comment by labradford** [comment]
https://github.com/scientist-softserv/palni-palci/pull/510

**Comment by sebhammer** [comment]
(I think this issue can be closed as a duplicate)
