### ISSUE TITLE
Improve Collection Name Display

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#518]
# Story

The default display for the collection title on public collection pages does not display the name well when a banner has not been loaded.  Improve the default apperance and add the ability to customize this better. 

# Acceptance Criteria

- [ ] A color-choice option is available for the Collection Title under the Appearance Tab in Settings.  When selecting a new color that is the color the font is displayed in on the public collection pages.  

# Screenshots / Video

<details>
<summary></summary>
<img width="281" alt="Screenshot 2023-06-04 at 1 14 07 PM" src="https://github.com/scientist-softserv/palni-palci/assets/11359350/a77bb23e-fd0b-466a-958c-118e085c2442">

</details>

# Testing Instructions and Sample Files

-

# Notes

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

tested on:
- https://qa-14.commons-archive.org/collections/9a63aaa6-4948-41b3-8728-6ca67e6f9629?locale=en
- https://qa-14.commons-archive.org/admin/appearance?locale=en#color

<details><summary>The default color for the collection title is more clear. You can also change this color in dashboard > appearance > colors</summary>

![Public Collection Hyku Commons 2023-06-09 at 1 28 02 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/c615369a-8abf-4a1a-9b39-e176ff00ff37)
![Show Appearance Hyku Commons 2023-06-09 at 1 28 50 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/714ce5e1-356a-455e-a482-ed9ab44268b8)
![Public Collection Hyku Commons 2023-06-09 at 1 28 40 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/c6f3bba7-fa85-4cd0-aa65-0983c6625213)

</details>
