### ISSUE TITLE
Default Collection Image is showing up in Search results on collections that have a collection image set

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#520]
# Story

When I look in search results I see collections that have the default collection thumbnail, even if I have added a thumbnail to the collection.  When I look at the search results I should see the collection thumbnail that has been selected.  

Can Use University Alumni Publications on the au-archives tenant on production.  

# Acceptance Criteria

- [ ] On search results as a user I see the thumbnail selected or uploaded for an collection instead of the default thumbnail, unless no thumbnail has been set for the collection.  

# Screenshots / Video

<details>
<summary></summary>
Search Results: 
<img width="782" alt="Screenshot 2023-06-04 at 1 33 11 PM" src="https://github.com/scientist-softserv/palni-palci/assets/11359350/d14136e9-69cf-4939-9b43-e1fff01e8b87">

Collection Public Page with Thumbnail: 

</details>
<img width="1099" alt="Screenshot 2023-06-04 at 1 33 27 PM" src="https://github.com/scientist-softserv/palni-palci/assets/11359350/a224a11f-cf00-44b7-8c8a-20bf580c2867">

# Testing Instructions and Sample Files

-

# Notes
This is an issue with the Gallery theme (blacklight)

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

tested on:
- https://qa-14.commons-archive.org/catalog?locale=en&q=&search_field=all_fields&utf8=%E2%9C%93&view=gallery

<details><summary>Gallery view: a collection's collection image correctly appears in the search results when it's updated.</summary>

![Index Catalog Hyku Commons 2023-06-11 at 1 07 43 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/624e4a02-7fb3-420f-87bc-dae1ad8fbaa6)
![Index Catalog Hyku Commons 2023-06-11 at 1 08 18 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/7f28725d-eeae-4f11-90b4-85bb2109e262)
</details>
