### ISSUE TITLE
Public Collection Page - Reduce White Space

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#523]
# Story

The public collection page has a lot of empty white space due to the layout of the page.  As a user I have to scroll past a lot of white space to find the search and the items in the collection.  Reduce the white space or reorganize the page so that there is less white space before scrolling and that it is easier to see what items are in a collection.  

# Acceptance Criteria

- [ ]

# Screenshots / Video

<details>
<summary></summary>
<img width="1118" alt="Screenshot 2023-06-05 at 7 45 50 AM" src="https://github.com/scientist-softserv/palni-palci/assets/11359350/6cd04917-2188-4d9c-b9b6-d019f6723ae6">

![Image](https://github.com/scientist-softserv/palni-palci/assets/37004183/00538214-64db-42b3-8663-47fe93d9d71f)

</details>

# Testing Instructions and Sample Files

-

# Notes

We need more details.

**Comment by labradford** [comment]
Blocked until #541 is approved by the client

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

tested on:
- https://dev.commons-archive.org/collections/6e8a4829-a2a3-4afe-b2fd-03f1c535f42d?locale=en
- figma wireframe: https://www.figma.com/file/mBmGMQCeoBNWhrsZmvCkvh/Pals-Collection-Show-Page?type=design&node-id=0-1

<details><summary>White space was reduced, per wireframe specs.</summary>

![_diem test subcollection Hyku Commons 2023-06-09 at 1 46 03 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/431d28a5-396d-45a9-9d96-6c8fe2993903)
![_diem test subcollection Hyku Commons 2023-06-09 at 1 46 14 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/9cd114a8-ca21-4aa9-b227-420bd5de6ed1)

</details>
