### ISSUE TITLE
Search Results Page - Correct Justification on Facet Listing

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#525]
# Story

On the facets on the search results page, the number of items that are available under a given heading are not justified and move around depending upon the length of the word or phrase from the facet.  

# Acceptance Criteria

- [ ]

# Screenshots / Video

<details>
<summary></summary>
<img width="789" alt="Screenshot 2023-06-05 at 7 57 13 AM" src="https://github.com/scientist-softserv/palni-palci/assets/11359350/477f9f5a-f545-489b-bb29-0bd7eb28a67e">

</details>

# Testing Instructions and Sample Files

-

# Notes

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot.

tested on:
- https://dev.commons-archive.org/catalog?f%5Bcreator_sim%5D%5B%5D=Rev.+Dr.+David+P.+Scaer&locale=en&q=&search_field=all_fields

<details><summary>The numbers are all justified at the end</summary>

![Index Catalog Hyku Commons 2023-06-11 at 12 56 09 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/87a06fd4-68d3-4f64-9ae5-32d5e6c0f8d9)
</details>
