### ISSUE TITLE
Search Results Page - Make the X to remove a filter Red by defaut instead of white

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#526]
# Story

The X to remove filters can be hard to see for many users.  Change the color to make it more clear.  

# Acceptance Criteria

- [ ] X to remove a filter Red by default instead of white 

# Screenshots / Video

<details>
<summary></summary>
<img width="700" alt="Screenshot 2023-06-05 at 8 05 41 AM" src="https://github.com/scientist-softserv/palni-palci/assets/11359350/b81a2559-080c-42fb-832a-1c7d9afca5d1">

</details>

# Testing Instructions and Sample Files

-

# Notes

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot.

tested on:
- https://dev.commons-archive.org/catalog?f%5Bcreator_sim%5D%5B%5D=Rev.+Dr.+David+P.+Scaer&locale=en&q=&search_field=all_fields

<details><summary>The "x" is now red</summary>

![Index Catalog Hyku Commons 2023-06-11 at 12 53 48 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/31b63476-7aaf-4bfa-8fa0-bdfb2fab17a7)
</details>
