### ISSUE TITLE
Search Results Page : Add a color-picker to the Appearance UI for the X to remove a filter

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#527]
# Story

The X to remove a filter can be hard for users to see, but it should still be able to match a tenants theme colors.   Make a color picker for the X in Settings-> Appearance

# Acceptance Criteria

- [ ] As an admin I can choose the color for the X to clear search filters in hyku.  

# Screenshots / Video

<details>
<summary></summary>
<img width="700" alt="Screenshot 2023-06-05 at 8 05 41 AM" src="https://github.com/scientist-softserv/palni-palci/assets/11359350/135b604a-be5b-4752-9b8a-507b66257d2d">

</details>

# Testing Instructions and Sample Files

-

# Notes

**Comment by labradford** [comment]
closing in favor of #526
