### ISSUE TITLE
Public Collection Page - Reduce Collection Thumbnail Image Size

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#528]
# Story

The thumbnail for a collection is really large on the Public Collection Page.  Reduce the size of the image.  

# Acceptance Criteria

- [ ]

# Screenshots / Video

<details>
<summary></summary>
<img width="1118" alt="Screenshot 2023-06-05 at 7 45 50 AM" src="https://github.com/scientist-softserv/palni-palci/assets/11359350/a3605adc-9c93-4b12-8ad6-80f306a31a2b">
</details>

# Testing Instructions and Sample Files

-

# Notes

What is the goal of reducing the image?  Is it that the quality of the thumbnails is not high enough, or does it relate to white space, or a different reason?

**Comment by labradford** [comment]
Blocked until #541 is approved by the client

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot.

tested on:
- https://qa-14.commons-archive.org/collections/9a63aaa6-4948-41b3-8728-6ca67e6f9629?locale=en
- wireframe: https://www.figma.com/file/mBmGMQCeoBNWhrsZmvCkvh/Pals-Collection-Show-Page?type=design&node-id=0-1

<details><summary>The thumbnail has been reduced, per the wireframe specs</summary>

![Public Collection Hyku Commons 2023-06-09 at 1 35 00 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/977b33c7-f1e5-4b44-8860-5e9d08542520)
</details>
