### ISSUE TITLE
Public Collection Page - Move Search Bar for collection up in the visual display

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#529]
# Story

As a user I have to scroll down the page to find the search bar.  I want it to be in a more evident and readily seen spot.  

# Acceptance Criteria

- [ ] The search bar is easier to see without scrolling

# Screenshots / Video

<details>
<summary></summary>
<img width="1118" alt="Screenshot 2023-06-05 at 7 45 50 AM" src="https://github.com/scientist-softserv/palni-palci/assets/11359350/cbe2e7bd-3891-455e-b967-2fb3042bd2ab">

</details>

# Testing Instructions and Sample Files

-

# Notes

**Comment by labradford** [comment]
Blocked until #541 is approved by the client

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

tested on:
- https://dev.commons-archive.org/collections/6e8a4829-a2a3-4afe-b2fd-03f1c535f42d?locale=en

<details><summary>The collection search bar has been moved up</summary>

![_diem test subcollection Hyku Commons 2023-06-09 at 1 46 03 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/c2f573f6-6939-4404-ab90-2a3a29d0ee29)
</details>
