### ISSUE TITLE
Work Show/View Page - Restore functionality of geography field and display field on work page

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#530]
# Story

The Geography field (`based_near`) has been hidden from users as it was not working correctly.  Fix the field and display to users.  

# Acceptance Criteria

- [ ] a user can use the field in the form to search for based near (location) controlled vocabularies
- [ ] works can be saved with a based near (location) field filled in
- [ ] These changes may require of reindex of prod to take effect
- [ ] works that have an existing based near location filled in do not throw an error upon edit after reindexing all works
- [ ] Help text for based near is updated to be more descriptive and actually help the user set up this field if they haven't already 

# Screenshots / Video

<details>
<summary>error that is thrown on save for anything with a based near</summary>

![Image](https://github.com/scientist-softserv/palni-palci/assets/73361970/eb02f109-2074-40be-878c-ac350fe16f66)

</details>

<details>
<summary>The first place in the stack where the error is thrown:</summary>

![Image](https://github.com/scientist-softserv/palni-palci/assets/73361970/f64cb223-ed25-407d-90c3-d0fa83847833)

</details>

<details>
<summary> <s>This is the error that is thrown while trying to search for a Based Near (aka location)</s> this is solved by correctly entering your geonames username & configuring your geonames account.</summary>

![Image](https://github.com/scientist-softserv/palni-palci/assets/73361970/d0eda40d-94ac-4688-b075-4b72972b350c)

</details>

<details>
<summary> <s>In the edit field, it just says loading failed, and has errors in the console</s> this is solved by correctly entering your geonames username & configuring your geonames account.</summary>

![Image](https://github.com/scientist-softserv/palni-palci/assets/73361970/a662609b-b8aa-495a-ac16-4d4131c0fc08)

</details>

# Testing Instructions and Sample Files
In order for this field to work, you will need to configure the geonames in each tenant. Follow the following steps to do this: 

### Steps to Enable Based Near Controlled Vocabulary in Hyku/Hyrax app  
1. Create a free account on [geonames.org](http://geonames.org/)
2. Go to your account settings at https://www.geonames.org/manageaccount and select the option at the bottom to enable free services. 
3. Go into your hyrax/hyku account settings in the dashboard
4. Enter your geonames username in the hyrax account settings
5. You should now be able to see the list of locations in the based near field inside the forms

Then, to test
1. create a work with the location field filled in, make sure it saves.
2. edit that work and make sure it saves

# Notes
_TODO_
- still waiting on client to get back to us about what label they want to use for this field. 

_OLD_
What should the functionality of the geography field be?

This is the `based_near` metadata field. We think this was fixed in Hyrax and changes need to be brought back to HykuCommons

**Comment by DiemBTran** [comment]
**Needs further review:**

tested on:
- https://qa-14.commons-archive.org/concern/images/469ffa4e-e9f6-41ae-a055-3c0135c8ae9c?locale=en
- screen recording: https://share.getcloudapp.com/12ukoD21

1. Location  is not bolded on the work show page :x:
   1. (0:25) in screen recording
2. Editing to remove locations doesn’t work. I created the work with 3 locations. I try to delete 2 of them, but all 3 still show up on the work show page :x:
   1. (0:26) in screen recording
3. Besides that, editing to add locations works :white_check_mark:

**Comment by summer-cook** [comment]
### Softserv QA after Rework
- Location is bolded on the work show page  ✅
- Editing to remove locations still doesn’t work at qa.commonsarchive.org ❌

removing locations works locally, but not once deployed. I suspect the metadata ordering could be causing this, need to touch  base with Jeremy or Kiah on monday

**Comment by summer-cook** [comment]
update: i also hit the same workflow error in the sanitize_params method:



![Image](https://github.com/scientist-softserv/palni-palci/assets/73361970/fac06624-2504-42f7-a95a-80ea69192fbd)

**Comment by summer-cook** [comment]
Most likely blocked by https://github.com/scientist-softserv/palni-palci/issues/448
