### ISSUE TITLE
Home Page- Update the 2019 Samvera copyright date to say 2019-2023 (with 2023 set to the current year).

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#531]
# Story

In. the footer update the 2019 Samvera copyright date to say 2019-2023 (with 2023 set to the current year).

# Acceptance Criteria

- [ ] The home page shows a copyright date of 2019 - 2023
- [ ] The copyright end date auto updates to the current year. 

# Screenshots / Video

<details>
<summary></summary>
<img width="1089" alt="Screenshot 2023-06-05 at 8 58 32 AM" src="https://github.com/scientist-softserv/palni-palci/assets/11359350/29441879-443c-4a54-9eb7-a956894e6d93">

</details>

# Testing Instructions and Sample Files

-

# Notes

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot.

tested on:
- https://qa-14.commons-archive.org/?locale=en

<details><summary>Copyright year is updated</summary>

![Hyku Commons 2023-06-09 at 12 41 39 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/33192d77-c0aa-4576-8c7b-e430d7d562f2)
</details>

**Comment by summer-cook** [comment]
PR to contribute back: https://github.com/scientist-softserv/palni-palci/pull/565
