### ISSUE TITLE
Work Show/View Page - Move analytics button, possibly to below citations? 

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#532]
# Story

The Analytics button was not included in the initial theming and is not intuitive for users.  Move the analytics button on each work show theme view page.  

# Acceptance Criteria

- [ ]

# Screenshots / Video

<details>
<summary></summary>

</details>

# Testing Instructions and Sample Files

-

# Notes
Move Analytics button for logged in and logged out users to underneath the citations button. Update all show page themes

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

tested on:
- https://qa-14.commons-archive.org/concern/generic_works/8963140c-228f-45dc-8aa6-95d7f029a31d?locale=en

<details><summary>The analytics button is now below the citation button for all 3 work show page themes</summary>

![generic work ID 8963140c-228f-45dc-8aa6-95d7f029a31d Hyku Commons 2023-06-09 at 12 46 24 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/1d8ab866-07a3-4875-b7c0-98299b8ba0c5)
![generic work ID 8963140c-228f-45dc-8aa6-95d7f029a31d Hyku Commons 2023-06-09 at 12 47 09 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/d37271d0-6ce4-4dfd-8253-da340917f49a)
![generic work ID 8963140c-228f-45dc-8aa6-95d7f029a31d Hyku Commons 2023-06-09 at 12 46 45 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/9f1968ab-2b86-4971-93c2-26c8b1a68cc3)
</details>
