### ISSUE TITLE
Citations - Add edition numbers for each style guide to Citation generator dropdown

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#534]
# Story
Update to the citations dropdown on the work show page

# Acceptance Criteria

- [ ] MLA Citation should be updated with the edition: MLA citation style (9th ed.)
- [ ] MLA Citation URL should not include http:// or https:// and should be followed with a period.
- [ ] APA Citation should be updated with the edition: APA citation style (7th ed.)
- [ ] APA Citation should be using initials for first and middle names.
- [ ] Chicago Citation should be updated with the edition Chicago citation style (CMOS 17, author-date): 
- [ ] Chicago Citation should end with a period.

# Screenshots / Video

<details>
<summary></summary>

![Image](https://github.com/scientist-softserv/palni-palci/assets/18175797/5e21c96a-89b8-4333-9285-9b957e7758c2)

</details>

# Testing Instructions and Sample Files

- Create or edit a work
- Make sure to add a creator to the work
- View the citations dropdown on the work show page
- Make sure the citations meet the above acceptance criteria 

# Notes
What are the edition numbers we should be putting on each? (See notes below from Nic)
Confirming that this is just adding the edition number and not making multiple editions available

**Comment by labradford** [comment]
@ndroark it looks like we didn't create citations based on a particular edition. This was adapted from code in the ATLA digital library.

> Notch8 will improve functionality of the Citations feature by discarding the nonfunctional EndNote, Zotero, and Mendeley options and implementing the MLA, APA, and Chicago citation functionality (as found in the Atla Digital Library).

From the ATLA project, we were using functionality built into Hyrax, but I cannot find any information as to what Hyrax citations were based on other than "MLA, APA and Chicago"

**Comment by ndroark** [comment]
It looks to me like the following are the edition numbers being used. I have also noted issues with the citations themselves, but I suspect that's out of scope for this sprint. 

MLA citation style (9th ed.): — the citation itself has problems. The URL should not include http:// or https:// (this is unique to MLA), and should be followed with a period. 

APA citation style (7th ed.): — Citation should be pulling initials for first and middle names. 

Chicago citation style (CMOS 17, author-date): — Citation should end with a period.

**Comment by labradford** [comment]
If these changes are not complex we can probably just make the updates while we are in the file.

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot.

tested on:
- https://qa-14.commons-archive.org/concern/generic_works/8963140c-228f-45dc-8aa6-95d7f029a31d?locale=en

<details><summary>requested changes have been made</summary>

![generic work ID 8963140c-228f-45dc-8aa6-95d7f029a31d Hyku Commons 2023-06-09 at 1 13 21 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/cae16150-9de6-41a5-abe8-84bdb0fa3a3a)
</details>
