### ISSUE TITLE
Importer not attaching works to collections

### ISSUE THREAD

**Issue by ndroark** [scientist-softserv/palni-palci#582]
In this importer the collections were all already created, but some give NoMethod errors and some don't in this import https://goshen.hykucommons.org/importers/11?locale=en#collection-entries. (CSV: https://samvera.slack.com/files/U03JWU5Q90U/F05EA0AQUPM/elihochstedlerdiaries_-_sheet1.csv)

In this attempt, the works all import but they don't attach to the collection. The importer also doesn't show an error for the collection, just lists nothing https://goshen.hykucommons.org/importers/18?locale=en#collection-entries (CSV: https://samvera.slack.com/files/U03JWU5Q90U/F05EA484U6N/elihochstedlerimages451_550_-_sheet1.csv)

**Comment by alishaevn** [comment]
### goshen importer 11

the full no method error is "NoMethodError - undefined method 'reindex_extent=' for #<Collection:0x00007fa8fdd82c70>". it happens inside of `#collection_parent_work_child` in the create relationships job.

importer 11 shows 6 collections being imported, no works or file sets. the csv above only lists generic works though, no collections or file sets. I clicked "edit" on the importer and the name of the file that was uploaded is "EliHochstedler**Papers** - Sheet1.csv" the name of the file above is "EliHochstedler**Diaries** - Sheet1.csv". although nic could have named his file differently than the goshen user, it does appear to actually be the incorrect file.

@ndroark can you attach the papers csv that was uploaded in importer 11? I'm assuming there's a "children" column on it. I'd like to see what children it's trying to attach these parent collections to.

<details>
<summary> goshen importer 11 </summary>

![Image](https://github.com/scientist-softserv/palni-palci/assets/29032869/5595c3de-3149-4ebe-8042-c3075bb70fd3)
</details>

**Comment by alishaevn** [comment]
### goshen importer 11
I'm unable to duplicate any issues importing "EliHochstedlerPapers.-.Sheet1.csv".

<details>
<summary>importer and parent collection</summary>

![Image](https://github.com/scientist-softserv/palni-palci/assets/29032869/f40770b2-9095-4000-9a85-edb85b65f143)


![Image](https://github.com/scientist-softserv/palni-palci/assets/29032869/897c02bd-938c-4d04-ab4a-613b335aff27)
</details>

**Comment by alishaevn** [comment]
### goshen importer 18
in the csv from the description comment above, there are only "image" models, no collections. so there would not be any collection entries for this importer. however, the "parents" column does show "EliHochstedlerPapers_Images", which is one of the collections I just imported in importer 11.

looking at the "before" section in the comment above, "EliHochstedlerPapers_Images" is one of the collections that did not import correctly initially. so I would not have expected the relationships between the works and collection to exist. (unless it's one of the collections that already existed?) 

looking at the "EliHochstedlerPapers_Images" collection, I do see 393 works attached. I did a search for a few of the titles in the csv, and they do show in that collection already.

<details>
<summary>example</summary>

https://goshen.hykucommons.org/collections/aa94846a-2229-4151-b35c-957965919f46?utf8=%E2%9C%93&cq=Landscape+shot+of+cabins+in+the+woods&sort=&locale=en

![Image](https://github.com/scientist-softserv/palni-palci/assets/29032869/42f25d7a-30a3-458b-a143-f8a3b8999d71)

![Image](https://github.com/scientist-softserv/palni-palci/assets/29032869/8a86f11b-0009-45f9-88fa-ad1aa2247944)

</details>

**Comment by alishaevn** [comment]
@ndroark bringing this back to your attention.

**Comment by ndroark** [comment]
I'll mark this as closed. I've asked the user who reported it to report if they encounter the issue again.
