### ISSUE TITLE
Spike - Sushi endpoint

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#588]
# Story

For Pitt we will be installing a sushi endpoint to report out data.  This ticket should research the requirements for the sushi endpoint and set up a plan for how to install it.  

# Acceptance Criteria

- [ ] A list of URLs for the SUSHI Enpoint
- [ ] A list of Parameters for each of the reports
- [ ] Ideas for implementation

# Screenshots / Video

<details>
<summary></summary>

</details>

# Testing Instructions and Sample Files

- not end-user testable

# Notes

**Comment by labradford** [comment]
## SUSHI endpoints:

**Base URL:**
https://<TENANT>.hykucommons.org/api/sushi/r51

**Status**:
https://<TENANT>.hykucommons.org/api/sushi/r51/status

**Members**
https://<TENANT>.hykucommons.org/api/sushi/r51/members

**List all available reports:**
https://<TENANT>.hykucommons.org/api/sushi/r51/reports

**Individual reports:**
https://<TENANT>.hykucommons.org/api/sushi/r51/reports/<report_id>

Platform Report: https://<TENANT>.hykucommons.org/api/sushi/r51/reports/pr

Platform Usage Report: https://<TENANT>.hykucommons.org/api/sushi/r51/reports/pr_p1

Item Report: https://<TENANT>.hykucommons.org/api/sushi/r51/reports/ir

**Comment by labradford** [comment]
The COUNTER_SUSHI API - excluding the public path /r51/status MUST be secured using one or more of the following methods:
* Combination of customer ID and requestor ID
* API key assigned to the organization harvesting the usage

Are we going to use API key or customer/requestor ID

**Comment by labradford** [comment]
If global reports are available, the customer ID 0000000000000000 should be used for “The World”. The report should be available to any valid requestor ID and/or API key.
**Does PITT want global reports available to the world?**

**Comment by labradford** [comment]
Query parameters are documented here: https://countermetrics.stoplight.io/docs/counter-sushi-api/yc1o09env0d2a-counter-sushi-api

**Comment by labradford** [comment]
**This is Pseudo code:**

**Routes:**
```
# SUSHI api
  namespace :api, defaults: { format: :json } do
    namespace :sushi do
      namespace :v51 do
        resources :reports, only: [ :index, :show, :members, :status ]     
    end
  end
```
**Controller Methods:**
required params will need validation https://stackoverflow.com/questions/42030271/validate-params-in-rails

```
def index
  @reports = reports.all
end
```
```
def show
  report_id = params[:report_id]
  access_method=params[:access_method]
  data_type= params[:data_type]
  metric_type=params[:metric_type]
end
```
```
def status
  platform = params[:platform] (might not be necessary)
  description
  service_active
  alerts (object with date_time and alert string)
end
```
```
def members
  api_key = params[:api_key]
  platorm = params[:platform]
  requestor_id = params[:requestor_id]
  customer_id = params[:customer_id] (required)
end
```

**Comment by labradford** [comment]
https://github.com/datacite/sashimi

**Comment by ctgraham** [comment]
> Does PITT want global reports available to the world?

Pitt's only use-case is publicly available reports; we do not internally have a need to API-key-restricted or Customer-ID-specific reports.  As always, this question should be sanity checked with PALCI/PALNI for use case outside of Pitt's preference.

**Comment by summer-cook** [comment]
### potential tickets or parts of tickets

- [ ] create basic controller to query sushi endpoints
- [ ] reusable method for base_url
- [ ] set up a place to store customer ID 
- [ ] query method & data normalization for platform report (data normalization just meaning making sure the hash returned from this query aligns with what hyku expects)
- [ ] query method & data normalization for usage report
- [ ] query method & data normalization for item report

questions for lea ann:
do we definitely need status & members reports to be queried for? or were they just listed

**Comment by labradford** [comment]
closing spike as the API is being implemented on report tickets
