### ISSUE TITLE
Spike - Uploading historical metrics

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#589]
# Story

For Pitt we will need a way to upload/ingest/load historical analytics data to be included in the stats.  We need to be able to add data from the last two years and this data should show in the counter reports.  

# Acceptance Criteria

- [ ] Planning for historical metrics results in implementation solution
- [ ] Tickets are made for implementing historical metrics

# Screenshots / Video

<details>
<summary></summary>

</details>

# Testing Instructions and Sample Files

-

# Notes

**Comment by labradford** [comment]
Need a database table for historical data with the following fields:
`work_id | YYYY-MM | total_item_investigations | total_item_requests | unique_item_investigations | unique_item_requests`

When generating the reports, we would check the DB to see if the historical items are present and if they are, we will add them to the report totals

We can have a UI where we upload the items individually

We can use Bulkrax to import historical data while importing the works. 

Possibly use the `has_local_processing` to grab the historical data columns and save them to the database.

**Comment by labradford** [comment]
Per client meeting, historical data will be imported in a one-time process.

They will be uploading works via bulkrax but haven't decided if they are going to use OAI feed or CSV at this point.

**Comment by ctgraham** [comment]
The data storage in eprints irstats2 looks like:
```
mysql> describe irstats2_downloads;  -- requests
+-----------+--------------+------+-----+---------+----------------------------+
| Field     | Type         | Null | Key | Default | Extra                      |
+-----------+--------------+------+-----+---------+----------------------------+
| uid       | int(11)      | NO   | PRI | NULL    |   Unique row id            |
| eprintid  | int(11)      | YES  | MUL | NULL    |    work identifier         |
| datestamp | int(11)      | YES  | MUL | NULL    |   Rollup to day: YYYYMMDD  |
| value     | varchar(255) | YES  | MUL | NULL    |   "views" string literal   |
| count     | int(11)      | YES  |     | NULL    |   accumulated count        |
+-----------+--------------+------+-----+---------+----------------------------+
5 rows in set (0.00 sec)

mysql> describe irstats2_views; -- investigations
+-----------+--------------+------+-----+---------+--------------------------------+
| Field     | Type         | Null | Key | Default | Extra                          |
+-----------+--------------+------+-----+---------+--------------------------------+
| uid       | int(11)      | NO   | PRI | NULL    |   Unique row id                |
| eprintid  | int(11)      | YES  | MUL | NULL    |    work identifier             |
| datestamp | int(11)      | YES  | MUL | NULL    |   Rollup to day: YYYYMMDD      |
| value     | varchar(255) | YES  | MUL | NULL    |   "downloads" string literal   |
| count     | int(11)      | YES  |     | NULL    |   accumulated count            |
+-----------+--------------+------+-----+---------+--------------------------------+
5 rows in set (0.00 sec)
```

I don't think you want a 'total_' vs. 'unique_' column in your data model.  IIRC, the total_item_investigations and total_item_requests is a rollup to the platform (or report), not to the item.

That is, for the whole repository, there were 20 total investigations, with 12 unique items investigations among those 20 investigations.

**Comment by labradford** [comment]
> The data storage in eprints irstats2 looks like:
> 
> ```
> mysql> describe irstats2_downloads;  -- requests
> +-----------+--------------+------+-----+---------+----------------------------+
> | Field     | Type         | Null | Key | Default | Extra                      |
> +-----------+--------------+------+-----+---------+----------------------------+
> | uid       | int(11)      | NO   | PRI | NULL    |   Unique row id            |
> | eprintid  | int(11)      | YES  | MUL | NULL    |    work identifier         |
> | datestamp | int(11)      | YES  | MUL | NULL    |   Rollup to day: YYYYMMDD  |
> | value     | varchar(255) | YES  | MUL | NULL    |   "views" string literal   |
> | count     | int(11)      | YES  |     | NULL    |   accumulated count        |
> +-----------+--------------+------+-----+---------+----------------------------+
> 5 rows in set (0.00 sec)
> 
> mysql> describe irstats2_views; -- investigations
> +-----------+--------------+------+-----+---------+--------------------------------+
> | Field     | Type         | Null | Key | Default | Extra                          |
> +-----------+--------------+------+-----+---------+--------------------------------+
> | uid       | int(11)      | NO   | PRI | NULL    |   Unique row id                |
> | eprintid  | int(11)      | YES  | MUL | NULL    |    work identifier             |
> | datestamp | int(11)      | YES  | MUL | NULL    |   Rollup to day: YYYYMMDD      |
> | value     | varchar(255) | YES  | MUL | NULL    |   "downloads" string literal   |
> | count     | int(11)      | YES  |     | NULL    |   accumulated count            |
> +-----------+--------------+------+-----+---------+--------------------------------+
> 5 rows in set (0.00 sec)
> ```
> 
> I don't think you want a 'total_' vs. 'unique_' column in your data model, at least not associated with a "work". IIRC, the total_item_investigations and total_item_requests is a rollup to the platform (or report), not to the item.
> 
> That is, for the whole repository, there were 20 total investigations, with 12 unique items investigations among those 20 investigations.

Ok, so I think this means we will determine the unique items by grouping by the item id. I was misinterpreting the "unique" views. I thought this meant the visitor was unique.

**Comment by labradford** [comment]
> Need a database table for historical data with the following fields: `work_id | YYYY-MM | total_item_investigations | total_item_requests | unique_item_investigations | unique_item_requests`
> 
> When generating the reports, we would check the DB to see if the historical items are present and if they are, we will add them to the report totals - this would be part of the SUSHI tickets
> 
> We can have a UI where we upload the items individually
> 
> We can use Bulkrax to import historical data while importing the works.
> 
> Possibly use the `has_local_processing` to grab the historical data columns and save them to the database.

The table should include `work_id | YYYY-MM | total_item_investigations | total_item_requests `

We can determine unique investigations and unique requests by counting the unique work_ids for a given date range

**Comment by labradford** [comment]
We will be doing this work in Hyrax.

- generate model in Hyrax to track counter metrics
- resource_type, work_id, worktype, date, total_item_investigations, total_item_requests and any other items from the work that are needed for counter report filters
- We will use the Hyrax::Analytics reporting layer to create reports from the DB
- Cron job to run every 24 hours (with a 24 hour delay) to save the items the DB

**Comment by labradford** [comment]
Tickets for historical data have been made #616 and #617
