### ISSUE TITLE
Spike - Is there a Ruby gem to implement SUSHI API

### ISSUE THREAD

**Issue by labradford** [scientist-softserv/palni-palci#593]
# Story
Research to see if there is a Ruby gem that implements a SUSHI API

# Acceptance Criteria
- [ ] Create a list gems that implement SUSHI API
- [ ] Note if there are no SUSHI API gems

# Testing Instructions
Not end-user testable

# Notes

**Comment by labradford** [comment]
https://github.com/datacite/sashimi

**Comment by labradford** [comment]
I was not able to find any gems except for Sashimi. I'm not sure it will work for us

**Comment by summer-cook** [comment]
@labradford I found this gem from the michigan library: 
https://github.com/mlibrary/swagger_client

this is from its readme: 


### swagger_client
SwaggerClient - the Ruby gem for the COUNTER_SUSHI5_0 API

The COUNTER_SUSHI5_0 API represents a RESTful implementation of SUSHI automation intended to return COUNTER Release 5 reports and snippets of COUNTER usage in JSON format

This SDK is automatically generated by the [Swagger Codegen](https://github.com/swagger-api/swagger-codegen) project:

API version: 1.0.0
Package version: 1.0.0
Build package: io.swagger.codegen.languages.RubyClientCodegen For more information, please visit http://www.niso.org/workrooms/sushi


I need to look into it more to see if its the correct versions. but this could help us potentially?

**Comment by labradford** [comment]
Crystal has reached out to Jose Blanco at UMich for info

**Comment by labradford** [comment]
All of the gems we have discovered are Read counter reports and not create SUSHI endpoints
