### ISSUE TITLE
Spike - Item Report

### ISSUE THREAD

**Issue by labradford** [scientist-softserv/palni-palci#595]
# Story
Create a list of all items that should be included in the Item report and understand how the items align with Hyku
# Acceptance Criteria
- [ ] List all of the items that will be a part of the Item report
- [ ] Each item should have a description of what it is and how it is related to Hyku
# Testing Instructions
Not end user testable
# Notes

This is for the Item Report. Depending on what kind of Host type HykuCommons is, we may need to make need a standard view as well. I is possible that we will need the Journal Article view as well as the standard report

**Comment by labradford** [comment]
https://cop5.projectcounter.org/en/5.1/_downloads/431d952696ed0b5b7dc28f272c903ecc/IR_sample_r51.xlsx

**Comment by labradford** [comment]
**Headers:**
- Report Name => Item Report
- Report ID =>
- Release =>
- Institution Name => Institution Name or Application Name
- Institution ID => ???
- Metric_types =>
- Report_filters =>
- Report_attributes => | separated list of attributes to show (metadata fields)
- Exceptions =>
- Reporting_Period => Begin_Date=YYYY-MM-DD; End_Date=YYYY-MM-DD
- Created => <datetime of report created>
- Created_By => <institution_name???>
- Registry_Record => ???

**Comment by labradford** [comment]
##Item Report Fields
**Mandatory**
- Item => Title?
- Publiser => publisher
- Publisher_ID => blank
- Platform => ??? 
- DOI => Identifier
- Proprietary_ID => Item ID?
- ISBN => Identifier???
- Print_ISSN => blank
- Online_ISSN => blank
- URI => work URL?
- Data_Type => resource_type (listed in header)
- Metric_Type => Total_Item_Requests; Unique_Items_Requests (listed in header)
- Reporting_Period_Total => Count of items for whole reporting period
- Mmm-yyyy => (Jan-2022) Count of monthly items unless Exclude_Monthly_Details
**only if Called for**
- Authors
- Pulication_date
- Article_Version
- Parent and Component items (Not sure if this will apply) *
- YOP => ??? (Year of Publication maybe?)
- Access_Type => examples are Open, Controlled, Free to read
- Access_Method => Regular or TDM


* An example of a parent would be the Journal if the work is a Journal Article. 
* An example of a component would be a Journal Article if the work is a Journal

**Comment by labradford** [comment]
## Item Report Filters

- Data_Type => `<resource_type>`
- YOP => All years (default), a specific year in the format yyyy, or a range of years in the format yyyy-yyyy. Use 0001 for unknown or 9999 for articles in press. COUNTER_SUSHI API allows the specification of multiple years and ranges separated by the vertical pipe (“|”) character
- Access_Type => Controlled; Open; Free_To_Read
- Access_Method => Regular; TDM
- Metric_Type => Total_Item_Investigations; Total_Item_Requests; Unique_Item_Investigations; Unique_Item_Requests; Limit_Exceeded; No_License
- Include_Parent_Details - Default False
- Include_Component_Details - Default False
- Excude_Monthly_Details - Default False

**Comment by labradford** [comment]
sample JSON for the item report is located here: https://countermetrics.stoplight.io/docs/counter-sushi-api/5a6e9f5ddae3e-ir-item-report

**Comment by crisr15** [comment]
What host type would you be / which counter reports do you need?

- Certainly for Pitt's usage both of our tenants would fall in the "Repository" [host type](https://cop5.projectcounter.org/en/5.0.2/03-specifications/03-counter-report-common-attributes-and-elements.html#host-types) (one institutional repository, and one subject repository).  Within broader H4C usage, I wonder if there could be cause to support the "Multimedia" and/or "Data_Repository" host types.  If host types beyond "Repository" were needed, might this be a configurable setting in the "Account" or "Labels"?
- The primary reports of interest are the [PR Platform Master Report](https://cop5.projectcounter.org/en/5.0.2/04-reports/01-platform-reports.html#platform-reports) and the [IR "Item Master Report"](https://cop5.projectcounter.org/en/5.0.2/04-reports/04-item-reports.html#item-reports), as this would be used to share and aggregate usage metrics.  Database Reports and Title reports do not apply to the Repository host type.

Investigation vs. Request:  If the PDF is viewable on the page, should any time the page loads it count as an Investigation or a Request?

- Yes, the view of a PDF on page is considered an Investigation and a Request.  See figure 3.e here: https://cop5.projectcounter.org/en/5.0.2/03-specifications/03-counter-report-common-attributes-and-elements.html#metric-types

Will you have any access restrictions? (do we need to record no_license or limit_exceeded? )

- Pitt does not have nor anticipate subscription-based access controls.  We do have a few dark archive materials which we will need to decide how to handle, but these don't even display in search currently, so it is not possible to get a No_License or Limit_Exceeded condition for these items.  If other H4C clients have license-restricted materials we can chat about that, but our funding and scope would prioritize OA materials.  (N.b. embargoed material access would fall under the "Controlled" access type).

For searches, will you only have one database?  (ie, will we need to support searches on shared search, and in different tenants differently for the counts?)

- I believe metrics should be aggregated to the tenant.  I would interpret a "shared search" implementation across multiple tenants to actually be a different COUNTER Host Type, specifically A&I_Database or Aggregated_Full_Content.  Pitt does not have a specific requirement for implementing shared search across the two planned tenants and does not propose a requirement for reporting these searches.  Searches can be limited to the Searches_Platform metric type.

How would the Data_type attribute be determined on a work? (resource_type?)

- I concur that the Data Type most directly maps to a Resource Type.  How is the list of Resource Types managed?  If static, I hope we can assume that the mapping from Resource Type to Data Type can be set for all tenants, but if tenants can add/edit Resource Types, this may become more complex.  Is there any implication for future changes to the Work Type / Resource Type relationship?

How would sections be determined?  Would it be based off of a metadata field?  Off of relationships?  What would this look like? 

- [Sections](https://cop5.projectcounter.org/en/5.0.2/03-specifications/03-counter-report-common-attributes-and-elements.html#section-types) only apply eJournal, eBook, and similar host types, so I don't believe this will apply to H4C clients unless others are using H4C for journal or ebook publishing.

What access types will you have? How would we determine what was what?

- For [Access Types](https://cop5.projectcounter.org/en/5.0.2/03-specifications/03-counter-report-common-attributes-and-elements.html#access-types), our use case would be entirely within Other_Free_To_Read (and maybe OA_Gold).  If others implement access restrictions, content which requires a login would be categorized as Controlled.  There should be metadata backing to distinguish open resources between Other_Free_To_Read and OA_Gold, but quite honestly, a simpler approach might be to classify all open repository deposits as Other_Free_To_Read, as the OA_Gold version is unlikely to be the deposit.

**Comment by labradford** [comment]
Next step is to document the JSON structure
