### ISSUE TITLE
Reshare show page theme

### ISSUE THREAD

**Issue by summer-cook** [scientist-softserv/palni-palci#599]
# Story
Reshare show page theme wireframe: https://www.figma.com/file/K4o9KLOKXlGwVDi7kVVeB1/Untitled?type=design&node-id=0-1&mode=design&t=08zh0rJz0t2gOI3M-0

# Acceptance Criteria
- [ ] There is a ReShare show page theme that can be selected from the Appearance>Themes settings
- [ ] ReShare show page theme only has UV and Metadata
- [ ] ReShare show page theme will have links back to ReShare for additional search

# Testing Instructions
- [ ] To test on staging, log into https://reshare.palni-palci-staging.notch8.cloud/ as admin user
- [ ] Navigate to the `Dashboard > Settings > Appearance` page here: https://reshare.palni-palci-staging.notch8.cloud/admin/appearance?locale=en
- [ ] Click the `Themes` tab
- [ ] Scroll down to `Show Page Theme`. You will see a dropdown menu and a wireframe beside it. This wireframe changes depending on which option is selected
- [ ] If it's not already selected, select `ReShare Show Page` on the dropdown menu. Click the `Save changes` button
- [ ] In another window, visit this work show page: https://reshare.palni-palci-staging.notch8.cloud/concern/cdls/7cee6c8f-0fd0-4f0c-88ed-8441fc4d16a7?locale=en
- [ ] Compare this work show page to the `ReShare Show Page` wireframe
- [ ] Verify that the work show page is accurate to the wireframe
  - **Note:** For web accessibility reasons, we changed the footer link font for `Samvera` to be darker. There needs to be sufficient contrast between the word `Samvera` and its background color to meet accessibility standards.
<details><summary>Click to expand and see a larger version of the wireframe and what you're comparing it to. </summary>

![reshare_show-df22fb6abca1d97baf325597860a08fde849f67479992a86a95d0ec40c7cbf3a](https://github.com/scientist-softserv/palni-palci/assets/29311858/61b94fb5-2c7b-4bd3-8a68-7bc3d20ed8d0)
![Cdl Description of the Camera Lucida ID 7cee6c8f-0fd0-4f0c-88ed-8441fc4d16a7 Hyku Commons 2023-07-25 at 6 58 28 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/d44c12c0-8639-4602-8e9c-055b7c73da91)

</details>

# Related
EPIC: #462 

# Files

Screenshot to use for the theme's "wireframe" image
![Image](https://github.com/scientist-softserv/palni-palci/assets/73361970/54af3430-eb2c-447d-8a2a-0ffbc1712ff7)

**Comment by summer-cook** [comment]
QA - passed. I can change to the ReShare theme from the appearance styles, and it satisfies the requirements.

**Comment by crisr15** [comment]
Sample work for testing at https://reshare.palni-palci-staging.notch8.cloud/concern/cdls/74ebfc53-ee7c-4dc9-9dd7-693e4d840745

**Comment by crisr15** [comment]
Approved to close during meeting with ReShare on 8/29
