### ISSUE TITLE
Universal viewer theming

### ISSUE THREAD

**Issue by summer-cook** [scientist-softserv/palni-palci#600]
# Summary
Make edits to the UV for reshare show page theme

# Acceptance Criteria
- [ ] There is no download link for the work in the UV
- [ ] UV can show 2 page view

# Testing Instructions
- [ ] To test on staging, log into https://reshare.palni-palci-staging.notch8.cloud as an Admin user
- [ ] Visit this work show page: https://reshare.palni-palci-staging.notch8.cloud/concern/cdls/7cee6c8f-0fd0-4f0c-88ed-8441fc4d16a7?locale=en
- [ ] Verify the Universal Viewer (UV) has its download link removed
<details><summary>Click to expand these screenshots. The first shows a default UV from another app which still has the download link. The second screenshot shows that the ReShare UV has its download link removed</summary>

![Generic Work 2023-07-09 Revert to main branch of IiifPrint #454 ID 94f5d7e5-90d1-44e4-925c-9fc075c6e934 Hyku 2023-07-25 at 6 42 52 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/c09484fa-e228-4708-93e5-79ad9164d424)
![Cdl Description of the Camera Lucida ID 7cee6c8f-0fd0-4f0c-88ed-8441fc4d16a7 Hyku Commons 2023-07-25 at 6 42 44 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/dd45c932-709e-4692-9411-61edb7e27b4b)
</details>

- [ ] The first page of the PDF is the front cover and the last page of the PDF is the back cover of the book. Flip through the pages on the UV by clicking the right arrow. Verify that the UV shows 2 pages at a time for every other set of pages.
<details><summary>Click to expand. This screenshot shows that besides the first and last pages of this book, the other pages display 2 pages at a time</summary>

![Cdl Description of the Camera Lucida ID 7cee6c8f-0fd0-4f0c-88ed-8441fc4d16a7 Hyku Commons 2023-07-25 at 6 41 29 PM](https://github.com/scientist-softserv/palni-palci/assets/29311858/de5d553a-a29c-4285-9763-ffac8357e37b)
</details>

# Related
EPIC: #462

**Comment by summer-cook** [comment]
### Softserv QA: Passed
![screencapture-test-palni-palci-staging-notch8-cloud-concern-generic-works-07368ab5-70ee-43c8-bac0-e7c10673d3dc-2023-07-11-12_16_40](https://github.com/scientist-softserv/palni-palci/assets/73361970/4372735a-3cca-400c-a9a6-da63afaa7dfe)

- [x] Universal viewer does not have download or share links
- [x] UV has the option to show 2 page view for pdfs

**Comment by crisr15** [comment]
Approved to close during meeting with ReShare on 8/29
