### ISSUE TITLE
Create COUNTER metrics tables in Hyrax

### ISSUE THREAD

**Issue by labradford** [scientist-softserv/palni-palci#616]
See more notes on ticket #589 
Part of #586 

## Story
We will need to store counter based metrics into the DB. 

Generate a migration IN HYRAX to add metrics info that we will be using to store data for COUNTER reports

- worktype - string
- resource_type - string
- work_id - string
- date - datetime
- total_item_investigations - integer
- total_item_requests - integer
- any other items from the work that are needed for counter report filters

Required fields: work_id, date

## Acceptance Criteria
- [ ] Hyrax had new table for counter based metrics

## Testing Instructions
- [ ] Test suite will run verifying the new table and fields are valid
- [ ] Test suite will make sure that required fields are validated

## Notes

https://docs.google.com/presentation/d/1lifKiMDmlPqn_0FhAsq6XGLFsBVYX9fiQJ33YpSlhY4/edit?usp=sharing

**Comment by labradford** [comment]
I was thinking it should stay open until the code is merged into Hyrax main branch

**Comment by alishaevn** [comment]
the pipeline for https://github.com/samvera/hyrax/pull/6124 was fixed today and the pr has been merged into hyrax `main`.
