### ISSUE TITLE
Understand JSON Structure for Platform and Item reports

### ISSUE THREAD

**Issue by labradford** [scientist-softserv/palni-palci#622]
## Story
Part of #586 

Platform and Item Reports will be presented via SUSHI API. We need to document the JSON structure of these reports

## Acceptance criteria
- [ ] JSON structure for Item Report is documented
- [ ] JSON structure for Platform Report is documented

## Testing

This is not end user testable

## Notes
Notes on reports available on #595 #594 #615

**Comment by summer-cook** [comment]
I started to fill this out to make it easier to see everything: https://docs.google.com/spreadsheets/d/1DFMR1zEAcxxJ0VB9r_kyCzRteZHZIMMc_quSyH6XzYw/edit#gid=0

**Comment by labradford** [comment]
We want to make sure we are documenting the JSON structure and not the CSV structure.
https://countermetrics.stoplight.io/docs/counter-sushi-api/5a6e9f5ddae3e-ir-item-report
https://countermetrics.stoplight.io/docs/counter-sushi-api/e98e9f5cab5ed-pr-platform-report

**Comment by summer-cook** [comment]
- we need to know what is the JSON structure for the headers
- the two links above - for now we are just doing item report 

- building out a header on a controller action 
- make a sushi controller
- show method 
- build the headers out in the show method
- look at the sushi api endpoint

**Comment by summer-cook** [comment]
Item report example header: 
{"Release":"5.1","Report_ID":"IR","Report_Name":"Item Report","Created":"2023-02-15T09:11:12Z","Created_By":"Sample Publisher","Institution_ID":{"ISNI":["1234123412341234"]},"Institution_Name":"Sample Institution","Registry_Record":"https://registry.projectcounter.org/platform/99999999-9999-9999-9999-999999999999","Report_Attributes":{"Attributes_To_Show":["Authors","Publication_Date","Article_Version","YOP","Access_Type","Access_Method"],"Include_Parent_Details":"True"},"Report_Filters":{"Begin_Date":"2022-01-01","End_Date":"2022-03-31"}}

**Comment by summer-cook** [comment]
Platform report header:

https://countermetrics.stoplight.io/docs/counter-sushi-api/5kpsquvbl2v9j-pr-report-header

**Comment by alishaevn** [comment]
> I started to fill this out to make it easier to see everything: https://docs.google.com/spreadsheets/d/1DFMR1zEAcxxJ0VB9r_kyCzRteZHZIMMc_quSyH6XzYw/edit#gid=0

@summer-cook can you grant me access?
