### ISSUE TITLE
CDL: 3 fields not appearing on work show page for admin users

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/palni-palci#632]
# Story

According to #457, the CDL work type should have 3 metadata fields that only appear to admin on the work show page:

- contributing library
- library catalog identifier
- chronology note

This was working in 2023 May, but stopped they no longer appear on the work show page for admin users.

# Acceptance Criteria

- [ ] These 3 CDL metadata fields appear on the work show page for admin users:
  - [ ] contributing library
  - [ ] library catalog identifier
  - [ ] chronology note

# Screenshots / Video

bugged on:
- Pals Staging: https://qa-14.commons-archive.org/concern/cdls/540f5d9a-04a1-4bfe-8e4d-0796bbe82ea1?locale=en
- ReShare Staging: https://qa-1.palni-palci-staging.notch8.cloud/concern/cdls/23ab3f51-2201-4102-bbf0-0916c0528ae4?locale=en

<details>
<summary>On both Pals staging and ReShare staging, these 3 fields do not appear on the work show page</summary>

![Cdl cdl audio ID 540f5d9a-04a1-4bfe-8e4d-0796bbe82ea1 Hyku Commons 2023-07-27 at 10 39 44 AM](https://github.com/scientist-softserv/palni-palci/assets/29311858/e1e51636-0b56-45e6-bb4c-78e929d63a72)
![Cdl another CDL work type ID 23ab3f51-2201-4102-bbf0-0916c0528ae4 Hyku Commons 2023-07-27 at 10 44 18 AM](https://github.com/scientist-softserv/palni-palci/assets/29311858/4b256074-9bb0-4ec0-877f-2a00db092826)
</details>

# Testing Instructions and Sample Files

- [ ] log in as an admin user
- [ ] create a CDL work type
- [ ] add these 3 fields
  - [ ] contributing library
  - [ ] library catalog identifier
  - [ ] chronology note
- [ ] verify these 3 fields appear on the work show page for admin only

# Notes

**Comment by labradford** [comment]
Might be an issue with the theme

**Comment by crisr15** [comment]
Approved to close during meeting with ReShare on 8/29
