### ISSUE TITLE
Create a sushi controller and build out controller actions for routes

### ISSUE THREAD

**Issue by summer-cook** [scientist-softserv/palni-palci#648]
# story
IR Report Headers: https://countermetrics.stoplight.io/docs/counter-sushi-api/wcjsyuz1v419a-ir-report-header
PR Report Header: https://countermetrics.stoplight.io/docs/counter-sushi-api/5kpsquvbl2v9j-pr-report-header

- the JSON structure for the report headers is outlined in the 2 links above
- make a sushi controller
- build the controller actions and routes

# Related
- #588
- https://github.com/scientist-softserv/palni-palci/issues/622

# acceptance criteria
- [ ] sushi controller has report methods that render json

**Comment by summer-cook** [comment]
Validation tool for counter API: https://stats.redi-bw.de/counter-validation-tool/filelist

We need the following 4 things for a get request: 
Base URL,
Customer ID,
Start date in YYYY-MM or YYYY-MM-DD format
End date in YYYY-MM or YYYY-MM-DD format

**Comment by labradford** [comment]
Not end user testable. Closing in favor of future PRs with real report data
