### ISSUE TITLE
Allow tenant configuration to ignore IIIF Print splitting PDFs consideration

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/palni-palci#658]
There should be one single `flipflop` feature for the following tickets:

- #657
- #658 
- #659 

Testing Instructions can be found here:

- https://github.com/scientist-softserv/palni-palci/pull/666

The three tickets can all be tested in one swoop.

**Comment by crisr15** [comment]
Passes internal QA.  Not end user testable.
