### ISSUE TITLE
Allow tenant configuration to ignore showing PDFs in universal viewer

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/palni-palci#659]
## Summary

We want a feature flipper that turns on and off the PDF processing for iiif print.  This means a tenant can decide if they want PDFs showing in the viewer or not.  

## Testing instructions

Create a PDF work.  Go view it to see that it creates with a thumbnail.  
Go to the Settings, Features, and toggle the use iiif print feature.  
Upload a PDF and allow it to process.  
View the work and confirm you can see the PDF in the viewer.  

## Notes
There should be one single `flipflop` feature for the following tickets:

- #657
- #658 
- #659 

Testing Instructions can be found here:

- https://github.com/scientist-softserv/palni-palci/pull/666

The three tickets can all be tested in one swoop.

**Comment by crisr15** [comment]
This fails SoftServ QA:  

- [ ] When I turn off the feature flipper for iiif print and upload a PDF, the file uploads properly and I do not see derivatives created, but the UV still displays an empty viewer.  
Example work: 
https://dev.commons-archive.org/concern/generic_works/4616118a-f8e4-4ace-bb9f-00f80e9073ae?locale=en

Screenshot: 

![Image](https://github.com/scientist-softserv/palni-palci/assets/11359350/b770b7c4-7ea2-48c8-b09b-8ee25471611c)

**Comment by crisr15** [comment]
Passes internal QA.  Viewer does not show on works that do not have processed files.  



![Image](https://github.com/scientist-softserv/palni-palci/assets/11359350/1416342c-040f-4af2-8fbd-276faaa3dc32)

**Comment by jeremyf** [comment]
Here's a thread reporting that this has been returned to SoftServ for further fixes: https://assaydepot.slack.com/archives/C0313NKC08L/p1692255870043969

Looking at the logs I'm seeing:

```
F, [2023-08-17T15:35:26.309458 #1] FATAL -- : [a0b4305bc8cff4fdb06cd6a1ffc94499] ActionView::Template::Error (private method `solr_document' called for #<Hyrax::IiifAv::IiifFileSetPresenter:0x00007f34682eab00>
Did you mean?  solr_document=):
F, [2023-08-17T15:35:26.309569 #1] FATAL -- : [a0b4305bc8cff4fdb06cd6a1ffc94499]     1: <%# Overridden from Hyrax 3.5.0 - To add extra download restrictions %>
[a0b4305bc8cff4fdb06cd6a1ffc94499]     2: <% if display_media_download_link?(file_set: file_set) && (Site.account.settings[:allow_downloads].nil? || Site.account.settings[:allow_downloads].to_i.nonzero?) %>
[a0b4305bc8cff4fdb06cd6a1ffc94499]     3:   <div>
[a0b4305bc8cff4fdb06cd6a1ffc94499]     4:       <h2 class="sr-only"><%= t('hyrax.file_set.show.downloadable_content.heading') %></h2>
[a0b4305bc8cff4fdb06cd6a1ffc94499]     5:       <%= image_tag thumbnail_url(file_set),
F, [2023-08-17T15:35:26.309598 #1] FATAL -- : [a0b4305bc8cff4fdb06cd6a1ffc94499]   
F, [2023-08-17T15:35:26.309625 #1] FATAL -- : [a0b4305bc8cff4fdb06cd6a1ffc94499] app/helpers/hyrax/file_set_helper.rb:16:in 
```

And here's the exception : https://scientist-inc.sentry.io/issues/4368889816/?environment=production&project=6707374&referrer=project-issue-stream
