### ISSUE TITLE
Make a new user for Debra on the reshare.notch8.cloud testing site.

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/palni-palci#680]
## Summary

ReShare will be doing a demo for their users tomorrow.  Their repository manager needs a user on our repo to be able to demo with.  Make a new admin user for debra@indexdata.com, and then email her the info and password

## Acceptance Criteria

- [ ] Debra is an admin user at email address debra@indexdata.com
- [ ] Debra knows her user login info including password

## Testing Instructions
Not end user testable.  Close ticket once Debra has been emailed her password.

**Comment by labradford** [comment]
Emaild Debra 8/14/23 at 11:15am PT
