### ISSUE TITLE
Update Docker base Image for Fits Performance Improvements

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/palni-palci#690]
# Story

This was discussed in Slack: https://assaydepot.slack.com/archives/C0313NK5NMA/p1692110736739739

> I’m encountering a problem in PALS where the characterize job is apparently
> blocking all things.  I’m wondering how I would determine if it’s docker image
> has been updated with the fixes we’ve applied to Adventist, British Library,
> etc.
>
> The issue was that I started uploading files (PDFs and Images) then noticed
> those were stuck in the sidekiq processes (having already cleared out the two
> jobs that gum everything up) So it was on a branch for conditional IIIF tenant
> work, but there’s no adjustment to the CharacterizeJob, so my assumption is
> that this is a general issue.
>
> In part because it looks like we have JDK 11 instead of JDK 17 in play in the
> Dockerfile.

# Task

> I would recommend stealing the one from utk (look at both dockerfile and
> docker-compose.yaml). It’s been updated recently to be much faster to build
> and pulls from a base that has both arm and amd images.

# Acceptance Criteria

- [ ] The CharacterizeJob does not freeze the workers
- [ ] Our docker build is using JDK 17 instead of JDK 11

# Testing Criteria

Create a work and upload a PDF.  The characterize job should run **and** complete.  Prior to this fix the characterize job would run **and possibly** complete.  While incomplete, it would choke out all resources for other jobs.

**Comment by bkiahstroud** [comment]
If the goal is fits performance improvements, should we look at implementing this change 👇  as part of this ticket? 

- https://github.com/scientist-softserv/nnp/pull/301

**Comment by jeremyf** [comment]
@bkiahstroud the goal is to remove blocking characterize jobs; the fits service doesn't look like it's been merged so I'm not proceeding with that at this moment (as this blocks at least one ticket)

**Comment by labradford** [comment]
this work was completed and merged into main
