### ISSUE TITLE
update the `Hyrax::CounterMetric` table

### ISSUE THREAD

**Issue by alishaevn** [scientist-softserv/palni-palci#695]
# story
as we've been working on the reports, we noticed that there should be a few more fields that we add to the `Hyrax::CounterMetric` table so that we can use them in the reports

# Acceptance Criteria
- the `Hyrax::CounterMetric` table also has the following columns
  - title
  - year_of_publication
  - publisher
  - author
- data has been added to those columns via the [counter metrics data import rake task ](https://github.com/scientist-softserv/palni-palci/blob/main/lib/tasks/counter_metrics.rake)

**Comment by alishaevn** [comment]
@summer-cook moving this back to "ready for dev" since the second acceptance criteria hasn't been met.

**Comment by alishaevn** [comment]
thanks! I just re-ran that flaky spec again. if it doesn't pass this time, I say we merge it anyway since it's blocking #720 and #721.

**Comment by labradford** [comment]
QA - closing. Not end user testable. I successfully ran the migrations and rake task to populate the new fields. Checked the schema on staging and the table has been updated
