### ISSUE TITLE
OAI feed: Add thumbnail link to feed

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#733]
## Summary
They would like the thumbnail link to display in the feed and be mapped to the `thumbnail_url` element

## Testing Instructions
To see the going OAI Feed, visit ...

## Accepted Criteria

- [ ] Thumbnail link is mapped to `thumbnail_url` element
- [ ] This is only available for OAI_hyku feed

**Comment by jillpe** [comment]
Client answers on above questions:

thumbnail_url  / yes, only OAI_hyku unless there is a reason to add it elsewhere

**Comment by ShanaLMoore** [comment]
@laritakr does this involve oai pmh and would be quick to accomplish?

**Comment by laritakr** [comment]
I can add the thumbnail path `/assets/work-ff055336041c3f7d310ad69109eda4a887b16ec501f35afc0a547c4adb97ee72.png` easily, but not the full thumbnail_url including the tenant url. 

Adding the full thumbnail url would involve adding it to the index and reindexing.

**Comment by ShanaLMoore** [comment]
> I can add the thumbnail path... i.e. `/assets/work-ff055336041c3f7d310ad69109eda4a887b16ec501f35afc0a547c4adb97ee72.png` easily, but not the full thumbnail_url including the tenant url.
> 
> Adding the full thumbnail url would involve adding it to the index and reindexing.

We don't have enough time left to tackle this now so moving it to the backlog.

**Comment by ShanaLMoore** [comment]
I'm not familiar enough with outgoing OAI but maybe this endpoint will suffice for testing? 

https://demo.commons-archive.org/catalog/oai?verb=ListRecords&metadataPrefix=oai_hyku

**Comment by ShanaLMoore** [comment]
QA Results: ...

Thumbnail_url is present in the OAI feed: 

<img width="671" alt="image" src="https://github.com/scientist-softserv/palni-palci/assets/10081604/fb73ec66-ace1-4cc0-ac40-f16de55836c6">

- [ ] copying/pasting the path correctly sends the user to the thumbnail image

<img width="960" alt="image" src="https://github.com/scientist-softserv/palni-palci/assets/10081604/97f1f70f-1087-4396-b9e4-1b33c1beff51">

- [ ] This is only available for OAI_hyku feed
