### ISSUE TITLE
Advanced Search: reorder fields to show priority fields first (title, creator, date created, keyword

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#738]
## Summary
They want certain fields to be reordered tot he top of the list in advanced search. Screenshot below shows where list is. Fields to show at top, in priority order:

- title
- creator
- date created
- keyword
- copyright and license
- subject

![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/fb7dc866-043a-40ba-b097-06083a230d29)

# Acceptance Criteria

- [x] Advanced search fields show the following fields at the top and in this order:
  - title
  - creator
  - date created
  - keyword
  - copyright and license
  - subject

**Comment by ShanaLMoore** [comment]
QA RESULTS: ...
