### ISSUE TITLE
Advanced Search. display only priority fields- use "show additional" button to show the remaining feilds

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#739]
## Summary
related to
- #738 

The goal is to only show the fields from #738 and hide the remaining fields behind a `show additional` button.

## Accepted Criteria

- [ ] The following fields are the only ones to show initially on the advanced search page, and the remaining are hidden until the 'show additional' button is clicked
  - title
  - creator
  - date created
  - keyword
  - copyright and license
  - subject

**Comment by ShanaLMoore** [comment]
QA RESULTS: ...


## Accepted Criteria

- [ ] The following fields are the only ones to show initially on the advanced search page, and the remaining are hidden until the 'show additional' button is clicked
  - title
  - creator
  - date created
  - keyword
  - copyright and license
  - subject
