### ISSUE TITLE
Advanced Search. show dropdown menu when controlled vocab is in use

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#740]
## Summary
The goal is to provide a dropdown menu for controlled vocab fields on the advanced search page

## Accepted Criteria

- [ ] As a user, when filling in a field with controlled vocab on the advanced search page, the options are displayed/selectable via a dropdown menu

**Comment by kirkkwang** [comment]
Not sure if this is addressed somewhere else, but which fields have controlled vocabulary?  And what are the options they users should see?

**Comment by ShanaLMoore** [comment]
QA RESULTS: Pass ✅ 

The following fields have drop downs now: 
- [ ] License
- [ ] Accessibility Feature
- [ ] Accessibility Hazard
- [ ] Audience
- [ ] Education Level
- [ ] Learning Resource Type
- [ ] Rights or Rights Statement
- [ ] Type or Resource Type

DEMO: 

Adv search

![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/f1cb6e67-4248-461d-9b23-a588ca1347aa)


SEARCH => Catalog results
![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/0e4a2aaf-280b-4731-8d8d-62e3a1f22c97)
