### ISSUE TITLE
Improve Resource Type list -- add a few new terms

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#741]
## Summary
The goal is to add more resource types to the list in the creating and editing a work page, while keeping the list in alphabetical order.

![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/611e67db-6b62-4ee8-b0b9-edb0b9087c17)

## Accepted Criteria

Creating a Work Form
- [ ] Resource Type list contains the original list + the following:
  - "Newspaper"
  - "Preprint"
  - "Realia"
- [ ] Resource Type list is in alphabetical order (a-z)

Editing a Work Form
- [ ] Resource Type list contains the original list + the following:
  - "Newspaper"
  - "Preprint"
  - "Realia"
- [ ] Resource Type list is in alphabetical order (a-z)

## Testing Criteria
Creating a Work Form
- [ ] Resource Type list contains the original list + the following:
  - "Newspaper"
  - "Preprint"
  - "Realia"
- [ ] Resource Type list is in alphabetical order (a-z)

Editing a Work Form
- [ ] Resource Type list contains the original list + the following:
  - "Newspaper"
  - "Preprint"
  - "Realia"
- [ ] Resource Type list is in alphabetical order (a-z)

**Comment by jillpe** [comment]
SoftServ QA:

<details><summary>Creating a Work Form</summary>
 Resource Type list contains the original list + the following:
"Newspaper"
"Preprint"
"Realia"
 Resource Type list is in alphabetical order (a-z)


</details>

<details><summary>Editing a Work Form</summary>

 Resource Type list contains the original list + the following:
"Newspaper"
"Preprint"
"Realia"
 Resource Type list is in alphabetical order (a-z)

</details>

**Comment by ndroark** [comment]
Not sure where it was dropped, but the term "text" should be a resource type as well https://docs.google.com/spreadsheets/d/1iIzTikHdXKo8u1_Re_CuE_LhnI0o-62WqYdKYGAt1BE/edit#gid=519636467

**Comment by ShanaLMoore** [comment]
QA RESULTS: Pass ✅ 

<details>
  <summary> DEMO </summary>


![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/27cfaaa5-713a-4919-94ae-439744edbc02)



</details> 

Creating a Work Form
- [ ] Resource Type list contains the original list + the following:
  - "Newspaper"
  - "Preprint"
  - "Realia"
  - "Term"
- [ ] Resource Type list is in alphabetical order (a-z)


Editing a Work Form
- [ ] Resource Type list contains the original list + the following:
  - "Newspaper"
  - "Preprint"
  - "Realia"
  - "Term"
- [ ] Resource Type list is in alphabetical order (a-z)
