### ISSUE TITLE
Ability to control menu button color through appearance settings

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#742]
## Summary
Ability to control the color of the navbar buttons on the homepage, `Home`, `About`, `Help`, and `Contact`, through the `colors` tab in the `Appearance` page of the Dashboard. 

<details><summary>Buttons to be able to be edited</summary>

![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/aedda2c1-620f-47cc-8b0b-e1eb74ee40ab)

</details>

<details><summary>Location of where to be able to edit</summary>

![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/e420a5fc-3b2c-4f86-80b8-42f10acf65c9)

</details>

## Accepted Criteria

- [ ] `Colors` tab on the `Appearance` page in the Dashboard gives the ability to edit the colors of the following buttons:
- navbar buttons on home page
  - `Home`
  - `About`
  - `Help` 
  - `Contact`

## Testing Instructions
- Navigate to the `Colors` tab of the `Appearance` Section in the dashboard
  - [ ] The color chosen for `Navbar link background color` is the color the `Home`, `About`, `Help`, and `Contact` buttons on the home page displays
    - Note: the button that coincides with the page you are on will be darker than the others (i.e. if you are on the Home page, the `home` page button will be darker)
  - [ ] The color chosen for the `Navbar background color` is the color the Home page navbar displays

**Comment by kirkkwang** [comment]
- [ ] Correct the `Navbar background color` to `Navbar background active color`
- [ ] Add a true `Navbar background color`

**Comment by jillpe** [comment]
SoftServ QA: Pass ✅ 

<details><summary>Navbar link background color</summary>


![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/1968341a-70ea-448e-a733-1bb234de4553)



![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/7d06b88d-6a76-434b-9da3-7d376697ede2)


<details>

<details><summary>Navbar background color</summary>


![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/3ce45d63-357c-4f05-96cd-0a3ec8c04a1e)



![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/8e4b9905-d8f4-403f-adc1-099c4571aab4)


<details>
