### ISSUE TITLE
Sort subcollections A-Z on collection pages

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#744]
## Summary
They would like the subcollections that are on a collection show page, to display in A-Z order

![image](https://github.com/scientist-softserv/palni-palci/assets/10081604/cf6c7222-704b-45df-abd7-4a8a00a925a6)

## Accepted Criteria

- [ ] Subcollections on a collection show page display A-Z

## Testing Instructions
- Navigate to a collection's show page
  - [ ] The subcollections display, by default, in A-Z order

**Comment by aahurford** [comment]
![image](https://github.com/scientist-softserv/palni-palci/assets/117950472/7936027d-e199-4c3b-ad94-b4c4ff9f8022)
https://palni.hykucommons.org/collections/97ba78b3-9deb-408f-8735-bf1df5c42792?locale=en

**Comment by jillpe** [comment]
SoftServ QA: Pass ✅ 

[Collection URL](https://dev.commons-archive.org/collections/fb3f5068-3b66-41a8-bb32-5b38c370aaa8?q=744)

<details><summary>Screenshots</summary>


![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/c02fbc70-0a6d-4f70-9f3a-b6f1d14c4125)


</details>
