### ISSUE TITLE
Enhance banner image customization

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#746]
## Summary
Pals would like to be able to preview the banner customization before saving, as well as be able to select the positioning and cropping of the image **after** it is uploaded.

## Accepted Criteria

- [ ] As a user, I can preview my banner customization before saving it
- [ ] As a user, after an image is uploaded for the banner image customization, I can adjust the positioning and cropping

## Testing Instructions

- From the admin dashboard, navigate to the [banner image tab](https://demo.commons-archive.org/admin/appearance?locale=en#banner_image) in the appearance settings. 
- Import a banner image. Sample - 

![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/0931c738-694d-45ea-922e-7d20c83892d1)

- [ ] a user should be able to crop the image before saving

- Save the banner image and visit the home page.
- The home page's banner should update to the imported/cropped banner photo 
- 
**- NOTE: The home page's banner is dynamic/responsive so it may not portray exact dimensions as cropped. Nic is ok with this for now as it still reduces the efforts for the users.** 

- Navigate back to the banner image settings. A user should be able to click crop to make adjustments to the previously cropped image. **NOTE: if a user wants to recrop from the original image they will have to reupload - Nic is OK w this for now.** 
- Check the homepage banner for changes

- Navigate back to the banner image settings. Click the remove button. 
- [ ] the banner image should go back to the default. Confirm your uploaded image is no longer seen on the homepage banner.

## Screenshots

![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/834787a0-8e66-4db3-8fd8-9d640588a80d)

**Comment by ShanaLMoore** [comment]
# DEV NOTES/Resources

https://stackoverflow.com/questions/21840899/preview-image-before-upload-with-carrierwave

**Comment by ShanaLMoore** [comment]
# QA Results: ❌ 

Tested on: https://demo.commons-archive.org/?locale=en

Initially the homepage updated to what I selected. However, when I re upload/crop and click save, the homepage banner doesn't appear to be updating. demo: https://share.zight.com/rRumGZYe

Not a cause for kickback but I'd argue crop button should not be displayed on the initial upload (since it's activated automatically).

**Comment by ShanaLMoore** [comment]
I see the issue. silly mistake. Closing this PR

**Comment by ShanaLMoore** [comment]
# QA RESULTS: Pass ✅ ⚠️ 

The banner is slow to save so it kind of feels like it wasn't working, but it saved. It may be a good idea to add a loading spinner to let the user know it's doing something, but holding off until the client requests this in a separate ticket. 

Tested on: https://dev.commons-archive.org/admin/appearance?locale=en#banner_image

![image](https://github.com/scientist-softserv/palni-palci/assets/10081604/db747752-526c-4822-9e5f-701c92f26614)

![image](https://github.com/scientist-softserv/palni-palci/assets/10081604/d58e8f91-9180-46af-8169-ee050a0b4333)
