### ISSUE TITLE
Add institutional visibility in importer

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#747]
## Summary
Pals would like `Institutional` to be added as an option for the `Visibility` field on both CSV and Bagit importers

<details><summary>Screenshots</summary>

![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/3bfe835c-a3a3-4fa6-bb2e-5783f0ef214a)

![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/45c78091-631f-4fd7-b067-2ca99edadbaa)

</details>

## Accepted Criteria

CSV Importer
- [ ] `Private`, `Public`, and `Institutional` are the 'Visibility' field options

Bagit Importer
- [ ] `Private`, `Public`, and `Institutional` are the 'Visibility' field options

## Testing Instructions
- Create a new import
  - Set the Parser to CSV
    - [ ] Visiblity field has 3 options: `Public`, Private`, or `Institutional`
    - [ ] All options can be selected and saved
  - Set the Parser to Bagit
    - [ ] Visiblity field has 3 options: `Public`, Private`, or `Institutional`
    - [ ] All options can be selected and saved

**Comment by kirkkwang** [comment]
According to this [code](https://github.com/samvera-labs/bulkrax/blob/da5c83bd6c53951eecae20f78354480a538597a4/app/parsers/bulkrax/application_parser.rb#L144-L151) in Bulkrax, you can set `visibility` column with `restricted`, `open`, or `authenticated`.

`restricted` => Private
`open` => Public
`authenticated` => Institution

**Comment by jillpe** [comment]
SoftServ QA: Pass ✅ 

<details><summary>CSV ✅ </summary>


![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/3de085df-0449-440f-be2a-ad006e788a37)


</details>

<details><summary>Bagit ✅ </summary>


![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/f5c68959-f3ee-42e9-8b41-516ad75e87bf)


</details>
