### ISSUE TITLE
Ability to sort works and collections on dashboard

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#748]
## Summary
Pals would like the ability to sort works and collections on the dashboard. They would like to be able to sort both by:
- date uploaded
- date modified
- date created
- depositor (a-z)
- creator (a-z)

<details><summary>Screenshots</summary>

![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/5b3265e4-987a-41df-bc6c-98aeee366d29)

![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/1a50f565-a4cd-45a1-8fcd-3a8a17fbb7eb)

</details>

## Accepted Criteria

- [ ] As a user, I can sort works on the 'Works' dashboard page by ~date uploaded~, `date modified`, `date created`, `depositor (a-z)`, and `creator (a-z)`
- [ ] As a user, I can sort collections on the 'Collections' dashboard page by `date uploaded`, `date modified`, `date created`, `depositor (a-z)`, and `creator (a-z)`

**Comment by jillpe** [comment]
Do you have a preference on where the sort button should go? Or do you want a developer to decide?

**Comment by ndroark** [comment]
I think the space between Show # per page and Search makes sense, if that's an option

**Comment by ShanaLMoore** [comment]
# QA RESULTS: 

Tested on: https://dev.commons-archive.org/dashboard/my/collections?locale=en

## COLLECTIONS 
- [X] As a user, I can sort collections on the 'Collections' dashboard page by date uploaded, date modified, date created, depositor (a-z), and creator (a-z)



Demo: https://share.zight.com/o0uKe9nO




![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/eec25fe2-0359-4602-8978-0a893fd988a4)





## WORKS
- [X] As a user, I can sort works on the 'Works' dashboard page by date uploaded, date modified, date created, depositor (a-z), and creator (a-z)


DEMO: https://share.zight.com/Wnupx9Zl




![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/2ee3d7b5-d841-4558-a999-ca0b70bfaefb)

**Comment by ShanaLMoore** [comment]
Why is date uploaded missing from the collection dashboard? 

Per @kirkkwang - 

``` ruby
        # Collections don't seem to have a date_uploaded_dtsi nor date_modified_dtsi
        # we can at least use the system_modified_dtsi instead of date_modified_dtsi
        # but we will omit date_uploaded_dtsi
```

ref: https://github.com/scientist-softserv/palni-palci/blob/main/app/helpers/blacklight/configuration_helper_behavior_decorator.rb#L23-L25

**Comment by ShanaLMoore** [comment]
Requires re-indexing prod. Hold on client verification until that task is complete.

**Comment by ndroark** [comment]
Sort by Depositor and Creator aren't working in production tenants I've tested. Depositor sorts by title, and Creator seems to sort by some combination of file type and title.

**Comment by ShanaLMoore** [comment]
Apologies for dropping the ball with removing the ON HOLD label. According to [this comment](https://assaydepot.slack.com/archives/C0313NKC08L/p1697757941093479?thread_ts=1697752643.158689&cid=C0313NKC08L) the prod data was re-indexed. So I'll take a few mins to look into what may be going on. @ndroark

**Comment by kirkkwang** [comment]
@ShanaLMoore I don't think we ever did a reindex on prod did we?

**Comment by laritakr** [comment]
> @ShanaLMoore I don't think we ever did a reindex on prod did we?

Shana said we did reindex prod, and it's also not working right on staging.

**Comment by ShanaLMoore** [comment]
@ndroark Could you provide a screenshot or url, that shows the sort behaving incorrectly? Could you also specify your expectation in comparison to what your screenshot shows?
We could huddle too if you are available. We just want to make sure we understand expectations vs behaviors in order to fix whatever issue there may be.

**Comment by ShanaLMoore** [comment]
> @ndroark Could you provide a screenshot or url, that shows the sort behaving incorrectly? Could you also specify your expectation in comparison to what your screenshot shows? We could huddle too if you are available. We just want to make sure we understand expectations vs behaviors in order to fix whatever issue there may be.

Update after a huddle meeting: Creator is OK but depositor is not. Depositor had a typo in the app indexer so we will fix this, redeploy and reindex prod to resolve this.

**Comment by ShanaLMoore** [comment]
deployed hotfix to prod. 

Don't client verify this until the reindex has been completed.

**Comment by ShanaLMoore** [comment]
Reindex complete ✅

**Comment by ShanaLMoore** [comment]
Reindex complete ✅

@kirkkwang  to review work in prod then let @ndroark know to do the same if everything functions ok.

**Comment by ShanaLMoore** [comment]
@laritakr confirmed that the misspelling of the solr property depositor has been corrected. 

cc @ndroark this is ready for re review
