### ISSUE TITLE
Add image caching for faster page loads

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#755]
## Summary
This would be IIIF serverless caching. This has been done in Adventist and UTK. Examples:

[v2](https://wtchtwt5fcxnxj5guruoadqpwm0uvgjl.lambda-url.us-west-2.on.aws/iiif/2/001c304611e6d980d9af7a99c7bc3a4f2d58bfa4/full/600,/0/default.jpg) 
[v3](https://wtchtwt5fcxnxj5guruoadqpwm0uvgjl.lambda-url.us-west-2.on.aws/iiif/3/001c304611e6d980d9af7a99c7bc3a4f2d58bfa4/full/600,/0/default.jpg)

To Do:
- Pyramidal tiffs
- IIIF print
- Turning on caching properly for manifests (Trinity work)

## Acceptance Criteria

- [ ] IIIF serverless caching has been enabled

**Comment by orangewolf** [comment]
I did both serverless caching and the manifest caching we did for Trinity.
