### ISSUE TITLE
Extra Importer/Exporter buttons populating on staging dashboard

### ISSUE THREAD

**Issue by ndroark** [scientist-softserv/palni-palci#767]
Something I newly noticed in staging is that Importers and Exporters are being listed twice in the dashboard sidebar, e.g. https://nic2.commons-archive.org/dashboard?locale=en

![Image](https://user-images.githubusercontent.com/117871943/264745261-58eb3195-9847-4b8a-9def-c332285c6247.png)

**Comment by ShanaLMoore** [comment]
<img width="158" alt="image" src="https://github.com/scientist-softserv/palni-palci/assets/10081604/2d1c0373-4a71-4f83-8010-79795860e222">
