### ISSUE TITLE
An intuitive placement of a download button or link near the viewer, in addition to the file manager at the bottom of the page

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#774]
# Summary 
A download button and file manager is near the viewer in an intuitive spot for the user. 

- the file manager button is already near the viewer by default so we did not change this behavior. 
- a download button has been added. The download button will only display when the flag on the files tab is selected.

# Acceptance Criteria
- [ ] A download button and file manager is near the viewer in an intuitive spot for the user

# Testing Instructions
- Create or open the show page of a work with **multiple** PDFs attached to it
**NOTE: the File Manager button will not get displayed if there is only one file attached** 
**PS. No work was done on the file manager button. It is currently displaying default behavior.**

- Default Theme
  - [ ] Download button is in an intuitive spot
  - [ ] File manager is in an intuitive spot
- Cultural Theme
  - [ ] Download button is in an intuitive spot
  - [ ] File manager is in an intuitive spot
- Scholarly Theme
  - [ ] Download button is in an intuitive spot
  - [ ] File manager is in an intuitive spot
- ReShare Theme
  - [ ] Download button is in an intuitive spot
  - [ ] File manager is in an intuitive spot

**Comment by kirkkwang** [comment]
Possible solution can be adding a download button near the top so it hopefully won't interfere much with themes.  The only other question is if we always show the download button or is it something like, when the viewer shows, show the download button, when it's just a thumbnail, don't show the download button?

<img width="1192" alt="image" src="https://github.com/scientist-softserv/palni-palci/assets/19597776/c926888e-bcb1-4c0e-ae12-0c950ae88432">

**Comment by ShanaLMoore** [comment]
QA RESULTS: ...

**Comment by kirkkwang** [comment]
## Cultural Theme

<details><summary>Pass ✅</summary>



![Image](https://github.com/scientist-softserv/palni-palci/assets/19597776/57d3765c-b62f-4d3d-91db-d7670dc677c8)

</details>

**Comment by ShanaLMoore** [comment]
Requires reindexing prod
