### ISSUE TITLE
Customizable downloading options on a work by work basis—administrators should be able to set a pdf to be embedded in the viewer while disabling the option to download the file

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#776]
# Summary 
Administrators have the ability to configure a PDF to show in the viewer but not be able to be downloaded

# Acceptance Criteria
- [ ] As and admin, I can configure a PDF to show in the viewer but not be able to be downloaded

**Comment by kirkkwang** [comment]
Possible solution could be setting a flag on the work to check if this pdf is downloadable or not?

**Comment by jillpe** [comment]
Closed- covered in #773 and #125
