### ISSUE TITLE
Issue with adding collections as subcollections

### ISSUE THREAD

**Issue by ndroark** [scientist-softserv/palni-palci#783]
## Summary
I am trying to add collections to existing collections (while logged in as a superadmin), but after I select the subcollection from the dropdown list, I get this error message. Occuring in franklin.hykucommons.org.

![Image](https://user-images.githubusercontent.com/117871943/267379252-095de82d-90d5-43e2-885e-cd374b7e3036.png)

## Acceptance Criteria
- [ ] Any user with collection manager level permissions can add collections to existing collections through the dashboard
- [ ] This code has been contributed to the double combo or main branch (the longest running branch). Note that this rake task doesn't work as is on hyku since hyrax is v5+. 

# NOTE

This ticket was unrelated to permissions. If collection manager permissions continue, this should be a new ticket.

# Testing

Verify that the 3 affected collections in Franklin tenant now show the full list of valid collections to be added as subcollections. The 3 affected collections were [College Presidents](https://franklin.hykucommons.org/dashboard/collections/3ced02ba-d2dd-49fe-af48-42207f013ce4?locale=en), [Franklin College in the News](https://franklin.hykucommons.org/dashboard/collections/0c3005c0-f126-4b7a-ac77-20a2b725f75b?locale=en), and [Lasting Legacies](https://franklin.hykucommons.org/dashboard/collections/39e102cc-551c-4d41-8f26-2d87190ac39f?locale=en).

To test in staging, you would have to find an old collection (prior to 2024), create a new collection, and verify that subcollections can be added to each other.

**Comment by bkiahstroud** [comment]
@ndroark can you confirm whether or not this is still an issue? 

Based on the screenshot, the intended parent collection is `Lasting Legacies: Franklin College 'Spirit of Community' Collection`, and the intended subcollection is `Judi Warren '80`. 

Looking at the [parent collection now](https://franklin.hykucommons.org/dashboard/collections/39e102cc-551c-4d41-8f26-2d87190ac39f?locale=en), `Judi Warren '80` is a subcollection:  

<details><summary>Screenshot 1</summary>

<img width="1101" alt="image" src="https://github.com/scientist-softserv/palni-palci/assets/32469930/614d178c-ba63-419a-b4ba-ddcf0bfa5d38">

</details>

Though I can tell from the URL that the Collection ID is different, maybe it was recreated? 

I created two test collections in the franklin tenant and was able to add one as a subcollection to the other: 

<details><summary>Screenshot 2</summary>

<img width="1344" alt="image" src="https://github.com/scientist-softserv/palni-palci/assets/32469930/17982478-42db-4785-ad11-f188ab4478d7">

</details>

**Comment by ndroark** [comment]
The issue seems to still be present with at least certain collections in the tenant. For instance, this collection (https://franklin.hykucommons.org/dashboard/collections/39e102cc-551c-4d41-8f26-2d87190ac39f?locale=en) only lists two other collections as available to add to it, and doesn't show up in the list for other collections to be added to. 

![image](https://github.com/scientist-softserv/palni-palci/assets/117871943/f76ed638-b55c-429d-9577-8e6a28569d85)

**Comment by ndroark** [comment]
This function should be not be limited to superadmins, any user with collection manager level permissions should be able to do this. The specific subcollections in the comments above in the Franklin tenant are the main area where problems have been observed.

**Comment by jillpe** [comment]
This might be associated with the pagination bug in adventist

**Comment by ShanaLMoore** [comment]
possible this may be fixed when upgrading. 

related tickets (should've been contributed back)

https://github.com/samvera/hyku/pull/2024

https://github.com/scientist-softserv/adventist-dl/issues/622

**Comment by jeremyf** [comment]
Things to look at:

https://github.com/samvera/hyrax/blob/e9141b81865a37fbc80ab88b44825a51534e6c48/app/controllers/hyrax/my/works_controller.rb#L32-L36

And we need to consider applying the cloning the of the object to the three other locations.

```ruby
❯ rg "Hyrax::CollectionsService.new"
app/controllers/concerns/hyrax/works_controller_behavior.rb
173:      Hyrax::CollectionsService.new(self)

app/controllers/hyrax/my/works_controller.rb
35:        Hyrax::CollectionsService.new(cloned)

app/controllers/hyrax/dashboard/collections_controller.rb
387:        Hyrax::CollectionsService.new(self).search_results(:edit)

app/controllers/hyrax/homepage_controller.rb
25:    Hyrax::CollectionsService.new(self).search_results do |builder|
```

**Comment by laritakr** [comment]
There seem to be 3 collections in the franklin repo that are affected: 
- https://franklin.hykucommons.org/dashboard/collections/39e102cc-551c-4d41-8f26-2d87190ac39f?locale=en
- https://franklin.hykucommons.org/dashboard/collections/0c3005c0-f126-4b7a-ac77-20a2b725f75b?locale=en
- https://franklin.hykucommons.org/dashboard/collections/3ced02ba-d2dd-49fe-af48-42207f013ce4?locale=en

These 3 can be added to each other, but are not options for any other collections. So far I have found no reason for this behavior and have been unable to duplicate the behavior locally. 

These 3 collections seem to have been the first 3 collections created in the franklin tenant. Is it possible something changed in the code prior to the 4th collection being created in March of 2023?

![Image](https://github.com/scientist-softserv/palni-palci/assets/17851674/ea9f95da-23b6-495f-b0d2-0f4ab7f02afe)

**Comment by laritakr** [comment]
✅ Passes QA

- New collection: https://demo.commons-archive.org/collections/bd47476a-ab14-4688-a82d-b29574ea4a8b?locale=en
- Ran code from rake task to update collections on all tenants in dev environment (rake task threw faraday errors but code with a few revisions to handle invalid tenants worked from within the rails console.) Now that the collections have been migrated, the rake task is only for documentation purposes. 
- Older collections now show in the list of available subcollections

<details>
<summary>Before data update</summary>

![Image](https://github.com/scientist-softserv/palni-palci/assets/17851674/b13dc036-f0ee-4346-a253-0295a0b58f08)

</details>


<details>
<summary>After data update</summary>

![Image](https://github.com/scientist-softserv/palni-palci/assets/17851674/f0e712e9-cfe9-498b-ac13-c1579435ee4d)

</details>
