### ISSUE TITLE
By default sort collection works by A-Z on collection page rather than relevance

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/palni-palci#800]
# Summary

From a collection show page, if it has works by default sort_by title (A-Z) should be activated. Default means that whenever we visit the page, sort_by: title (A-Z) is chosen/displayed, instead of sort_by relevance.

**NOTE: The original ticket #743 was misleading. It had the wrong screenshot, pointing to the featured collections section. So the devs worked on that section instead, hince the creation of this ticket.**  

## Accepted Criteria

- [ ] Works on the public view of the collection page are by default, sorted A-Z

## Testing Instructions

- [ ] Login in as an admin user
- [ ] Click on Collections. Find a [collection](https://demo.commons-archive.org/collections/687a4f4b-3d53-4fc4-ba46-4b1c20d015a9?utf8=%E2%9C%93&sort=title_ssi+asc&per_page=10&locale=en) with several items and click on it. click to see the public view of it. 
- [ ] By Default, title A-Z should be selected and the works should be sorted.

## Screenshot

![743](https://github.com/scientist-softserv/palni-palci/assets/10081604/1665982e-da8d-4d49-8c89-28ff055e0697)

**Comment by jillpe** [comment]
SoftServ QA: Pass ✅ 

[Collection URL](https://demo.commons-archive.org/collections/687a4f4b-3d53-4fc4-ba46-4b1c20d015a9?utf8=%E2%9C%93&sort=title_ssi+asc&per_page=10&locale=en)

<details><summary>Screenshots</summary>


![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/fe63036a-2a44-438f-8efd-067ed2b874f0)


</details>
