### ISSUE TITLE
In some tenants active users are not being added when invited through the Manage Users page

### ISSUE THREAD

**Issue by ndroark** [scientist-softserv/palni-palci#813]
# Story 

Trying to add a user (ruth@palni.edu) active in other repositories (goshen.hykucommons.org) to another tenant (palni.hykucommons.org) does not return any error but does not add the user. 

# Acceptance Criteria 

- [ ] Invited users are always added to the Registered Users group  

# Testing Instructions 

1. Login as a super admin 
2. Create a new tenant (e.g. `Tenant A`)
3. Navigate to `Tenant A` > Dashboard > Manage Users 
4. Invite a new user who does not already exist in the **application** (i.e. across all tenants, not just one) 
5. Verify that the new user gets added to the Registered Users group in `Tenant A` 
6. Create a new tenant (e.g. `Tenant B`) 
7. Navigate to `Tenant B` > Dashboard > Manage Users 
8. Invite the same user from Step 4. Do not give it any individual roles in the invite form 
9. Verify that the user gets added to the Registered Users group in `Tenant B`

# Notes

**Update:**

The primary issue here is that invited users who already have an account (i.e. an instance of `User` in the database) were not being added to the tenant's Registered Users group. This meant that, if a user was invited with no specific roles, they simply wouldn't show up in the tenant at all. 

---

Adding a user to a second tenant without a role fails to add them to the new tenant.  This probably occurs with users who have been previously deleted from a tenant as well.  

The expected behavior is the user will be added to the registered users group when no role is selected, and the user doesn't have an individual role.

~~This is probably an issue with the Persona gem~~

**Comment by ShanaLMoore** [comment]
<img width="950" alt="image" src="https://github.com/scientist-softserv/palni-palci/assets/10081604/39d08c55-49af-4664-ac73-527f6c8116ab">

**Comment by labradford** [comment]
I created a test user [leaann+test@scientist.com](mailto:leaann+test@scientist.com) That user has admin privileges  in the [qa.hykucommons.org](http://qa.hykucommons.org/) tenant. That user recieved and email and is activated in this tenant.
I then went to [demo.hykucommons.org](http://demo.hykucommons.org/) and put that email in the add/invite users form. I selected work editor as the role in the form and clicked the Invite User button.
I did not receive an email that I was added to the new tenant. But my test user shows up in the users list and has the role that I selected.

**Comment by labradford** [comment]
Adding a user to a second tenant without a role fails to add them to the new tenant. 

The expected behavior is the user will be added to the registered users group when no role is selected, OR a new Registered User role would be added as the default role if the role field is not selected in the form.

**Comment by labradford** [comment]
Crystal and I were able to add this user to the Palni tenant into the Registered Users group

**Comment by ndroark** [comment]
Interesting, not sure what was going on with my attempts, but I see it active in the tenant now. I'll go ahead and close the ticket for now and reopen if I see the behavior again.

**Comment by labradford** [comment]
We were able to achieve this via the Rails console in Rancher. There is still behavior that needs to be fixed when adding users to the UI

**Comment by jillpe** [comment]
SoftServ QA: ✅ Pass!

user: jill@scientist.com

[813qa user list](https://813qa.commons-archive.org/admin/users?locale=en)

<details><summary>Screenshots</summary>


![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/7e27014c-ae1f-4b85-9c8c-aef298cfe797)


</details>


[813example user list](https://813example.commons-archive.org/admin/users?locale=en)

<details><summary>Screenshots</summary>


![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/9998cc77-5253-4ba6-93b3-eb3152a4ddc6)



</details>
