### ISSUE TITLE
Improve file manager and PDF.js interaction

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#839]
# Story

Currently, the file manager isn't selecting between PDFs for display in the viewer.  If there are multiple PDFs, changing the representative media/thumbnail doesn't affect which one displays in the viewer.  

Add the ability for the user to change which PDF is being displayed through the file manager selection.

# Screenshots / Video

https://github.com/scientist-softserv/palni-palci/assets/19597776/a56bb856-de66-4e17-bafb-ef2d0ae632a1

# Testing Instructions

The following must be true before you begin: 

1. PDF.js feature flag is on. Admin Dashboard > Settings > Features 

<img width="1128" alt="image" src="https://github.com/scientist-softserv/palni-palci/assets/10081604/bfe61c3c-2536-4ab5-aa79-a16f8a61993f">

2. Use a work that has imported a variety of file types (PDFS and Jpgs): https://demo.commons-archive.org/concern/generic_works/1d23ff36-15c5-4450-bf95-e01e1f83fcca?locale=en

Click on the file manager
- [ ] when a user selects a non pdf file type as the representative media and click save. **(NOTE: Yes, the save button looks disabled. please click it anyways)**  Go back to the work's show page. the UV displays the jpg.
- [ ] when a user selects a pdf file as the representative media and click save. Go back to the work's show page. the PDJ.js viewer will display the selection.

**Comment by jillpe** [comment]
Can you provide more details here? What do you you want to see here?

**Comment by ndroark** [comment]
Currently, the file manager isn't selecting between PDFs for display in the viewer. If there are multiple PDFs, changing the  representative media/thumbnail doesn't affect which one displays in the viewer. I *think* the viewer displays the first uploaded or the first identified PDF associated with the work, but that may not actually be what it is doing. 

If there is a non-pdf work (in this case, a jpeg), you can select it as representative and the system will load the IIIF viewer to display the image, but if afterward you select a pdf as representative, the system still displays the jpeg.

Ideally, the file manager should dictate what file is displayed, both in cases with multiple PDFs and no other file type, and with mixed file types. Users should be able to use the file manager to toggle between a Jpeg as representative (with the UV loading) and a PDF as representative (with whatever PDF viewer is set as default loading).

**Comment by kirkkwang** [comment]
Hi @ndroark, when you say that you want the Users to be able to use the file manager, you mean public users? Not admins?

**Comment by ndroark** [comment]
No, only users with edit access to a work should be able to use the file manger for that work. That is the current functionality and we don't want to change that aspect of it.

**Comment by jillpe** [comment]
SoftServ QA: 
[Work URL](https://demo.commons-archive.org/concern/generic_works/1d23ff36-15c5-4450-bf95-e01e1f83fcca?locale=en)

https://demo.commons-archive.org/concern/generic_works/1d23ff36-15c5-4450-bf95-e01e1f83fcca?locale=en
Click on the file manager

- [x] when a user selects a non pdf file type as the representative media and click save.
  - (NOTE: Yes, the save button looks disabled. please click it anyways) Go back to the work's show page. the UV displays the jpg.
<details><summary>Screenshots</summary>


![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/a224edd9-183b-4ef3-9a29-5381be5b3839)



![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/56e0d153-dfee-441a-8adf-d27c65fbf764)


</details>


- [x] when a user selects a pdf file as the representative media and click save. Go back to the work's show page. the PDJ.js viewer will display the selection.
<details><summary>Screenshots</summary>


![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/23b0d0ad-1437-4a6a-914a-8852dd15d124)



![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/0a5d284f-a0d6-437b-b323-fa3760591061)


</details>
