### ISSUE TITLE
add link back to parent work from child

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#840]
## Summary
Currently, when you navigate to a child work's show page, there is no link to take the user back to the parent work. 

![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/3a9f1b2f-fc7b-4e1b-8d27-bb27b5b7d80f)

## Accepted Criteria
- [ ] The Work Page for child works should list "Part of: [Parent Work]" as the final relation under Relations in the same format as "In Collection:"

## Testing Instructions
- Navigate to a child work show page
  - [ ] The Work Page for child works should list "Part of: [Parent Work]" as the final relation under Relations in the same format as "In Collection:"
  - [ ] Clicking the 'Part of: [Parent Work]' navigates the user to that work show page

**Comment by ndroark** [comment]
Acceptance criteria: The Work Page for child works should list "Part of: [Parent Work]" as the final relation under Relations in the same format as "In Collection:"

**Comment by jillpe** [comment]
SoftServ QA: 

[Work URL](https://demo.commons-archive.org/concern/generic_works/ff57f1b2-5cb5-434d-819f-80dabf8a900b?locale=en)
  - [x] The Work Page for child works should list "Part of: [Parent Work]" as the final relation under Relations in the same format as "In Collection:"
  - [x] Clicking the 'Part of: [Parent Work]' navigates the user to that work show page



https://github.com/scientist-softserv/palni-palci/assets/84697174/58561fee-e900-498b-bede-9e01a45db2a2

**Comment by ndroark** [comment]
Parent work doesn't show to viewers who are not logged in. This is the behavior that admin sets use, it should follow the behavior used by regular collections.

**Comment by ShanaLMoore** [comment]
QA RESULTS: Check with @ndroark 

If this doesn't pass your review, could you point us to an example in production? 

I am trying to understand what you mean. 

I logged into staging as an superadmin user and went to a child work: https://dev.commons-archive.org/concern/images/5267f9fb-ae5b-43db-84b4-92540969e2aa?locale=en

when I visit a child work I see part of. It also has a collection and admin set displayed: 


![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/77ec0fd2-86e3-4779-9c66-e7b43fad5220)



when I log out and go to the same work, I see part of and the collection, but not the admin set. 


![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/1ac7dc81-dbea-4c64-8efa-68a7a5bd48be)


I'm seeing the same behavior in prod. If this is OK then it passes QA.

**Comment by ndroark** [comment]
In staging, I just added a new work and then a new child to that work, and when logged out the relations box shows blank. I'm not sure why your example work is listing it when logged out and this one isn't. https://nic726.commons-archive.org/concern/generic_works/905c0ac8-5f27-4585-908b-e37850567292?locale=en

**Comment by ShanaLMoore** [comment]
> In staging, I just added a new work and then a new child to that work, and when logged out the relations box shows blank. I'm not sure why your example work is listing it when logged out and this one isn't. https://nic726.commons-archive.org/concern/generic_works/905c0ac8-5f27-4585-908b-e37850567292?locale=en

Oh weird, I see it blank too. hmm 🤔 I'll pull it back and see what's going on. @ndroark

**Comment by kirkkwang** [comment]
SoftServe QA

Public user (not signed in), i see the public collection and the public parent work:

![Image](https://github.com/scientist-softserv/palni-palci/assets/19597776/9194607f-852e-4720-a929-0df4012614ae)

Signed in admin user, i see all the parents

![Image](https://github.com/scientist-softserv/palni-palci/assets/19597776/c7fa06e4-8da3-4add-8ffc-b86a745d205f)

Public user (not signed in) with no collection

![Image](https://github.com/scientist-softserv/palni-palci/assets/19597776/d9da9b38-74d4-4ce0-9a29-b64f1702025d)

Signed in admin user, work with no collection

![Image](https://github.com/scientist-softserv/palni-palci/assets/19597776/69d2d8da-fa49-40ae-953e-9b6ebca16d7b)
