### ISSUE TITLE
Refine account settings page to limit options for non-super admins

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#841]
## Summary
The Account Setting page has too many options for non-super admins, and Pals would like to limit their options. 

<details><summary>Screenshots</summary> 

![image](https://github.com/scientist-softserv/palni-palci/assets/84697174/3517fb7a-8888-4de9-a5e1-bf3c762c2f62)

</details>

Hide certain settings from non-superadmins on the Account settings dashboard page as prescribed by the client.

# Acceptance Criteria

A non super admin user should **NOT** see the following fields: 

- [ ] :~contact_email~ See [comments](https://github.com/scientist-softserv/palni-palci/issues/841#issuecomment-1765434879) section for update
- [ ] :contact_email_to,
- [ ] :analytics_provider
- [ ] :file_acl
- [ ] :s3_bucket,
- [ ] :oai_prefix
- [ ] :oai_sample_identifier,
- [ ] :file_size_limit

# Testing Instructions

Visit the options [here](https://demo.commons-archive.org/admin/account/edit?locale=en), as a super admin and a non super admin. 

super admin login: support@notch8.com => get password from 1Password
non super admin login: user@example.com => testing123

# Expected Behavior Before Changes

<details> <summary> screenshot (non superadmin user) </summary>

![image](https://github.com/scientist-softserv/palni-palci/assets/10081604/d0babdb3-8b6a-4c1a-9b70-c8b8bc25a02e)

</details>

<details> <summary> screenshot (superadmin user) </summary>

![image](https://github.com/scientist-softserv/palni-palci/assets/10081604/1daf1618-9fc9-462f-8c46-4249294ef721)

</details>

# Expected Behavior After Changes
<details> <summary> screenshot (non superadmin user) </summary>

![image](https://github.com/scientist-softserv/palni-palci/assets/10081604/5029eb16-c3db-47a9-8324-ac3fe3a00e31)

</details>

<details> <summary> screenshot (superadmin user) </summary>

![image](https://github.com/scientist-softserv/palni-palci/assets/10081604/d1e3c47a-76fe-4fd3-ba1a-e5527cefb6e8)

</details>

**Comment by jillpe** [comment]
What do you want non-super admins to see?

**Comment by ndroark** [comment]
Partially, we're not sure what some of these fields are for, and thus we're not sure what could potentially allow users to break systems by changing settings. 

The ones we don't know about are:

- Analytics Provider
- File acl
- OAI prefix
- Oai sample identifier
- S3 Bucket

I think we should also limit File Size Limit to superadmin (I also notice that the text says it should be set to at least 536870912000 but the default value is only 5368709120)

**Comment by ndroark** [comment]
Given the information on ticket 778, we should add Contact Email and Contact Email To to the list of things only superadmins can access. https://github.com/scientist-softserv/palni-palci/issues/778

**Comment by jillpe** [comment]
SoftServ QA: ✅ Pass!

<details><summary>Logged in as a Super Admin:</summary>


![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/9777c2d1-15d9-4596-af7e-d579ce32f284)


</details>

<details><summary>Logged in as a NON Super Admin:</summary>
A non super admin user should NOT see the following fields:

- [x] :contact_email
- [x] :contact_email_to,
- [x] :analytics_provider
- [x] :file_acl
- [x] :s3_bucket,
- [x] :oai_prefix
- [x] :oai_sample_identifier,
- [x] :file_size_limit

![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/4ab89ce4-d3b8-48c7-b81d-ed8a170eb2cb)


</details>

**Comment by ndroark** [comment]
We want to retain **Contact email to** for local admins. There is also an issue with some tenants having different Account settings pages (see au-archives.hykucommons.org, compare to sju-library.hykucommons.org).

**Comment by ShanaLMoore** [comment]
@ndroark What do you mean by local admins? These fields should only show to superadmins with our changes.

**Comment by ndroark** [comment]
I mean that we need to revert that change for the Contact Email To field. It should be accessible to non-super admins, since it's something they can set and change without additional configuration. See Rob's comment here https://assaydepot.slack.com/archives/C0313NKC08L/p1697499227224089?thread_ts=1697487952.830559&cid=C0313NKC08L

**Comment by ShanaLMoore** [comment]
Gotcha. For clarity of this ticket, could you list the fields that should only be for superadmins? This ticket listed many fields. We currently have them defined in a constant, [here](https://github.com/scientist-softserv/palni-palci/blob/main/app/models/account.rb#L49-L52) cc @ndroark 

```ruby

  SUPERADMIN_ONLY_SETTINGS = [:contact_email, :contact_email_to,
                              :analytics_provider, :file_acl, :s3_bucket,
                              :oai_prefix, :oai_sample_identifier,
                              :file_size_limit].freeze
```

**Comment by ndroark** [comment]
For sure, that same list without the Contact email to. So the superadmin only settings are :

:contact_email, :analytics_provider, :file_acl, :s3_bucket, :oai_prefix, :oai_sample_identifier, :file_size_limit

**Comment by ShanaLMoore** [comment]
# QA RESULTS: 

Tested on: https://dev.commons-archive.org/

SUPER ADMIN SHOULD SEE: 

- [ ] contact email
- [ ] analytics provider
- [ ] file acl
- [ ] s3 bucket
- [ ] oai prefix
- [ ] oai sample identifier
- [ ] file size limit

![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/39ddb15f-ba3f-4c0d-a862-0e8b0b69bc6f)




ADMIN SHOULD **NOT** SEE: 

- [ ] contact email
- [ ] analytics provider
- [ ] file acl
- [ ] s3 bucket
- [ ] oai prefix
- [ ] oai sample identifier
- [ ] file size limit



![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/441d10ea-7ef3-4018-a911-48d16b987dcf)

**Comment by ndroark** [comment]
The help text for "Contact email" and "Contact email to" are reversed

**Comment by kirkkwang** [comment]
switched the hint text, will be doing a hot fix deploy soon

<img width="1281" alt="image" src="https://github.com/scientist-softserv/palni-palci/assets/19597776/72afc51e-02c4-48a0-afdd-78ab247d73d5">
