### ISSUE TITLE
IR theme - The resource type icons do not link to search results, which is counterintuitive

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#842]
## Summary
Currently the resource type icons in the IR theme do not link to the search results, and Pals would like them to do so.

Screenshot below is of the icons that are not 'clickable':
<img width="967" alt="Screen Shot 2023-10-06 at 10 03 21 AM" src="https://github.com/scientist-softserv/palni-palci/assets/84697174/4f660094-2ed2-4bde-9c88-2803ef4ddbc7">

## Accepted Criteria
- [ ] As a user, I can click on a resource type icon, in the IR theme, and it will take me to the search results for that resource type icon

# Testing Instruction

1. switch to institutional repository theme
2. Add resource types to works
3. Navigate to the icon bar of the home page. 
4. The user should see resource types icons and click on them to perform a catalog search.

## Notes 

See PR for demos: 
- https://github.com/scientist-softserv/palni-palci/pull/851

**Comment by ShanaLMoore** [comment]
# QA RESULTS: Pass ✅ 

Tested on: https://demo.commons-archive.org/?locale=en



![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/58facef6-1a94-4dd7-9c6e-212cafc8c889)
