### ISSUE TITLE
Bug: works not populating for approval in Wabash tenant

### ISSUE THREAD

**Issue by ndroark** [scientist-softserv/palni-palci#859]
In the wabash.hykucommons.org tenant, works are showing on the works dashboard as pending approval, but the work page cannot be accessed, and the Review Submissions tab is empty. Example work page: https://wabash.hykucommons.org/concern/generic_works/30ff1df1-0c20-4e55-b97a-46533202a8ff?locale=en

**Comment by bkiahstroud** [comment]
I believe we've encountered this before on other tenants. IIRC, it's related to the Groups with Roles feature. If someone else ends up picking this up, please loop me in!

**Comment by ShanaLMoore** [comment]
Closing because it's a Duplicate of: https://github.com/scientist-softserv/palni-palci/issues/886
