### ISSUE TITLE
🐛 Works locked in pending status error

### ISSUE THREAD

**Issue by ndroark** [scientist-softserv/palni-palci#886]
In some production tenants, works by some users are being locked in a Pending Review status, and cannot be viewed or approved by any users. Other users can still add works in the tenants as normal. 

This occurs in admin sets with mediated deposit, to users with admin settings (due to being in the admin group), to users who have previously successfully uploaded works. Works also are not listed in the Review Submissions tab. 

Examples here: https://wabash.hykucommons.org/concern/generic_works/30ff1df1-0c20-4e55-b97a-46533202a8ff?locale=en and https://desales.hykucommons.org/concern/generic_works/7212295d-ddfa-4c3b-99e2-140941776b48?locale=en

I have not noticed it in staging. I have not seen it in any work I personally have uploaded from a superadmin account, both of the examples I've seen have been added by users who are in both the repository administrators and registered users groups in their respective repos.

![Image](https://user-images.githubusercontent.com/117871943/277790874-a5d2fb17-baa1-4a41-9776-247c3fe2045c.png)

## Notes
Kiah would be a good resource to reach out to, until we get ramped up on groups/roles. He implemented the groups/roles work for hyku

**Comment by ShanaLMoore** [comment]
# [Additional Notes](https://assaydepot.slack.com/archives/C0313NKC08L/p1698178208583439?thread_ts=1698079969.750519&cid=C0313NKC08L)

<img width="526" alt="image" src="https://github.com/scientist-softserv/palni-palci/assets/10081604/c90c4970-cfc0-4c00-94fa-3fa1d22aa014">

**Comment by ShanaLMoore** [comment]
So far I haven't been able to reproduce this locally. 

Some notable details though (maybe?) 

the linked example work is part of Default Admin Set. 

### Default Admin Set: 



![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/52b2683a-87d5-4b50-9b02-bae8084ac593)




![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/73ffce3f-75ff-4df1-99e3-4b10e1cb51e0)

### Default Admin Set is Managed by: 



![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/b8df0073-47f8-48d3-a30a-c6f09b26956b)





![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/6c2ef09a-0a1e-4dd9-afae-7642cc0283b0)

**Comment by ShanaLMoore** [comment]
Does "the script Kiah ran" refer to `rake hyku:roles:grant_workflow_roles` ? ref: https://github.com/scientist-softserv/palni-palci/blob/cf8e203bfd6007bb4e8eed0e7cd4e307249d8b94/lib/tasks/roles.rake#L65-L73

**Comment by ShanaLMoore** [comment]
Locally my workflow roles are: 



![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/103c3337-668a-4f4c-a224-5c78266be16a)


I'll try removing the approving ones and match [ndroark@anderson.edu](mailto:ndroark@anderson.edu) settings, to see if I can produce this issue. Stay tuned!

**Comment by ShanaLMoore** [comment]
To 

> Does "the script Kiah ran" refer to `rake hyku:roles:grant_workflow_roles` ? ref:
> 
> https://github.com/scientist-softserv/palni-palci/blob/cf8e203bfd6007bb4e8eed0e7cd4e307249d8b94/lib/tasks/roles.rake#L65-L73

As breadcrumbs for my future self, Kiah resolved this by logging into each tenant in rancher and running `     RolesService.grant_workflow_roles_for_all_admin_sets! `

We noticed that the Repository Administrators had no roles for both accounts. On tenant creation, this group should auto get a bunch of workflow roles to let them do all the things (such as reviewing/approving works). 

BEFORE running the command (unable to review/approve works logged in as superadmin):

<img width="948" alt="image" src="https://github.com/scientist-softserv/palni-palci/assets/10081604/7b65503d-7fdf-4868-973d-1bc873f84db6">

![image](https://github.com/scientist-softserv/palni-palci/assets/10081604/7e5577dc-4bc1-499d-b56b-a8c4dc740037)

 

AFTER running this command (logged in as superadmin): 


![Screenshot 2023-10-25 at 10-57-12 Index Workflow Role __ Hyku Commons](https://github.com/scientist-softserv/palni-palci/assets/10081604/d6499355-c1f7-4c6d-9969-e6b08bd94608)

![image](https://github.com/scientist-softserv/palni-palci/assets/10081604/bda42cf2-bb40-4fe0-b461-b4adc52bccf2)
