### ISSUE TITLE
:bug: Wav files not playing in audio player

### ISSUE THREAD

**Issue by ndroark** [scientist-softserv/palni-palci#887]
## Summary
Example: https://franklin.hykucommons.org/concern/generic_works/91b887eb-d13e-4a8b-a9e6-3bd29f120c6f?locale=en

Pals is having trouble with Wav files not playing in the audio player

## Acceptance Criteria
- [ ] A user should be able to attach a wav file and have it play in the viewer. 

## Testing Instructions

Create a work and attach a .wav file

**Comment by jillpe** [comment]
This is possibly relevant to the [mp4 issue](https://github.com/scientist-softserv/palni-palci/issues/852). This will be a spike to determine what exactly is failing (if this singular thing or all of the things failed).

**Comment by ShanaLMoore** [comment]
# Dev Notes

the [manifest.json](https://franklin.hykucommons.org/concern/generic_works/91b887eb-d13e-4a8b-a9e6-3bd29f120c6f/manifest.json) loads properly. 

Downloading the wav file fails and leads to 500



![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/b8a178aa-f3ef-4cf6-b2c0-198b099f7482)

**Comment by ShanaLMoore** [comment]
cc @kirkkwang I think you have the most a/v experience here. Instead of continuing spending time on this spike I'm going to push this back to ready for dev. Hopefully the above notes will help. Also I'm happy to pair to learn, if you pick it up.

**Comment by kirkkwang** [comment]
thanks @ShanaLMoore I'll take a look when i'm done with this roles ticket!

**Comment by kirkkwang** [comment]
@ndroark do you happen to have the wave file that's being problematic?  It looks like the file never got attached to the file set

**Comment by ndroark** [comment]
Here is an example: https://franklin.hykucommons.org/concern/generic_works/c5bee722-7d44-4030-bca4-77b3081ac051?locale=en

**Comment by kirkkwang** [comment]
I can't download that file either, which is really strange that both these WAV files did not properly ingest, do you have access to the actual file anywhere?

**Comment by ndroark** [comment]
I don't have immediate access to the files but I am confident I can get access to copies from the students who uploaded them.

**Comment by ShanaLMoore** [comment]
# QA Results:
