### ISSUE TITLE
Create script to remove all instances of a specific file that has been uploaded in a tenant (placeholder PDF files)

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#912]
## Summary
Want to remove "HykuCommonsPlaceholder.pdf" and "hykuplaceholderarchives.pdf" from [dickinson.hykucommons.org](http://dickinson.hykucommons.org/)

Pals is okay if this is a one time script that SoftServ runs. 

## Acceptance Criteria
- [ ] Script to remove all instances of "HykuCommonsPlaceholder.pdf" and "hykuplaceholderarchives.pdf" from [dickinson.hykucommons.org](http://dickinson.hykucommons.org/) has been run

## Testing Instructions

Create several works, upload each file and set them as their thumbnail:

[hykuplaceholderarchives.pdf](https://github.com/scientist-softserv/palni-palci/files/13601851/hykuplaceholderarchives.pdf)

[HykuCommonsPlaceholder.pdf](https://github.com/scientist-softserv/palni-palci/files/13601852/HykuCommonsPlaceholder.pdf)

After running the script, these works should no longer be attached to the works.

**Comment by jillpe** [comment]
What do you want this to look like? (Do you want to provide the file name and it runs the script in the UI? If so, who has permission to do that?)

**Comment by ShanaLMoore** [comment]
maybe something like this? TODO: test on staging. 

Create several works, upload each file and set them as their thumbnail: 



[hykuplaceholderarchives.pdf](https://github.com/scientist-softserv/palni-palci/files/13601851/hykuplaceholderarchives.pdf)



[HykuCommonsPlaceholder.pdf](https://github.com/scientist-softserv/palni-palci/files/13601852/HykuCommonsPlaceholder.pdf)


After running the script, these works should no longer be attached to the works. 


```ruby


namespace :hyku do
  desc "Delete specific thumbnails for dickinson account"
  task delete_dickinson_thumbnails: :environment do
    account_cname = "dickinson.hykucommons.org"

    Account.find_each do |account|
      next unless account.cname == account_cname

      begin
        switch!(account.cname)
        puts "********************** switched to #{account.cname} **********************"

        Hyrax.config.curation_concerns.each do |cc|
          next if cc.count.zero?

          puts "********************** checking #{cc}s **********************"

          cc.find_each do |work|
            if work.thumbnail && (work.thumbnail.title == "HykuCommonsPlaceholder.pdf" || work.thumbnail.title == "hykuplaceholderarchives.pdf")
              work.thumbnail.destroy(eradicate: true)
              puts "Deleted thumbnail for #{work.id}"
              next
            end
          end

          puts "********************** updated #{cc}s **********************"
        end
      rescue StandardError => e
        puts "********************** error: #{e} **********************"
        next
      end
    end
  end
end
```

**Comment by ShanaLMoore** [comment]
# QA Results:

**Comment by ndroark** [comment]
I am seeing some works in Dickinson that still have the file, e.g. https://dickinson.hykucommons.org/concern/generic_works/933487b5-287d-409d-ad3d-1a221a6778f8?locale=en

**Comment by kirkkwang** [comment]
@ndroark We did not actually run the script at the time, but i just finished running it, can you check now?

**Comment by ndroark** [comment]
I was wondering if that was the case. Looks like the file is removed, but on search results I'm seeing a broken link instead of the generic thumbnail. My guess is that the next reindex will take care of that? 
![Screenshot(74)](https://github.com/scientist-softserv/palni-palci/assets/117871943/6e1a3c83-7a66-4b41-b9fd-69fbcb795731)

**Comment by kirkkwang** [comment]
hmmm that's interesting, i'm not seeing the broken thumbs

<img width="1182" alt="image" src="https://github.com/scientist-softserv/palni-palci/assets/19597776/8f3877c3-2c50-4078-a47f-7781c630d620">

can you check it cache cleared just in case?
