### ISSUE TITLE
shared search implementation

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#915]
⚠️ This will require a reindex ⚠️ 

## Summary
Pals would like the Repository name to display on the listings in shared search results. Their goal is to have it operate like [British Library's](https://iro.bl.uk/catalog?utf8=%E2%9C%93&search_field=all_fields&q=biology). They would like the displayed repo to link back to the original repository home page and for the repository to be facet-able. 

<details><summary>BL Screen Shot</summary>
<img width="1338" alt="Screen Shot 2023-12-01 at 11 15 54 AM" src="https://github.com/scientist-softserv/palni-palci/assets/84697174/7ff8ed2c-f892-405a-99bd-a1b5416a5b8a">

</details>

Note from client meeting 2023-12-04:
Follow the logic of OAI, use the field of application name and if that is missing add the URL

## Acceptance Criteria
- [ ] The repository name is displayed on listings in shared search results like British Library's
  - [ ] the field of application name is used for the repository name and if that is missing add the URL
- [ ] The repository name that is displayed links back to the original repository home page
- [ ] The repository name is facet-able
- [ ] When the tenant doesn't have an institution name set, it will display its domain url

## Testing Instructions

Perform an empty catalog search using the [search tenant](https://search-test-nd.commons-archive.org/) on staging. 
Verify the Acceptance Criteria

**Comment by jillpe** [comment]
How do you want this to display? Name? Url?

Should it be a link? If so, where to? 

Do you want this to be a facet?

**Comment by aahurford** [comment]
Would like it to operate similarly to the BL's shared search: https://iro.bl.uk/catalog?utf8=%E2%9C%93&search_field=all_fields&q=biology

Yes, should link back to original repository

Ideally, it would be a facet as well

**Comment by ShanaLMoore** [comment]
This will requires a reindex

**Comment by ShanaLMoore** [comment]
@ndroark What should happen if the institution doesn't have a value for institution_name? 

Should I 
- display the domain name?
- display a generic "Research Repository?" (this is what BL does)
- display nothing?



![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/e66b25e8-1f63-4605-b92f-417b21c237ec)

**Comment by ndroark** [comment]
Display the domain name.

**Comment by ShanaLMoore** [comment]
QA On hold until we reindex staging

**Comment by jillpe** [comment]
SoftServ QA: Pass ✅ 

- [x] The repository name is displayed on listings in shared search results like British Library's
  - [ ] the field of application name is used for the repository name and if that is missing add the URL
- [x] The repository name that is displayed links back to the original repository home page
- [x] The repository name is facet-able
- [ ] When the tenant doesn't have an institution name set, it will display its domain url

<details><summary>Screenshots/Videos</summary>
Listings display repository name


![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/16eeecf3-6b72-4cea-9796-af7860a354c0)


Repository name links to their home page


https://github.com/scientist-softserv/palni-palci/assets/84697174/d4919b6b-2af6-4c94-b6d4-a918ecffd7cf

Repository is Facet-able


![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/441425d6-83d9-4e1f-9a5e-648f5a0dc935)

URL displays if institution name is missing


![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/dbaabb65-a3ed-424c-9327-89795c0114c2)


</details>

**Comment by ndroark** [comment]
Some of the results from this search aren't showing an institution name. Adding an institution name to the originating tenant doesn't change that result. https://search.commons-archive.org/catalog?utf8=%E2%9C%93&search_field=all_fields&q=

**Comment by ShanaLMoore** [comment]
Hmm. This is because it's pulling the value from solr and required a reindex after updating the institution name @ndroark 



![Image](https://github.com/scientist-softserv/palni-palci/assets/10081604/be3830eb-50cd-4e95-bd0a-e9e14fac4f95)



When I edit and save the work without making any changes, it got populated. And edit/save triggers a reindex.  

I'll need some time to think about how to solve this.

**Comment by ShanaLMoore** [comment]
This bug is present in BL as well.

**Comment by ShanaLMoore** [comment]
@ndroark Since this is an existing bug, could we consider moving the bulk of the work (this ticket) forward and I'll make a separate bug ticket? 

Basically the issue is that updates to the tenant account's data (aka the institution name) currently would trigger an reindex of that entire tenant for the works to receive the update. 
 
We will have to reindex all of staging and prod when we deploy this, so hopefully it won't immediately be noticeable? I'll continue thinking about a solution in the meantime. 

I understand if you'd rather wait though and keep it altogether. Just let me know.

**Comment by ShanaLMoore** [comment]
@ndroark I just got done chatting with Rob about our options. This is something we should discuss in our next meeting for the sake of an easier convo. 

Re-indexing is required for the tenant for its works to receive the updates. I wonder what BL's process is for this. 🤔 

Again, this would be better to demo and talk through but if you insist, Rob's recommendation was to add a button or checkbox to this page that will trigger a re-index. 

Maybe it's something exposed only to superadmins. 

We'd definitely want some help text or an "are you sure?" pop up box to appear because reindexing the tenant is a costly operation. 

But basically, unfortunately the behavior you are seeing is valid, and reindexing is required to solve it.

**Comment by ShanaLMoore** [comment]
@ndroark You're right. In those cases for some reason those works didn't get re-indexed. 

Perhaps there were errors when I did the mass reindex on staging, that I didn't notice before. Reindexing them now updating them appropriately.

**Comment by ndroark** [comment]
Looks good to me, no problems with the reindex issue. I'll move it to deploy.

**Comment by ShanaLMoore** [comment]
client verification on hold until reindexing jobs complete

**Comment by ndroark** [comment]
From post-reindex testing: 

Some repositories where the application name was filled in before the reindex are still using the URL instead (e.g., https://search.hykucommons.org/catalog?f%5Baccount_institution_name_ssim%5D%5B%5D=alpa.hykucommons.org&locale=en&q=&search_field=all_fields)

**Comment by ndroark** [comment]
On repository is being called PVCC Research Repository (https://search.hykucommons.org/catalog?f%5Baccount_institution_name_ssim%5D%5B%5D=PVCC+Research+Repository&locale=en&q=&search_field=all_fields) while that doesn't match any of its labels, so I'm not sure where the system is pulling that name from

**Comment by ndroark** [comment]
Faceting for the Cooper Union institution returns an error page [https://search.hykucommons.org/catalog?f%5Baccount_institution_name_ssim%5D%5B%5D=The+Co[…]+Research+Repository&locale=en&q=&search_field=all_fields](https://search.hykucommons.org/catalog?f%5Baccount_institution_name_ssim%5D%5B%5D=The+Cooper+Union+Research+Repository&locale=en&q=&search_field=all_fields)

**Comment by ndroark** [comment]
I just realized the acceptance criteria has conflicting language. 

> - > - [ ] the field of application name is used for the repository name and if that is missing add the URL
> - [ ] When the tenant doesn't have an institution name set, it will display its domain url

In the actual code, the search repository is pulling from the institution name, not the application name?

**Comment by jeremyf** [comment]
> In the actual code, the search repository is pulling from the institution name, not the application name?

Yes.  It pulls from the institution name (and failing that it uses the CNAME)

**Comment by ndroark** [comment]
We're fine leaving the Institution name as the field being utilized, but we want to drop the "Research Repository" addition. It's just not accurate for some of our institutions, whose tenants are not research repositories. 

Once that and the issue with the Cooper Unions repository are changed, we're ready for the search bar on the public page to go live.

**Comment by jeremyf** [comment]
I wrote [the following in Slack](https://assaydepot.slack.com/archives/C0313NKC08L/p1705609581746769?thread_ts=1705607524.515499&cid=C0313NKC08L)

> Following up on this:
> 
> The conditional handling for the errors with collection badges is here: https://github.com/scientist-softserv/palni-palci/issues/951; and is merged in main
> This has not been reviewed
> - There are other code in main that is partially reviewed.
> - SoftServ needs to perform a deploy to production
> - SoftServ need to then schedule a reindex all tenants
> 
> Ultimately we have things that are ready for QA that cannot be easily verified in piece meal and require production data to come close to being able to fully vet the interactions.
> 
> My recommendation:
> 
> - Deploy the current main branch to staging and production then seek verification.
> - Test the splash page search tenant with the Cooper Unions facet; assuming that does not raise an exception, we then proceed with running a reindex
> 
> @Nic Don Stanton-Roark thoughts?
> 
> Part of the challenge is that the QA process and active work merging into main are at odds when both are moving at different paces.
> 
> There are ways around this, but they are VERY arduous and create lots of room for more code chaos.
