### ISSUE TITLE
Spike: how to identify GA downloads/if it's possible

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#919]
## Summary
Pals was wondering how to identify downloads/if it's possible with their versions (hyku, hyrax, GA) in regards to statistics from GA

## Acceptance Criteria
- [ ] The above question is answered and given to the client

**Comment by jeremyf** [comment]
This is a breadcrumb for future work; there might be clues as to dimensions necessary in the [GA4 work I did](https://github.com/scientist-softserv/hyrax-analytics-g4/blob/6452ea5255d465c9a744c47704b1f774d84335d5/lib/hyrax/analytics/g4/remote_daily_report.rb)

**Comment by kirkkwang** [comment]
There needs to be a change in the data that is sent with all the file_set media pages, but after that there should be a place to set it up in GA to look at the stats, I'm not an expert in GA but i set up the `label` custom dimension and see this:
<img width="1640" alt="image" src="https://github.com/scientist-softserv/palni-palci/assets/19597776/ec32bd59-4ba9-45b4-824b-0b9930b164e4">

Those should be the ids of the file sets that i was randomly donwloading
