### ISSUE TITLE
Homepage shared search box

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#947]
## Summary
Pals is hoping to get a search box on the hykucommons.org homepage that links specifically to the search.hykucommons.org repository. They would like the search box to be an input field that can be used to for searching the input

They would like there to be help text under the search box that says something along the lines of 'Search all contents here'

## Acceptance Criteria
- [ ] There is a search box on hykucommons.org that links to the search.hykucommons.org repository
  - [ ] Pals would like the search box to be listed above the "Browse our partner repositories" section and to be labeled in the same font, size, and justification "Search across all repositories:"
- [ ] The search box is in input field, and searches the input
- [ ] We would like the search bar to open a search on search.hykucommons.org in a new tab
- [ ] Help text under the search box that says 'Search all contents here'
  - [ ]  Pals is double checking the help text under the search box, and will let us know before the deploy window if we want to modify it.

**Comment by ndroark** [comment]
Some additional clarification: 

- [ ] We would like the search box to be listed above the "Browse our partner repositories" section and to be labeled in the same font, size, and justification "Search across all repositories:"
- [ ] We would like the search bar to open a search on search.hykucommons.org in a new tab
- [ ] I'm double checking the help text under the search box, and will let you know before the deploy window if we want to modify it.

**Comment by jeremyf** [comment]
Here's a screenshot of what I have for a local test instance:

<img width="1107" alt="Screenshot 2023-12-14 at 4 01 53 PM" src="https://github.com/scientist-softserv/palni-palci/assets/2130/4046de97-0338-4b92-b95e-74691b75011a">

The URL for the search is derived by first checking if there's a server variable; if not it checks if there's any tenant with search_only; and failing that it is "search.hykucommons.org"

**Comment by ndroark** [comment]
This mockup looks good. With the way that it's laid out, we don't think we need help text under the search bar.

**Comment by jeremyf** [comment]
QA shows the form:

<img width="1177" alt="Screenshot 2024-01-08 at 3 16 24 PM" src="https://github.com/scientist-softserv/palni-palci/assets/2130/8243d500-66f9-473b-b4b2-7cd69770474d">

Typing "Goshen" into the search field then submitting the search, opens a new tab (prompting for HTTP Auth) and "Goshen" is the default search parameter:

<img width="1244" alt="Screenshot 2024-01-08 at 3 17 09 PM" src="https://github.com/scientist-softserv/palni-palci/assets/2130/04b44813-3f5c-4712-8aa9-c7bcf0802c79">
