### ISSUE TITLE
Website Link Bug

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni-palci#960]
## Summary
Clicking the SSO link from the website results in an error, but clicking the link from slack, email or  entering it into the URL works as expected. Due to the website being live, this needs to be worked on in off hours to prevent any interruptions to user experiences.

## Accepted Criteria
- [ ] As an admin user, I can click the SSO link from the ReShare website and it takes me to the expected page and logs me in successfully

**Comment by jillpe** [comment]
Update: 
Coming from the VuFind My Account and clicking the URL to Hyku, the user (who had authenticated into VuFind) is taken first to this screen for about 10 secs:
![image](https://github.com/scientist-softserv/palni-palci/assets/84697174/57d427af-672e-4038-b4d0-65aa75079ff9)

Then after a bit takes they quickly see this:
![image](https://github.com/scientist-softserv/palni-palci/assets/84697174/cac35c5a-3758-4564-8b40-d71ec2fe5732)

And then user is taken here:
![image](https://github.com/scientist-softserv/palni-palci/assets/84697174/7cb3850a-f0ec-4903-99ad-46c62961a113)

The user has no access to the actual document. This is just the cover page and the document is not put into the viewer And why is the Add to collection tab there. The user should only be able to view the document.

The other user accessibility issue is the Hyku document opens in the same tab as VuFind. There is no way to get back to VuFind when they are done. If you use the back arrow on the page the user is just taken back to the Thank you for logging in page and then to document again. If they clock the ReShare logo in the top left hand corner they are brought here (which is useless to them):
![image](https://github.com/scientist-softserv/palni-palci/assets/84697174/7a87e30f-0aa9-4482-a2a8-4100f5ac9ac4)

**Comment by DraxIndustries79** [comment]
1. Share information on configuring UV
2. Ian disabled the open in new tab

Etc.:  Red Box and Share Collections should be addressed

**Comment by kirkkwang** [comment]
Tested locally with the reshare show page theme and I do see the UV, can I get the URL of the, also I don't see the Add to Collection URL when I'm signed out.

Can I get the URL of this work?

![image](https://github.com/scientist-softserv/palni-palci/assets/19597776/8e33e9f4-1fe9-4435-b87b-3e2b82a7f208)

**Comment by jillpe** [comment]
Client confirmed we can close this ticket 1/22/2024
