### ISSUE TITLE
Set up Location name field

### ISSUE THREAD

**Issue by ndroark** [scientist-softserv/palni-palci#964]
## Summary
The Location field relies on GeoNames Web Service. The functionality for this was present but past update broke this integration. 

We would like to 

1. Restore the basic functionality of this field in the standard work upload editor and 
2. Ensure that when incompatible data has been entered in this field (as through Bulkrax import), the work can be edited rather than returning a 500 error when one attempts to edit. 

## Acceptance Criteria
- [ ] The location field is functional in the UI
- [ ] When incompatible data is entered into the Location field on a Bulkrax import/creation of new works, the user can edit it and it saves
- [ ] Location values round-trip correctly

## Testing

- [ ] Make sure in the tenant Account settings, there is a valid geonames username (ask me for one if you don't have one) -Kirk
- [ ] Import from csv [generic_work_locations_test.csv](https://github.com/scientist-softserv/palni-palci/files/14542877/generic_work_locations_test.csv)
- [ ] Export data (NOTE: the locations will now be URIs in the exported CSV)
- [ ] Modify work titles in export CSV
- [ ] Import from export CSV

Verify that titles update and location values still look the same

## Note 

The GeoNames web service username must be specified on each tenant's configuration for this to work in that tenant.

**Comment by jillpe** [comment]
possibly related to 
- https://github.com/scientist-softserv/adventist-dl/issues/693

**Comment by jillpe** [comment]
The location field appears to be functional in demo.commons-archive.org. Still need to verify if it's still broken on the bulkrax part or not

**Comment by jillpe** [comment]
SoftServ QA: ✅ 
Updated Importer
- [Importer](https://dev.commons-archive.org/importers/158?locale=en)
- [Work 1](https://dev.commons-archive.org/concern/generic_works/2f5ec2b0-5e32-4afb-b862-3f1d5fdb9c5e?locale=en)
- [Work 2](https://dev.commons-archive.org/concern/generic_works/56855ad3-b252-4503-ac70-81e7ea5d7b27?locale=en)

<details><summary>Screenshots</summary>


![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/6a47c3b3-ce95-454e-9136-a040de0fd804)



![Image](https://github.com/scientist-softserv/palni-palci/assets/84697174/3fb2afba-1ad5-4979-a78e-00799ff03c05)


</details>
