### ISSUE TITLE
Reindex Pals

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/palni-palci#965]
Reindex prod (works, filesets, and collections) 

related
- #915 
- #947

## Notes
In the future, put a schedule on the calendar to reindex + reminder in slack channels. 
+ assign who follows up and when.

**Comment by jillpe** [comment]
Reindex to start Friday 2/2 after hours

**Comment by ShanaLMoore** [comment]
There are a bunch of errors for filet sets. We will address them in the a future maintenance sprint. 

https://assaydepot.slack.com/archives/C0311DNF3MG/p1706925872653319
