### ISSUE TITLE
Investigate prod server slowness/timeouts

### ISSUE THREAD

**Issue by bkiahstroud** [scientist-softserv/palni-palci#979]
# Story

Recently, production has been running very slow and timing out in some cases. Restarting the pods seems to help temporarily, but it doesn't last. We should investigate an underlying cause. 

Related Slack threads: 
- [Client report 1](https://assaydepot.slack.com/archives/C0313NKC08L/p1709150602772049)
- [Client report 2](https://assaydepot.slack.com/archives/C0313NKC08L/p1709235126983039)
- [Devops thread](https://assaydepot.slack.com/archives/C0313NK4SMS/p1709244573312769) 

# Acceptance Criteria

- [ ]

# Screenshots / Video

<details>
<summary></summary>

</details>

# Testing Instructions and Sample Files

-

# Notes

**Comment by jillpe** [comment]
https://assaydepot.slack.com/archives/C0313NKC08L/p1709332369988219?thread_ts=1709235126.983039&cid=C0313NKC08L

**Comment by jillpe** [comment]
https://assaydepot.slack.com/archives/C0313NKC08L/p1709622573875599?thread_ts=1709588481.717079&cid=C0313NKC08L

**Comment by jillpe** [comment]
confirmed in client meeting 2024-03-11, we can close this ticket
